Repository nucleuscloud/neosync, pull requests merged in 2024-10, with the labels that each got.

#2758 NEOS-1497: implement ability to convert personal account to paid
  backend/gen/go/db/mock_Querier.go
  backend/gen/go/db/querier.go
  backend/gen/go/db/users.sql.go
  backend/gen/go/protos/mgmt/v1alpha1/mgmtv1alpha1connect/user_account.connect.go
  backend/gen/go/protos/mgmt/v1alpha1/user_account.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/user_account.pb.validate.go
  backend/internal/neosyncdb/integration_test.go
  backend/internal/neosyncdb/users.go
  backend/protos/mgmt/v1alpha1/user_account.proto
  backend/services/mgmt/v1alpha1/integration_tests/user-account-service_integration_test.go
  backend/services/mgmt/v1alpha1/user-account-service/users.go
  backend/sql/postgresql/queries/users.sql
  docs/protos/data/proto_docs.json
  frontend/apps/web/components/providers/account-provider.tsx
  frontend/apps/web/components/site-header/AccountSwitcher.tsx
  frontend/apps/web/components/site-header/CreateNewTeamDialog.tsx
  frontend/apps/web/components/site-header/UpgradeButton.tsx
  frontend/apps/web/yup-validations/account-switcher.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/user_account-UserAccountService_connectquery.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/user_account_connect.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/user_account_pb.ts
Labels: enhancement

#2760 Updates Billing Page to include payasyougo, create team
  frontend/apps/web/app/(mgmt)/[account]/settings/billing/page.tsx
  frontend/apps/web/components/site-header/AccountSwitcher.tsx
  frontend/apps/web/components/site-header/CreateNewTeamDialog.tsx
Labels: enhancement

#2761 Buf Generation Greenkeeping
  backend/buf.gen.yaml
  backend/gen/go/protos/mgmt/v1alpha1/api_key.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/api_key.pb.validate.go
  backend/gen/go/protos/mgmt/v1alpha1/auth.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/auth.pb.validate.go
  backend/gen/go/protos/mgmt/v1alpha1/connection.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/connection.pb.validate.go
  backend/gen/go/protos/mgmt/v1alpha1/connection_data.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/connection_data.pb.validate.go
  backend/gen/go/protos/mgmt/v1alpha1/job.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/job.pb.validate.go
  backend/gen/go/protos/mgmt/v1alpha1/metrics.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/metrics.pb.validate.go
  backend/gen/go/protos/mgmt/v1alpha1/transformer.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/transformer.pb.validate.go
  backend/gen/go/protos/mgmt/v1alpha1/user_account.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/user_account.pb.validate.go
  frontend/apps/web/package.json
  frontend/package-lock.json
  frontend/packages/sdk/src/client/mgmt/v1alpha1/api_key-ApiKeyService_connectquery.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/api_key_connect.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/api_key_pb.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/auth-AuthService_connectquery.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/auth_connect.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/auth_pb.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/connection-ConnectionService_connectquery.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/connection_connect.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/connection_data-ConnectionDataService_connectquery.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/connection_data_connect.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/connection_data_pb.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/connection_pb.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/job-JobService_connectquery.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/job_connect.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/job_pb.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/metrics-MetricsService_connectquery.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/metrics_connect.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/metrics_pb.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/transformer-TransformersService_connectquery.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/transformer_connect.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/transformer_pb.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/user_account-UserAccountService_connectquery.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/user_account_connect.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/user_account_pb.ts
Labels: dependencies

#2762 Centralizes some frontend deps to workspace, updates knip
  .github/workflows/frontend.yml
  docs/knip.jsonc
  docs/knip.ts
  frontend/apps/web/app/api/webhooks/keycloak/add-to-crm/route.ts
  frontend/apps/web/app/api/webhooks/keycloak/slack/route.ts
  frontend/apps/web/app/api/webhooks/keycloak/welcome-email/route.ts
  frontend/apps/web/components/ui/checkbox.tsx
  frontend/apps/web/knip.ts
  frontend/apps/web/package.json
  frontend/knip.jsonc
  frontend/package-lock.json
  frontend/package.json
  frontend/packages/sdk/package.json
Labels: dependencies

#2352 NEOS-1254: update onboarding flow
  backend/gen/go/protos/mgmt/v1alpha1/user_account.pb.go
  backend/protos/mgmt/v1alpha1/user_account.proto
  backend/services/mgmt/v1alpha1/integration_tests/user-account-service_integration_test.go
  backend/sql/postgresql/models/models.go
  docs/protos/data/proto_docs.json
  frontend/apps/web/app/(mgmt)/[account]/new/connection/aws-s3/AwsS3Form.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/connection/dynamodb/DynamoDBForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/connection/gcp-cloud-storage/GcpCloudStorageForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/connection/mongodb/MongoDBForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/connection/mssql/MssqlForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/connection/mysql/MysqlForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/connection/postgres/PostgresForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/aigenerate/single/schema/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/generate/single/schema/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/schema/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/subset/page.tsx
  frontend/apps/web/app/BaseLayout.tsx
  frontend/apps/web/app/globals.css
  frontend/apps/web/components/SupportDrawer.tsx
  frontend/apps/web/components/onboarding-checklist/Configure.tsx
  frontend/apps/web/components/onboarding-checklist/Connect.tsx
  frontend/apps/web/components/onboarding-checklist/ConnectDarkMode.tsx
  frontend/apps/web/components/onboarding-checklist/ConnectLightMode.tsx
  frontend/apps/web/components/onboarding-checklist/OnboardingChecklist.tsx
  frontend/apps/web/components/onboarding-checklist/StepProgress.tsx
  frontend/apps/web/components/onboarding-checklist/Sync.tsx
  frontend/apps/web/components/onboarding-checklist/WelcomeDialog.tsx
  frontend/apps/web/components/onboarding-checklist/WelcomeOverview.tsx
  frontend/apps/web/components/onboarding-checklist/WelcomeRouter.tsx
  frontend/apps/web/components/site-header/AccountsRecordProgress.tsx
  frontend/apps/web/components/site-header/RecordsProgressBar.tsx
  frontend/apps/web/components/site-header/SiteHeader.tsx
  frontend/apps/web/public/icons/AwsS3Icon.tsx
  frontend/apps/web/public/icons/DynamoDB.tsx
  frontend/apps/web/public/icons/Mysql.tsx
  frontend/apps/web/public/icons/NeonGrayScale.tsx
  frontend/apps/web/public/images/job-med.png
  frontend/apps/web/public/images/jobs-dark.png
  frontend/apps/web/public/images/obsub.png
  frontend/apps/web/public/images/ss-dark.png
  frontend/packages/sdk/src/client/mgmt/v1alpha1/user_account_pb.ts
Labels: enhancement

#2764 adds action to generate repo stats
  .github/workflows/repostats.yml
Labels: ignore-for-release

#2765 delete images from onboarding pr
  frontend/apps/web/public/images/job-med.png
  frontend/apps/web/public/images/jobs-dark.png
  frontend/apps/web/public/images/obsub.png
  frontend/apps/web/public/images/ss-dark.png
Labels: Improvement, ignore-for-release

#2743 NEOS-1484 Reset SQL column defaults after sync
  backend/pkg/sqlmanager/mock_SqlDatabase.go
  backend/pkg/sqlmanager/mssql/mssql-manager.go
  backend/pkg/sqlmanager/mysql/mysql-manager.go
  backend/pkg/sqlmanager/postgres/postgres-manager.go
  backend/pkg/sqlmanager/postgres/postgres-manager_test.go
  backend/pkg/sqlmanager/sql-manager.go
  backend/services/mgmt/v1alpha1/connection-data-service/connection-data_test.go
  worker/internal/cmds/worker/serve/serve.go
  worker/pkg/benthos/sql/output_sql_insert.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/benthos-builder.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/benthos-builder_test.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/sync.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/sync_test.go
  worker/pkg/workflows/datasync/activities/post-table-sync/activity.go
  worker/pkg/workflows/datasync/activities/post-table-sync/activity_test.go
  worker/pkg/workflows/datasync/activities/run-sql-init-table-stmts/init-statement-builder.go
  worker/pkg/workflows/datasync/activities/run-sql-init-table-stmts/init-statement-builder_test.go
  worker/pkg/workflows/datasync/activities/shared/shared.go
  worker/pkg/workflows/datasync/workflow/integration_test.go
  worker/pkg/workflows/datasync/workflow/workflow.go
Labels: bug

#2768 Use goqu to build postgres truncate statement
  backend/pkg/sqlmanager/mssql/mssql-manager.go
  backend/pkg/sqlmanager/mssql/mssql-manager_test.go
  backend/pkg/sqlmanager/postgres/postgres-manager.go
  backend/pkg/sqlmanager/postgres/postgres-manager_test.go
  backend/pkg/sqlmanager/sql-manager.go
  backend/pkg/table-dependency/table-dependency.go
  backend/pkg/table-dependency/table-dependency_test.go
  cli/internal/cmds/neosync/sync/sync.go
  worker/pkg/workflows/datasync/activities/run-sql-init-table-stmts/init-statement-builder.go
  worker/pkg/workflows/datasync/activities/run-sql-init-table-stmts/init-statement-builder_test.go
Labels: Tech Debt

#2766 NEOS-14978: add check to skip setting transformer in apply default transformer if…
  frontend/apps/web/components/ConfirmationDialog.tsx
  frontend/apps/web/components/jobs/SchemaTable/SchemaTableToolBar.tsx
  frontend/apps/web/components/switches/SwitchCard.tsx
  frontend/apps/web/components/ui/alert.tsx
  frontend/apps/web/yup-validations/jobs.ts
Labels: enhancement

#2770 Updates Records Used Link to route to correct place
  frontend/apps/web/components/site-header/RecordsProgressBar.tsx
  frontend/apps/web/components/site-header/SiteHeader.tsx
Labels: bug

#2779 Fix post table sync activity error: run context not found
  worker/pkg/workflows/datasync/activities/post-table-sync/activity.go
  worker/pkg/workflows/datasync/activities/post-table-sync/activity_test.go
Labels: bug

#2780 NEOS-1505:Update job selection
  frontend/apps/web/app/(mgmt)/[account]/new/job/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/runs/[id]/page.tsx
  frontend/apps/web/public/images/aigen-dark.svg
  frontend/apps/web/public/images/aigen.svg
  frontend/apps/web/public/images/datagen-dark.svg
  frontend/apps/web/public/images/gen-light.svg
  frontend/apps/web/public/images/jobsynclight.svg
  frontend/apps/web/public/images/prodsync-dark.svg
Labels: enhancement

#2781 Mysql exclude default_generated from generated field to allow javascript transformer
  backend/pkg/sqlmanager/mysql/mysql-manager.go
Labels: bug

#2708 Reworks SSH Tunneling For SQL Databases
  .mockery.yml
  backend/gen/go/db/dbschemas/postgresql/db.go
  backend/gen/go/db/dbschemas/postgresql/mock_DBTX.go
  backend/gen/go/db/dbschemas/postgresql/system.sql.go
  backend/internal/auth/jwt/mock_JwtValidator.go
  backend/internal/neosyncdb/mock_DBTX.go
  backend/pkg/dbconnect-config/dbconnect-config.go
  backend/pkg/dbconnect-config/dbconnect-config_test.go
  backend/pkg/mongoconnect/connector.go
  backend/pkg/sqlconnect/mock_PgPoolContainer.go
  backend/pkg/sqlconnect/mock_SqlConnector.go
  backend/pkg/sqlconnect/pgpool.go
  backend/pkg/sqlconnect/sql-connector.go
  backend/pkg/sqlconnect/sql-connector_test.go
  backend/pkg/sqlconnect/sqldb.go
  backend/pkg/sqlmanager/mssql/integration_test.go
  backend/pkg/sqlmanager/mssql/mssql-manager_integration_test.go
  backend/pkg/sqlmanager/mysql/mysql-manager_integration_test.go
  backend/pkg/sqlmanager/mysql_sql-manager_integration_test.go
  backend/pkg/sqlmanager/postgres/integration_test.go
  backend/pkg/sqlmanager/postgres/postgres-manager.go
  backend/pkg/sqlmanager/postgres/postgres-manager_integration_test.go
  backend/pkg/sqlmanager/postgres_sql-manager_integration_test.go
  backend/pkg/sqlmanager/sql-manager.go
  backend/pkg/sshtunnel/endpoint.go
  backend/pkg/sshtunnel/endpoint_test.go
  backend/pkg/sshtunnel/tunnel.go
  backend/services/mgmt/v1alpha1/connection-data-service/connection-data.go
  backend/services/mgmt/v1alpha1/connection-data-service/connection-data_test.go
  backend/services/mgmt/v1alpha1/connection-service/connection_test.go
  backend/services/mgmt/v1alpha1/integration_tests/connection-service_integration_test.go
  backend/sqlc.yaml
  cli/internal/cmds/neosync/sync/sync.go
  cli/internal/cmds/neosync/sync/ui.go
  go.mod
  go.sum
  internal/mocks/github.com/jackc/pgx/v5/mock_Tx.go
  internal/sshtunnel/connectors/mssqltunconnector/connector.go
  internal/sshtunnel/connectors/mssqltunconnector/connector_test.go
  internal/sshtunnel/connectors/mysqltunconnector/connector.go
  internal/sshtunnel/connectors/mysqltunconnector/connector_test.go
  internal/sshtunnel/connectors/postgrestunconnector/connector.go
  internal/sshtunnel/connectors/postgrestunconnector/connector_test.go
  internal/sshtunnel/dialer.go
  internal/sshtunnel/dialer_integration_test.go
  internal/sshtunnel/utils.go
  internal/sshtunnel/utils_test.go
  worker/internal/cmds/worker/serve/serve.go
  worker/internal/connection-tunnel-manager/manager.go
  worker/internal/connection-tunnel-manager/manager_test.go
  worker/internal/connection-tunnel-manager/mock_ConnectionProvider.go
  worker/internal/connection-tunnel-manager/providers/mongoprovider/provider.go
  worker/internal/connection-tunnel-manager/providers/provider.go
  worker/internal/connection-tunnel-manager/providers/provider_test.go
  worker/internal/connection-tunnel-manager/providers/sqlprovider/provider.go
  worker/internal/connection-tunnel-manager/providers/sqlprovider/provider_test.go
  worker/pkg/workflows/datasync/activities/sync/activity.go
  worker/pkg/workflows/datasync/activities/sync/activity_test.go
  worker/pkg/workflows/datasync/workflow/workflow_integration_test.go
Labels: Tech Debt

#2785 NEOS-1514: update broken images
  frontend/apps/web/app/(mgmt)/[account]/new/job/page.tsx
  frontend/apps/web/public/images/aigen-dark.svg
  frontend/apps/web/public/images/aigen.svg
  frontend/apps/web/public/images/datagen-dark.svg
  frontend/apps/web/public/images/gen-light.svg
  frontend/apps/web/public/images/jobsynclight.svg
  frontend/apps/web/public/images/prodsync-dark.svg
Labels: bug

#2789 NEOS-1515: remove temporal dependency on s3 sync
  backend/services/mgmt/v1alpha1/connection-data-service/connection-data.go
Labels: enhancement

#2783 NEOS-1333 AnonymizeMany and AnonymizeSingle endpoint
  backend/gen/go/protos/mgmt/v1alpha1/anonymization.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/mgmtv1alpha1connect/anonymization.connect.go
  backend/internal/cmds/mgmt/serve/connect/cmd.go
  backend/protos/mgmt/v1alpha1/anonymization.proto
  backend/services/mgmt/v1alpha1/anonymization-service/anonymization.go
  backend/services/mgmt/v1alpha1/anonymization-service/service.go
  backend/services/mgmt/v1alpha1/integration_tests/anonymization-service_integration_test.go
  backend/services/mgmt/v1alpha1/integration_tests/integration_test.go
  docs/protos/data/proto_docs.json
  frontend/packages/sdk/src/client/client.ts
  frontend/packages/sdk/src/client/index.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/anonymization-AnonymizationService_connectquery.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/anonymization_connect.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/anonymization_pb.ts
  go.mod
  go.sum
  internal/json-anonymizer/json-anonymizer.go
  internal/json-anonymizer/json-anonymizer_test.go
  internal/json-anonymizer/testdata/company.json
  worker/pkg/benthos/transformers/transformer_initializer.go
Labels: Feature

#2791 Anonymize docs
  docs/docs/guides/anonymization-endpoints.md
  docs/protos/mgmt/v1alpha1/anonymization.proto.mdx
  docs/sidebars.ts
Labels: Docs

#2703 Adds timeline view and updates activity table in the runs page
  frontend/apps/web/app/(mgmt)/[account]/runs/[id]/components/JobRunActivityTable.tsx
  frontend/apps/web/app/(mgmt)/[account]/runs/[id]/components/JobRunActivityTable/columns.tsx
  frontend/apps/web/app/(mgmt)/[account]/runs/[id]/components/JobRunActivityTable/data-table-row-actions.tsx
  frontend/apps/web/app/(mgmt)/[account]/runs/[id]/components/JobRunActivityTable/data-table.tsx
  frontend/apps/web/app/(mgmt)/[account]/runs/[id]/page.tsx
  frontend/apps/web/components/RunTImeline/RunTimeline.tsx
Labels: enhancement

#2792 NEOS-1517: adds advanced s3 destination options to job configuration
  backend/gen/go/protos/mgmt/v1alpha1/job.pb.go
  backend/protos/mgmt/v1alpha1/job.proto
  backend/sql/postgresql/models/models.go
  docs/protos/data/proto_docs.json
  frontend/apps/web/app/(mgmt)/[account]/connections/[id]/components/AwsS3Form.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/destinations/components/DestinationConnectionCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/util.ts
  frontend/apps/web/app/(mgmt)/[account]/new/job/[id]/destination/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/aigenerate/single/connect/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/connect/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/generate/single/connect/page.tsx
  frontend/apps/web/components/jobs/Form/AwsS3DestinationOptionsForm.tsx
  frontend/apps/web/components/jobs/Form/DestinationOptionsForm.tsx
  frontend/apps/web/libs/util.test.ts
  frontend/apps/web/util/duration.test.ts
  frontend/apps/web/util/duration.ts
  frontend/apps/web/util/util.ts
  frontend/apps/web/yup-validations/jobs.ts
  frontend/apps/web/yup-validations/number.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/job_pb.ts
  worker/pkg/benthos/config.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/benthos-builder.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/sync.go
Labels: enhancement

#2793 Adds 9-26 Public Changelog
  docs/blog/2024-10-10-cli-sync.md
Labels: documentation

#2784 NEOS-1513: Update upgrade and warning prompts
  backend/gen/go/protos/mgmt/v1alpha1/user_account.pb.go
  backend/protos/mgmt/v1alpha1/user_account.proto
  backend/services/mgmt/v1alpha1/integration_tests/user-account-service_integration_test.go
  backend/services/mgmt/v1alpha1/user-account-service/billing.go
  docs/protos/data/proto_docs.json
  frontend/apps/web/components/site-header/AccountStatusHandler.tsx
  frontend/apps/web/components/site-header/AccountsRecordProgress.tsx
  frontend/apps/web/components/site-header/RecordsProgressBar.tsx
  frontend/apps/web/components/site-header/SiteHeader.tsx
  frontend/apps/web/components/site-header/Upgrade.tsx
  frontend/apps/web/components/site-header/UpgradeButton.tsx
  frontend/apps/web/components/site-header/UserNav.tsx
  frontend/packages/sdk/src/client/mgmt/v1alpha1/user_account_pb.ts
Labels: Improvement

#2795 NEOS-1516: updates to not show any connect errors for unsupported connections
  backend/services/mgmt/v1alpha1/connection-service/connection.go
  frontend/apps/web/app/(mgmt)/[account]/new/job/connect/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/generate/single/connect/page.tsx
  frontend/apps/web/components/connections/TestConnectionBadge.tsx
Labels: bug

#2774 fix(mysql): correct default value handling for VARCHAR columns in Ini…
  backend/pkg/sqlmanager/mysql/mysql-manager.go
  backend/pkg/sqlmanager/shared/types.go
Labels: bug

#2804 Fix transform email in anonymize endpoint
  worker/pkg/benthos/transformers/transform_email.go
  worker/pkg/benthos/transformers/transformer_initializer.go
Labels: bug

#2798 Add JQ optional operator to anonymize service docs
  docs/docs/guides/anonymization-endpoints.md
Labels: Docs

#2806 NEOS-1532 Fix transform int64 phone number
  worker/pkg/benthos/transformers/transform_int64_phone_number.go
  worker/pkg/benthos/transformers/transform_int64_phone_number_test.go
Labels: bug

#2805 NEOS-1525: adds new pii text transformer to anonymize service
  .mockery.yml
  LICENSE.md
  backend/buf.gen.yaml
  backend/gen/go/protos/mgmt/v1alpha1/anonymization.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/api_key.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/auth.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/connection.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/connection_data.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/job.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/metrics.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/transformer.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/user_account.pb.go
  backend/internal/cmds/mgmt/serve/connect/cmd.go
  backend/protos/mgmt/v1alpha1/transformer.proto
  backend/services/mgmt/v1alpha1/anonymization-service/anonymization.go
  backend/services/mgmt/v1alpha1/anonymization-service/service.go
  backend/services/mgmt/v1alpha1/integration_tests/integration_test.go
  backend/services/mgmt/v1alpha1/transformers-service/system_transformers.go
  cli/internal/auth/tokens.go
  docs/protos/data/proto_docs.json
  frontend/apps/web/yup-validations/transformer-validations.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/transformer_pb.ts
  go.mod
  go.sum
  internal/ee/LICENSE.md
  internal/ee/presidio/client.gen.go
  internal/ee/presidio/config/api.yml
  internal/ee/presidio/config/clientconfig.yml
  internal/ee/presidio/generate.go
  internal/ee/presidio/interface.go
  internal/ee/presidio/mock_AnalyzeInterface.go
  internal/ee/presidio/mock_AnonymizeInterface.go
  internal/ee/presidio/util.go
  internal/ee/transformers/functions/functions.go
  internal/ee/transformers/functions/functions_test.go
  internal/ee/transformers/transformers.go
  internal/json-anonymizer/json-anonymizer.go
  internal/json-anonymizer/json-anonymizer_test.go
  tools.go
  worker/pkg/benthos/environment/bloblang.go
  worker/pkg/benthos/environment/environment.go
  worker/pkg/benthos/transformers/transformer_initializer.go
  worker/pkg/http/client/client.go
  worker/pkg/http/client/client_test.go
  worker/pkg/workflows/datasync/activities/shared/shared.go
  worker/pkg/workflows/datasync/activities/sync/activity.go
Labels: enhancement

#2800 Add Github Action for testing the frontend
  .github/workflows/frontend.yml
Labels: Tech Debt

#2807 NEOS-1531 Fix initialize full name transformer
  worker/pkg/benthos/transformers/transformer_initializer.go
Labels: bug

#2810 Fix connection data stream AWS S3 get latest job run
  backend/services/mgmt/v1alpha1/connection-data-service/connection-data.go
  cli/internal/cmds/neosync/sync/sync.go
Labels: bug

#2812 NEOS-1539: add support for deny list in anonymizer
  .github/workflows/frontend.yml
  backend/gen/go/protos/mgmt/v1alpha1/transformer.pb.go
  backend/protos/mgmt/v1alpha1/transformer.proto
  docs/protos/data/proto_docs.json
  frontend/packages/sdk/package.json
  frontend/packages/sdk/src/client/mgmt/v1alpha1/transformer_pb.ts
  frontend/turbo.json
  internal/ee/transformers/functions/functions.go
  internal/ee/transformers/functions/functions_test.go
Labels: enhancement

#2814 NEOS-1546: fix s3 default destination options not saving on job create
  frontend/apps/web/app/(mgmt)/[account]/new/job/connect/page.tsx
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/sync.go
Labels: bug

#2811 Add debug flag to cli sync
  cli/internal/cmds/neosync/sync/sync.go
Labels: Devex

#2797 NEOS-1520 Add meter to anonymization service
  backend/gen/go/protos/mgmt/v1alpha1/anonymization.pb.go
  backend/internal/cmds/mgmt/serve/connect/cmd.go
  backend/pkg/metrics/labels.go
  backend/protos/mgmt/v1alpha1/anonymization.proto
  backend/services/mgmt/v1alpha1/anonymization-service/anonymization.go
  backend/services/mgmt/v1alpha1/anonymization-service/service.go
  backend/services/mgmt/v1alpha1/anonymization-service/user-account.go
  backend/services/mgmt/v1alpha1/integration_tests/anonymization-service_integration_test.go
  backend/services/mgmt/v1alpha1/integration_tests/integration_test.go
  docs/protos/data/proto_docs.json
  frontend/packages/sdk/src/client/mgmt/v1alpha1/anonymization_pb.ts
  internal/json-anonymizer/json-anonymizer.go
Labels: Fast Follow

#2808 NEOS-1545: Update TS API Docs
  docs/protos/go.md
  docs/protos/home.md
  docs/protos/typescript.md
  docs/src/css/overrides.css
Labels: Docs

#2816 NEOS-1548: add in anonymize unstructured data docs
  docs/protos/go.md
  docs/protos/typescript.md
Labels: Docs

#2818 AWS S3 getconnectionschema handle empty table folders
  backend/services/mgmt/v1alpha1/connection-data-service/connection-data.go
Labels: bug

#2825 updated old screenshots
  docs/docs/guides/creating-a-data-gen-job.md
  docs/docs/guides/creating-a-sync-job.md
  docs/docs/transformers/user-defined.md
  docs/static/img/fifth.png
  docs/static/img/first.png
  docs/static/img/fourth.png
  docs/static/img/second.png
  docs/static/img/third.png
Labels: documentation

#2822 Adds gating to AnonymizeMany and TransformPiiText Transformer
  backend/internal/cmds/mgmt/serve/connect/cmd.go
  backend/services/mgmt/v1alpha1/anonymization-service/anonymization.go
  backend/services/mgmt/v1alpha1/anonymization-service/service.go
  backend/services/mgmt/v1alpha1/integration_tests/anonymization-service_integration_test.go
  backend/services/mgmt/v1alpha1/integration_tests/integration_test.go
  backend/services/mgmt/v1alpha1/integration_tests/integration_util_test.go
Labels: Tech Debt

#2799 NOES-1523:adding an expanded modal to the runs timeline
  frontend/apps/web/components/RunTImeline/RunTimeline.tsx
Labels: enhancement

#2827 Adds Python SDK to Buf Gen
  .github/workflows/artifact-release.yml
  .github/workflows/buf.yml
  .github/workflows/sqlc.yaml
  .gitignore
  BUF_VERSION
  SQLC_VERSION
  backend/BUF_VERSION
  backend/Makefile
  backend/buf.lock
  backend/gen/openapi/mgmt/v1alpha1/anonymization.openapi.yaml
  buf.gen.yaml
  buf.lock
  buf.yaml
  docs/docusaurus.config.ts
  docs/protos/proto_docs.json
  python/README.md
  python/pyproject.toml
  python/src/neosync/__init__.py
  python/src/neosync/buf/validate/expression_pb2.py
  python/src/neosync/buf/validate/priv/private_pb2.py
  python/src/neosync/buf/validate/validate_pb2.py
  python/src/neosync/mgmt/v1alpha1/anonymization_pb2.py
  python/src/neosync/mgmt/v1alpha1/anonymization_pb2.pyi
  python/src/neosync/mgmt/v1alpha1/anonymization_pb2_grpc.py
  python/src/neosync/mgmt/v1alpha1/api_key_pb2.py
  python/src/neosync/mgmt/v1alpha1/api_key_pb2.pyi
  python/src/neosync/mgmt/v1alpha1/api_key_pb2_grpc.py
  python/src/neosync/mgmt/v1alpha1/auth_pb2.py
  python/src/neosync/mgmt/v1alpha1/auth_pb2.pyi
  python/src/neosync/mgmt/v1alpha1/auth_pb2_grpc.py
  python/src/neosync/mgmt/v1alpha1/connection_data_pb2.py
  python/src/neosync/mgmt/v1alpha1/connection_data_pb2.pyi
  python/src/neosync/mgmt/v1alpha1/connection_data_pb2_grpc.py
  python/src/neosync/mgmt/v1alpha1/connection_pb2.py
  python/src/neosync/mgmt/v1alpha1/connection_pb2.pyi
  python/src/neosync/mgmt/v1alpha1/connection_pb2_grpc.py
  python/src/neosync/mgmt/v1alpha1/job_pb2.py
  python/src/neosync/mgmt/v1alpha1/job_pb2.pyi
  python/src/neosync/mgmt/v1alpha1/job_pb2_grpc.py
  python/src/neosync/mgmt/v1alpha1/metrics_pb2.py
  python/src/neosync/mgmt/v1alpha1/metrics_pb2.pyi
  python/src/neosync/mgmt/v1alpha1/metrics_pb2_grpc.py
  python/src/neosync/mgmt/v1alpha1/transformer_pb2.py
  python/src/neosync/mgmt/v1alpha1/transformer_pb2.pyi
  python/src/neosync/mgmt/v1alpha1/transformer_pb2_grpc.py
  python/src/neosync/mgmt/v1alpha1/user_account_pb2.py
  python/src/neosync/mgmt/v1alpha1/user_account_pb2.pyi
  python/src/neosync/mgmt/v1alpha1/user_account_pb2_grpc.py
  scripts/backend-gen.sh
  sqlc.yaml
Labels: enhancement

#2832 Adds new EE license module to backend
  .gitignore
  backend/charts/api/README.md
  backend/charts/api/templates/api-env-vars.yaml
  backend/charts/api/values.yaml
  backend/internal/cmds/mgmt/serve/connect/cmd.go
  charts/neosync/README.md
  docs/docs/deploy/environment-variables.md
  internal/ee/license/license.go
  internal/ee/license/license_test.go
  internal/ee/license/neosync_ee_pub.pem
  scripts/gen-cust-license.sh
  scripts/gen-license.md
Labels: enhancement

#2834 Fixes Python SDK CI Job Incorrect Paths
  .github/workflows/artifact-release.yml
Labels: bug, ignore-for-release

#2835 Add benthos standard log with table and runtype keyvals to CLI sync
  cli/internal/cmds/neosync/sync/sync.go
  cli/internal/cmds/neosync/sync/ui.go
Labels: enhancement, Devex

#2836 NEOS-1560: expose entities in api for transformpiitext
  .mockery.yml
  backend/gen/go/protos/mgmt/v1alpha1/mgmtv1alpha1connect/mock_TransformersServiceClient.go
  backend/gen/go/protos/mgmt/v1alpha1/mgmtv1alpha1connect/transformer.connect.go
  backend/gen/go/protos/mgmt/v1alpha1/transformer.pb.go
  backend/gen/openapi/mgmt/v1alpha1/anonymization.openapi.yaml
  backend/gen/openapi/mgmt/v1alpha1/job.openapi.yaml
  backend/gen/openapi/mgmt/v1alpha1/transformer.openapi.yaml
  backend/internal/cmds/mgmt/serve/connect/cmd.go
  backend/protos/mgmt/v1alpha1/transformer.proto
  backend/services/mgmt/v1alpha1/integration_tests/integration_test.go
  backend/services/mgmt/v1alpha1/integration_tests/transformers-service_integration_test.go
  backend/services/mgmt/v1alpha1/transformers-service/entities.go
  backend/services/mgmt/v1alpha1/transformers-service/service.go
  backend/services/mgmt/v1alpha1/transformers-service/system_transformers.go
  backend/services/mgmt/v1alpha1/transformers-service/userdefined_transformers.go
  docs/protos/proto_docs.json
  frontend/packages/sdk/src/client/mgmt/v1alpha1/transformer-TransformersService_connectquery.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/transformer_connect.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/transformer_pb.ts
  internal/ee/presidio/interface.go
  internal/ee/presidio/mock_EntityInterface.go
  internal/ee/presidio/mock_RecognizerInterface.go
  internal/ee/transformers/functions/functions.go
  python/src/neosync/mgmt/v1alpha1/transformer_pb2.py
  python/src/neosync/mgmt/v1alpha1/transformer_pb2.pyi
  python/src/neosync/mgmt/v1alpha1/transformer_pb2_grpc.py
Labels: enhancement

#2837 NEOS-1561: updates logic to use presidio defined default if no user provided value
  internal/ee/transformers/functions/functions.go
  internal/ee/transformers/functions/functions_test.go
Labels: enhancement, Fast Follow

#2841 NEOS-1563: Add python sdk docs
  docs/proto-sidebars.ts
  docs/protos/proto-sidebars.js
  docs/protos/python.md
  docs/src/CustomComponents/IconHandler.tsx
Labels: Docs

#2840 Use json decoder instead of scanner when reading from document storage
  backend/internal/gcp/client.go
  backend/services/mgmt/v1alpha1/connection-data-service/connection-data.go
  backend/services/mgmt/v1alpha1/integration_tests/transformers-service_integration_test.go
Labels: bug

#2838 NEOS-1540: add support for allow list in anonymizer
  backend/gen/go/protos/mgmt/v1alpha1/transformer.pb.go
  backend/gen/openapi/mgmt/v1alpha1/anonymization.openapi.yaml
  backend/gen/openapi/mgmt/v1alpha1/job.openapi.yaml
  backend/gen/openapi/mgmt/v1alpha1/transformer.openapi.yaml
  backend/protos/mgmt/v1alpha1/transformer.proto
  docs/protos/proto_docs.json
  frontend/packages/sdk/src/client/mgmt/v1alpha1/transformer_pb.ts
  internal/ee/transformers/functions/functions.go
  internal/ee/transformers/functions/functions_test.go
  python/src/neosync/mgmt/v1alpha1/transformer_pb2.py
  python/src/neosync/mgmt/v1alpha1/transformer_pb2.pyi
Labels: enhancement

#2842 NEOS-1562: convert record limit to time based in account status
  backend/gen/go/db/mock_Querier.go
  backend/gen/go/db/querier.go
  backend/gen/go/db/users.sql.go
  backend/gen/go/protos/mgmt/v1alpha1/user_account.pb.go
  backend/gen/openapi/mgmt/v1alpha1/user_account.openapi.yaml
  backend/internal/cmds/mgmt/serve/connect/cmd.go
  backend/protos/mgmt/v1alpha1/user_account.proto
  backend/services/mgmt/v1alpha1/integration_tests/integration_test.go
  backend/services/mgmt/v1alpha1/integration_tests/integration_util_test.go
  backend/services/mgmt/v1alpha1/integration_tests/user-account-service_integration_test.go
  backend/services/mgmt/v1alpha1/user-account-service/billing.go
  backend/services/mgmt/v1alpha1/user-account-service/billing_test.go
  backend/services/mgmt/v1alpha1/user-account-service/service.go
  backend/sql/postgresql/queries/users.sql
  docs/protos/proto_docs.json
  frontend/apps/web/components/site-header/AccountStatusHandler.tsx
  frontend/apps/web/components/site-header/RecordsProgressBar.tsx
  frontend/apps/web/components/site-header/Upgrade.tsx
  frontend/apps/web/components/ui/progress.tsx
  frontend/apps/web/package.json
  frontend/package-lock.json
  frontend/packages/sdk/src/client/mgmt/v1alpha1/user_account_pb.ts
  python/src/neosync/mgmt/v1alpha1/user_account_pb2.py
  python/src/neosync/mgmt/v1alpha1/user_account_pb2.pyi
Labels: enhancement

#2844 NEOS-1565: Refactors CLI to share DB Connection Pools
  cli/internal/cmds/neosync/sync/sync.go
  cli/internal/cmds/neosync/sync/sync_test.go
  cli/internal/cmds/neosync/sync/ui.go
  internal/connection-tunnel-manager/manager.go
  internal/connection-tunnel-manager/manager_test.go
  internal/connection-tunnel-manager/mock_ConnectionProvider.go
  internal/connection-tunnel-manager/pool/providers/mongo/mongo-pool-provider.go
  internal/connection-tunnel-manager/pool/providers/sql/sql-pool-provider.go
  internal/connection-tunnel-manager/pool/providers/sql/sql-pool-provider_test.go
  internal/connection-tunnel-manager/providers/mongoprovider/provider.go
  internal/connection-tunnel-manager/providers/provider.go
  internal/connection-tunnel-manager/providers/provider_test.go
  internal/connection-tunnel-manager/providers/sqlprovider/provider.go
  worker/pkg/benthos/mongodb/output.go
  worker/pkg/benthos/sql/output_sql_insert.go
  worker/pkg/benthos/sql/output_sql_update.go
  worker/pkg/workflows/datasync/activities/sync/activity.go
Labels: Tech Debt

#2843 NEOS-1564:update billing page
  frontend/apps/web/app/(mgmt)/[account]/settings/billing/page.tsx
  frontend/apps/web/components/headers/SubPageHeader.tsx
Labels: Improvement

#2850 NEOS-1569:Update 10-24 changelog
  docs/blog/2024-10-10-cli-sync.md
  docs/blog/2024-10-24-anonymization-api.md
  docs/protos/mgmt/v1alpha1/anonymization.proto.mdx
  docs/protos/mgmt/v1alpha1/connection.proto.mdx
  docs/protos/mgmt/v1alpha1/connection_data.proto.mdx
  docs/protos/mgmt/v1alpha1/job.proto.mdx
  docs/protos/mgmt/v1alpha1/transformer.proto.mdx
  docs/protos/mgmt/v1alpha1/user_account.proto.mdx
  docs/protos/proto-sidebars.js
Labels: documentation

#2852 update changelog body
  docs/blog/2024-10-10-cli-sync.md
  docs/blog/2024-10-24-anonymization-api.md
Labels: Docs

#2853 update anonymize endpoint docs
  docs/docs/guides/anonymization-endpoints.md
Labels: documentation

#2854 CLI Sync postgres integration test + refactor
  backend/pkg/integration-test/integration-test-util.go
  backend/pkg/integration-test/integration-test.go
  backend/pkg/sqlmanager/mysql/integration_test.go
  backend/pkg/sqlmanager/mysql/mysql-manager_integration_test.go
  backend/pkg/sqlmanager/mysql_sql-manager_integration_test.go
  backend/pkg/sqlmanager/postgres/integration_test.go
  backend/pkg/sqlmanager/postgres_sql-manager_integration_test.go
  backend/services/mgmt/v1alpha1/integration_tests/anonymization-service_integration_test.go
  backend/services/mgmt/v1alpha1/integration_tests/connection-service_integration_test.go
  backend/services/mgmt/v1alpha1/integration_tests/integration_test.go
  backend/services/mgmt/v1alpha1/integration_tests/integration_util_test.go
  backend/services/mgmt/v1alpha1/integration_tests/jobs-service_integration_test.go
  backend/services/mgmt/v1alpha1/integration_tests/transformers-service_integration_test.go
  backend/services/mgmt/v1alpha1/integration_tests/user-account-service_integration_test.go
  cli/internal/auth/tokens.go
  cli/internal/benthos/config.go
  cli/internal/cmds/neosync/connections/connections_integration_test.go
  cli/internal/cmds/neosync/connections/list.go
  cli/internal/cmds/neosync/neosync.go
  cli/internal/cmds/neosync/sync/config.go
  cli/internal/cmds/neosync/sync/dynamodb.go
  cli/internal/cmds/neosync/sync/sync.go
  cli/internal/cmds/neosync/sync/sync_integration_test.go
  cli/internal/cmds/neosync/sync/ui.go
  cli/internal/cmds/neosync/sync/util.go
  internal/testutil/testcontainers/mysql/mysql.go
  internal/testutil/testcontainers/postgres/postgres.go
  internal/testutil/testdata/postgres/alltypes/create-schema.sql
  internal/testutil/testdata/postgres/alltypes/create-tables.sql
  internal/testutil/testdata/postgres/alltypes/teardown.sql
  internal/testutil/testdata/postgres/humanresources/create-schema.sql
  internal/testutil/testdata/postgres/humanresources/create-tables.sql
  internal/testutil/testdata/postgres/humanresources/teardown.sql
  internal/testutil/utils.go
  worker/pkg/benthos/config.go
  worker/pkg/benthos/environment/environment.go
  worker/pkg/benthos/neosync_connection_data/neosync_connection_data_input.go
  worker/pkg/workflows/datasync/workflow/integration_test.go
  worker/pkg/workflows/datasync/workflow/testdata/javascript-transformers/tests.go
  worker/pkg/workflows/datasync/workflow/testdata/mysql/all-types/tests.go
  worker/pkg/workflows/datasync/workflow/testdata/mysql/composite-keys/tests.go
  worker/pkg/workflows/datasync/workflow/testdata/mysql/init-schema/tests.go
  worker/pkg/workflows/datasync/workflow/testdata/mysql/multiple-dbs/tests.go
  worker/pkg/workflows/datasync/workflow/testdata/postgres/all-types/tests.go
  worker/pkg/workflows/datasync/workflow/testdata/postgres/circular-dependencies/tests.go
  worker/pkg/workflows/datasync/workflow/testdata/postgres/double-reference/tests.go
  worker/pkg/workflows/datasync/workflow/testdata/postgres/subsetting/tests.go
  worker/pkg/workflows/datasync/workflow/testdata/postgres/virtual-foreign-keys/tests.go
  worker/pkg/workflows/datasync/workflow/testdata/primary-key-transformer/tests.go
  worker/pkg/workflows/datasync/workflow/testdata/skip-fk-violations/tests.go
  worker/pkg/workflows/datasync/workflow/workflow_integration_test.go
Labels: Devex, Tech Debt

#2856 Moves openapi specs to docs folder, adds combined spec file
  backend/scripts/gen.sh
  buf.gen.yaml
  docs/.prettierignore
  docs/openapi-merge.json
  docs/openapi/mgmt/v1alpha1/anonymization.openapi.yaml
  docs/openapi/mgmt/v1alpha1/api_key.openapi.yaml
  docs/openapi/mgmt/v1alpha1/auth.openapi.yaml
  docs/openapi/mgmt/v1alpha1/connection.openapi.yaml
  docs/openapi/mgmt/v1alpha1/connection_data.openapi.yaml
  docs/openapi/mgmt/v1alpha1/job.openapi.yaml
  docs/openapi/mgmt/v1alpha1/metrics.openapi.yaml
  docs/openapi/mgmt/v1alpha1/transformer.openapi.yaml
  docs/openapi/mgmt/v1alpha1/user_account.openapi.yaml
  docs/openapi/neosync.mgmt.v1alpha1.json
  docs/package-lock.json
  docs/package.json
  scripts/backend-gen.sh
Labels: documentation

#2860 Generates Combined Openapi spec with redocly
  docs/openapi-merge.json
  docs/openapi/neosync.mgmt.v1alpha1.json
  docs/openapi/neosync.mgmt.v1alpha1.yaml
  docs/package-lock.json
  docs/package.json
Labels: documentation

#2859 NEOS-1567: fixes nil pointer error in cli sync
  cli/internal/cmds/neosync/sync/sync.go
Labels: bug

#2861 adds openapi template to add version
  buf.gen.yaml
  docs/openapi/mgmt/v1alpha1/anonymization.openapi.yaml
  docs/openapi/mgmt/v1alpha1/api_key.openapi.yaml
  docs/openapi/mgmt/v1alpha1/auth.openapi.yaml
  docs/openapi/mgmt/v1alpha1/connection.openapi.yaml
  docs/openapi/mgmt/v1alpha1/connection_data.openapi.yaml
  docs/openapi/mgmt/v1alpha1/job.openapi.yaml
  docs/openapi/mgmt/v1alpha1/metrics.openapi.yaml
  docs/openapi/mgmt/v1alpha1/transformer.openapi.yaml
  docs/openapi/mgmt/v1alpha1/user_account.openapi.yaml
  docs/openapi/neosync.mgmt.v1alpha1.yaml
  neosync.openapi.template.yaml
  scripts/backend-gen.sh
Labels: documentation

#2858 Add CLI sync mysql integration test
  backend/internal/neosyncdb/integration_test.go
  backend/pkg/integration-test/integration-test-util.go
  backend/pkg/sqlmanager/mssql/integration_test.go
  backend/pkg/sqlmanager/mssql_sql-manager_integration_test.go
  backend/pkg/sqlmanager/mysql/integration_test.go
  backend/pkg/sqlmanager/mysql_sql-manager_integration_test.go
  backend/pkg/sqlmanager/postgres/integration_test.go
  backend/pkg/sqlmanager/postgres_sql-manager_integration_test.go
  backend/services/mgmt/v1alpha1/integration_tests/integration_test.go
  cli/internal/cmds/neosync/sync/sync_integration_test.go
  internal/sshtunnel/dialer_integration_test.go
  internal/testutil/testdata/mysql/humanresources/create-schema.sql
  internal/testutil/testdata/mysql/humanresources/create-tables.sql
  internal/testutil/testdata/mysql/humanresources/teardown.sql
  worker/pkg/query-builder2/integration_test.go
  worker/pkg/query-builder2/query-builder_integration_test.go
  worker/pkg/workflows/datasync/workflow/integration_test.go
Labels: Devex, Tech Debt

#2862 Update postman link
  docs/docusaurus.config.ts
Labels: documentation

#2867 NEOS-1559: add ability to limit db connections via cli
  Makefile
  backend/gen/go/protos/mgmt/v1alpha1/connection.pb.go
  backend/pkg/sqlconnect/sql-connector.go
  backend/protos/mgmt/v1alpha1/connection.proto
  backend/sql/postgresql/models/models.go
  cli/internal/cmds/neosync/sync/config.go
  cli/internal/cmds/neosync/sync/sync.go
  docs/docs/cli/sync.md
  docs/openapi/mgmt/v1alpha1/connection.openapi.yaml
  docs/openapi/neosync.mgmt.v1alpha1.yaml
  docs/protos/mgmt/v1alpha1/connection.proto.mdx
  docs/protos/proto_docs.json
  frontend/packages/sdk/src/client/mgmt/v1alpha1/connection_pb.ts
  python/src/neosync/mgmt/v1alpha1/connection_pb2.py
  python/src/neosync/mgmt/v1alpha1/connection_pb2.pyi
Labels: enhancement

#2865 Fixes malformed struct tag in TransformFullName DB Model
  backend/sql/postgresql/models/transformers.go
Labels: bug

#2869 Deprecates Source in JobMappingTransformer config
  backend/gen/go/db/models.go
  backend/gen/go/db/transformers.sql.go
  backend/gen/go/protos/mgmt/v1alpha1/job.pb.go
  backend/protos/mgmt/v1alpha1/job.proto
  backend/services/mgmt/v1alpha1/job-service/jobs_test.go
  backend/services/mgmt/v1alpha1/transformers-service/userdefined_transformers.go
  backend/sql/postgresql/models/models.go
  backend/sql/postgresql/models/transformers.go
  docs/openapi/mgmt/v1alpha1/job.openapi.yaml
  docs/openapi/neosync.mgmt.v1alpha1.yaml
  docs/protos/mgmt/v1alpha1/job.proto.mdx
  docs/protos/proto_docs.json
  frontend/apps/web/app/(mgmt)/[account]/jobs/util.ts
  frontend/apps/web/components/jobs/SchemaTable/RowAlert.tsx
  frontend/apps/web/components/jobs/SchemaTable/SchemaColumns.tsx
  frontend/apps/web/components/jobs/SchemaTable/SchemaTableToolBar.tsx
  frontend/apps/web/components/jobs/SchemaTable/TransformerSelect.tsx
  frontend/apps/web/components/jobs/SchemaTable/schema-constraint-handler.ts
  frontend/apps/web/components/jobs/SchemaTable/transformer-handler.ts
  frontend/apps/web/util/util.ts
  frontend/apps/web/yup-validations/jobs.test.ts
  frontend/apps/web/yup-validations/jobs.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/job_pb.ts
  sqlc.yaml
  worker/pkg/benthos/default_transform/processor.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/benthos-builder_test.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/processors.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/processors_test.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/sync.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/sync_test.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/utils.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/utils_test.go
  worker/pkg/workflows/datasync/activities/run-sql-init-table-stmts/init-statement-builder_test.go
  worker/pkg/workflows/datasync/workflow/workflow_integration_test.go
Labels: Tech Debt

#2877 NEOS-1582: Adds support for importing, exporting of job mappings
  compose.dev.yml
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/DataGenConnectionCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/DataSyncConnectionCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/useOnImportMappings.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/generate/single/schema/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/schema/page.tsx
  frontend/apps/web/components/FileUpload/FileUpload.tsx
  frontend/apps/web/components/connections/TestConnectionBadge.tsx
  frontend/apps/web/components/jobs/NosqlTable/NosqlTable.tsx
  frontend/apps/web/components/jobs/SchemaTable/ApplyDefaultTransformersButton.tsx
  frontend/apps/web/components/jobs/SchemaTable/ExportJobMappingsButton.tsx
  frontend/apps/web/components/jobs/SchemaTable/ImportJobMappingsButton.tsx
  frontend/apps/web/components/jobs/SchemaTable/SchemaColumns.tsx
  frontend/apps/web/components/jobs/SchemaTable/SchemaPageTable.tsx
  frontend/apps/web/components/jobs/SchemaTable/SchemaTable.tsx
  frontend/apps/web/components/jobs/SchemaTable/SchemaTableToolBar.tsx
  frontend/apps/web/components/jobs/SchemaTable/useOnExportMappings.tsx
  frontend/apps/web/components/useJsonFileDownload.tsx
  frontend/apps/web/package.json
  frontend/package-lock.json
Labels: enhancement

#2871 NEOS-1579: add free trial timer to header
  backend/gen/go/protos/mgmt/v1alpha1/user_account.pb.go
  backend/protos/mgmt/v1alpha1/user_account.proto
  backend/services/mgmt/v1alpha1/user-account-service/billing.go
  docs/openapi/mgmt/v1alpha1/user_account.openapi.yaml
  docs/protos/mgmt/v1alpha1/user_account.proto.mdx
  docs/protos/proto_docs.json
  frontend/apps/web/components/site-header/AccountStatusHandler.tsx
  frontend/packages/sdk/src/client/mgmt/v1alpha1/user_account_pb.ts
  python/src/neosync/mgmt/v1alpha1/user_account_pb2.py
  python/src/neosync/mgmt/v1alpha1/user_account_pb2.pyi
Labels: enhancement

#2886 NEOS-1592:add dark mode stylings to upload component
  frontend/apps/web/components/FileUpload/FileUpload.tsx
Labels: Fast Follow

#2882 Updates CLI and Worker to used shared benthos builder
  backend/pkg/sqlmanager/sql-manager.go
  cli/internal/cmds/neosync/sync/config.go
  cli/internal/cmds/neosync/sync/dynamodb.go
  cli/internal/cmds/neosync/sync/job.go
  cli/internal/cmds/neosync/sync/sync.go
  cli/internal/cmds/neosync/sync/sync_integration_test.go
  cli/internal/cmds/neosync/sync/sync_test.go
  cli/internal/cmds/neosync/sync/ui.go
  cli/internal/cmds/neosync/sync/util.go
  go.mod
  internal/benthos/benthos-builder/benthos-builder.go
  internal/benthos/benthos-builder/builders/aws-s3.go
  internal/benthos/benthos-builder/builders/benthos-builder_test.go
  internal/benthos/benthos-builder/builders/dynamodb.go
  internal/benthos/benthos-builder/builders/dynamodb_test.go
  internal/benthos/benthos-builder/builders/gcp-cloud-storage.go
  internal/benthos/benthos-builder/builders/generate-ai.go
  internal/benthos/benthos-builder/builders/generate.go
  internal/benthos/benthos-builder/builders/mongodb.go
  internal/benthos/benthos-builder/builders/neosync-connection-data.go
  internal/benthos/benthos-builder/builders/processors.go
  internal/benthos/benthos-builder/builders/processors_test.go
  internal/benthos/benthos-builder/builders/sql-util.go
  internal/benthos/benthos-builder/builders/sql.go
  internal/benthos/benthos-builder/builders/sql_test.go
  internal/benthos/benthos-builder/generate-benthos.go
  internal/benthos/benthos-builder/internal/types.go
  internal/benthos/benthos-builder/shared/types.go
  internal/testutil/testcontainers/redis/redis.go
  internal/testutil/testdata/mysql/humanresources/create-tables.sql
  internal/testutil/testdata/postgres/humanresources/create-tables.sql
  worker/pkg/benthos/config.go
  worker/pkg/benthos/neosync_connection_data/neosync_connection_data_input.go
  worker/pkg/benthos/sql/output_sql_insert.go
  worker/pkg/query-builder2/wrapper.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/activity.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/benthos-builder.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/benthos-builder_test.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/sync.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/utils.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/utils_test.go
  worker/pkg/workflows/datasync/activities/sync/activity.go
  worker/pkg/workflows/datasync/workflow/workflow.go
  worker/pkg/workflows/datasync/workflow/workflow_test.go
Labels: enhancement, Devex, Tech Debt

#2883 NEOS-1585: Adds deadlock retry support to SQL outputs
  worker/pkg/benthos/config.go
  worker/pkg/benthos/sql/deadlock.go
  worker/pkg/benthos/sql/deadlock_test.go
  worker/pkg/benthos/sql/output_sql_insert.go
  worker/pkg/benthos/sql/output_sql_update.go
  worker/pkg/benthos/sql/retry.go
  worker/pkg/benthos/sql/retry_test.go
Labels: enhancement

#2885 NEOS-1587: Exposes MaxInFlight, BatchConfig for SQL Destinations
  backend/gen/go/protos/mgmt/v1alpha1/job.pb.go
  backend/protos/mgmt/v1alpha1/job.proto
  backend/sql/postgresql/models/models.go
  docs/openapi/mgmt/v1alpha1/job.openapi.yaml
  docs/openapi/neosync.mgmt.v1alpha1.yaml
  docs/protos/mgmt/v1alpha1/job.proto.mdx
  docs/protos/proto_docs.json
  frontend/packages/sdk/src/client/mgmt/v1alpha1/job_pb.ts
  internal/benthos/benthos-builder/builders/aws-s3.go
  internal/benthos/benthos-builder/builders/generate-ai.go
  internal/benthos/benthos-builder/builders/generate.go
  internal/benthos/benthos-builder/builders/sql-util.go
  internal/benthos/benthos-builder/builders/sql.go
  python/src/neosync/mgmt/v1alpha1/job_pb2.py
  python/src/neosync/mgmt/v1alpha1/job_pb2.pyi
  worker/pkg/benthos/config.go
Labels: enhancement

#2888 NEOS-1591: expose batching config sql options in cli
  cli/internal/cmds/neosync/sync/config.go
  cli/internal/cmds/neosync/sync/sync.go
  docs/docs/cli/sync.md
Labels: enhancement

#2891 Consolidates Database Schema Row Structs
  .mockery.yml
  backend/pkg/sqlmanager/mock_SqlDatabase.go
  backend/pkg/sqlmanager/mssql/mssql-manager.go
  backend/pkg/sqlmanager/mssql/mssql-manager_integration_test.go
  backend/pkg/sqlmanager/mysql/mysql-manager.go
  backend/pkg/sqlmanager/postgres/postgres-manager.go
  backend/pkg/sqlmanager/postgres/postgres-manager_integration_test.go
  backend/pkg/sqlmanager/shared/types.go
  backend/pkg/sqlmanager/shared/utils.go
  backend/pkg/sqlmanager/sql-manager.go
  backend/services/mgmt/v1alpha1/connection-data-service/connection-data.go
  backend/services/mgmt/v1alpha1/connection-data-service/connection-data_test.go
  backend/services/mgmt/v1alpha1/job-service/jobs.go
  backend/services/mgmt/v1alpha1/job-service/jobs_test.go
  cli/internal/cmds/neosync/sync/sync.go
  internal/benthos/benthos-builder/builders/benthos-builder_test.go
  internal/benthos/benthos-builder/builders/dynamodb.go
  internal/benthos/benthos-builder/builders/mongodb.go
  internal/benthos/benthos-builder/builders/processors.go
  internal/benthos/benthos-builder/builders/processors_test.go
  internal/benthos/benthos-builder/builders/sql-util.go
  internal/benthos/benthos-builder/builders/sql.go
  internal/benthos/benthos-builder/shared/types.go
  worker/pkg/query-builder2/query-builder_integration_test.go
  worker/pkg/query-builder2/querybuilder.go
  worker/pkg/query-builder2/subset.go
  worker/pkg/query-builder2/wrapper.go
Labels: Tech Debt
