Repository nucleuscloud/neosync, pull requests merged in 2024-12, with the labels that each got.

#3000 Wraps temporal logger in slog.Logger for better system plugin
  backend/internal/connect/interceptors/auth_logging/interceptor_test.go
  backend/internal/connect/interceptors/bookend/interceptor_test.go
  backend/internal/connect/interceptors/logger/interceptor_test.go
  backend/internal/connect/interceptors/logger/logger-ctx_test.go
  backend/internal/neosyncdb/integration_test.go
  backend/pkg/dbconnect-config/mysql_test.go
  backend/pkg/dbconnect-config/postgres_test.go
  backend/pkg/integration-test/integration-test.go
  backend/services/mgmt/v1alpha1/integration_tests/integration_test.go
  go.mod
  go.sum
  internal/benthos/benthos-builder/builders/sql-util_test.go
  internal/testutil/utils.go
  worker/internal/temporal-logger/logger.go
  worker/internal/temporal-logger/logger_test.go
  worker/pkg/benthos/sql/output_sql_insert_test.go
  worker/pkg/workflows/datasync/activities/account-status/activity_test.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/activity.go
  worker/pkg/workflows/datasync/activities/jobhooks-by-timing/activity.go
  worker/pkg/workflows/datasync/activities/jobhooks-by-timing/activity_test.go
  worker/pkg/workflows/datasync/activities/post-table-sync/activity.go
  worker/pkg/workflows/datasync/activities/post-table-sync/activity_test.go
  worker/pkg/workflows/datasync/activities/run-sql-init-table-stmts/activity.go
  worker/pkg/workflows/datasync/activities/sync-activity-opts/activity_test.go
  worker/pkg/workflows/datasync/activities/sync-redis-clean-up/activity.go
  worker/pkg/workflows/datasync/activities/sync/activity.go
  worker/pkg/workflows/datasync/activities/sync/activity_test.go
  worker/pkg/workflows/datasync/workflow/workflow_integration_test.go
Labels: Tech Debt

#3004 Use workflow id in benthos builder and connection manager
  cli/internal/cmds/neosync/sync/sync.go
  internal/benthos/benthos-builder/benthos-builder.go
  internal/benthos/benthos-builder/builders/aws-s3.go
  internal/benthos/benthos-builder/builders/dynamodb.go
  internal/benthos/benthos-builder/builders/gcp-cloud-storage.go
  internal/benthos/benthos-builder/builders/generate-ai.go
  internal/benthos/benthos-builder/builders/generate.go
  internal/benthos/benthos-builder/builders/mongodb.go
  internal/benthos/benthos-builder/builders/sql.go
  internal/benthos/benthos-builder/generate-benthos.go
  internal/benthos/benthos-builder/internal/types.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/benthos-builder.go
  worker/pkg/workflows/datasync/activities/jobhooks-by-timing/activity.go
  worker/pkg/workflows/datasync/activities/post-table-sync/activity.go
  worker/pkg/workflows/datasync/activities/post-table-sync/activity_test.go
  worker/pkg/workflows/datasync/activities/run-sql-init-table-stmts/activity.go
  worker/pkg/workflows/datasync/activities/sync/activity.go
  worker/pkg/workflows/datasync/workflow/workflow_integration_test.go
Labels: bug

#3005 Updates SSHDialer to be more robust to network fluctuations
  backend/pkg/sqlconnect/sql-connector.go
  internal/sshtunnel/connectors/postgrestunconnector/connector.go
  internal/sshtunnel/dialer.go
  internal/sshtunnel/dialer_integration_test.go
  internal/testutil/utils.go
  worker/internal/temporal-logger/logger.go
  worker/pkg/workflows/datasync/activities/account-status/activity_test.go
  worker/pkg/workflows/datasync/activities/jobhooks-by-timing/activity_test.go
  worker/pkg/workflows/datasync/activities/post-table-sync/activity_test.go
  worker/pkg/workflows/datasync/activities/sync-activity-opts/activity_test.go
  worker/pkg/workflows/datasync/activities/sync/activity_test.go
  worker/pkg/workflows/datasync/workflow/workflow_integration_test.go
Labels: enhancement

#3007 Fix postgres statements case sensitivity
  backend/gen/go/db/dbschemas/postgresql/system.sql.go
  backend/pkg/dbschemas/sql/postgresql/queries/system.sql
  backend/pkg/sqlmanager/postgres/postgres-manager.go
  worker/internal/cmds/worker/serve/serve.go
  worker/internal/redis/client.go
  worker/pkg/workflows/datasync/activities/post-table-sync/activity.go
  worker/pkg/workflows/datasync/activities/sync-redis-clean-up/activity.go
  worker/pkg/workflows/datasync/workflow/testdata/postgres/all-types/job_mappings.go
  worker/pkg/workflows/datasync/workflow/testdata/postgres/all-types/schema-create.sql
  worker/pkg/workflows/datasync/workflow/testdata/postgres/all-types/setup.sql
  worker/pkg/workflows/datasync/workflow/testdata/postgres/all-types/teardown.sql
  worker/pkg/workflows/datasync/workflow/workflow.go
  worker/pkg/workflows/datasync/workflow/workflow_integration_test.go
Labels: bug

#3010 Add postgres manager case sensitivity integration tests
  backend/pkg/sqlmanager/postgres/integration_test.go
  backend/pkg/sqlmanager/postgres/postgres-manager_integration_test.go
  backend/pkg/sqlmanager/postgres/testdata/create-schemas.sql
  backend/pkg/sqlmanager/postgres/testdata/setup.sql
Labels: Devex

#3001 CLI sync S3 end to end integration test
  .github/workflows/go.yml
  backend/pkg/integration-test/integration-test-util.go
  backend/pkg/integration-test/integration-test.go
  backend/services/mgmt/v1alpha1/integration_tests/jobs-service_integration_test.go
  cli/internal/cmds/neosync/sync/sync_integration_test.go
  internal/testutil/testcontainers/mysql/mysql.go
  internal/testutil/testcontainers/postgres/postgres.go
  internal/testutil/testdata/gen_jobmappings_config.json
  internal/testutil/testdata/generators.go
  internal/testutil/testdata/jobmapping_generator.go
  internal/testutil/testdata/mysql/alltypes/create-schema.sql
  internal/testutil/testdata/mysql/alltypes/create-tables.sql
  internal/testutil/testdata/mysql/alltypes/job_mappings.go
  internal/testutil/testdata/mysql/alltypes/teardown.sql
  internal/testutil/testdata/mysql/humanresources/create-schema.sql
  internal/testutil/testdata/mysql/humanresources/create-tables.sql
  internal/testutil/testdata/mysql/humanresources/job_mappings.go
  internal/testutil/testdata/mysql/humanresources/teardown.sql
  internal/testutil/testdata/postgres/alltypes/create-schema.sql
  internal/testutil/testdata/postgres/alltypes/create-tables.sql
  internal/testutil/testdata/postgres/alltypes/job_mappings.go
  internal/testutil/testdata/postgres/alltypes/teardown.sql
  internal/testutil/testdata/postgres/humanresources/create-schema.sql
  internal/testutil/testdata/postgres/humanresources/create-tables.sql
  internal/testutil/testdata/postgres/humanresources/job_mappings.go
  internal/testutil/testdata/postgres/humanresources/teardown.sql
  internal/testutil/utils.go
  worker/pkg/integration-test/datasync_workflow.go
  worker/pkg/workflows/datasync/activities/post-table-sync/activity.go
  worker/pkg/workflows/datasync/workflow/workflow_integration_test.go
Labels: Devex, CLI

#3013 Rotates cloud license key
  internal/ee/cloud-license/license_test.go
  internal/ee/cloud-license/neosync_cloud_pub.pem
Labels: ignore-for-release

#3011 NEOS-1654: 12 5changelog
  docs/blog/2024-12-05-job-hooks.md
Labels: documentation

#3014 NEOS-1656: adds empty state for job hooks
  frontend/apps/web/app/(mgmt)/[account]/connections/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/hooks/components/HooksCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/hooks/components/NewHookButton.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/runs/components/RunsTable.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/page.tsx
  frontend/apps/web/components/EmptyState.tsx
Labels: enhancement

#3027 Fix circular dependency subset
  backend/pkg/table-dependency/table-dependency.go
  internal/benthos/benthos-builder/builders/benthos-builder_test.go
  internal/benthos/benthos-builder/builders/dynamodb.go
  internal/benthos/benthos-builder/builders/mongodb.go
  internal/benthos/benthos-builder/builders/processors_test.go
  internal/benthos/benthos-builder/builders/sql.go
  internal/benthos/benthos-builder/shared/types.go
  worker/pkg/query-builder2/query-builder_integration_test.go
  worker/pkg/query-builder2/subset.go
  worker/pkg/query-builder2/wrapper.go
  worker/pkg/workflows/datasync/workflow/testdata/postgres/subsetting/job_mappings.go
  worker/pkg/workflows/datasync/workflow/testdata/postgres/subsetting/setup.sql
  worker/pkg/workflows/datasync/workflow/testdata/postgres/subsetting/tests.go
Labels: bug

#3009 Remove default postgres driver and use PGX everywhere
  backend/pkg/dbconnect-config/postgres.go
  backend/pkg/sqlconnect/sql-connector.go
  backend/pkg/sqlmanager/postgres/postgres-manager.go
  backend/pkg/sqlmanager/shared/types.go
  backend/pkg/sqlmanager/sql-manager.go
  backend/services/mgmt/v1alpha1/connection-data-service/connection-data.go
  cli/internal/cmds/neosync/sync/sync.go
  internal/benthos/benthos-builder/benthos-builder.go
  internal/benthos/benthos-builder/builders/sql-util.go
  internal/benthos/benthos-builder/builders/sql-util_test.go
  worker/pkg/query-builder/insert-query-builder.go
  worker/pkg/query-builder/query-builder.go
Labels: Devex, Tech Debt

#3029 NEOS-1662: update GetJobRunEvents to properly parse metadata
  backend/services/mgmt/v1alpha1/job-service/runs.go
Labels: bug

#3033 NEOS-1663: Fixes transformer configs not updating in job mapping table
  frontend/apps/web/components/jobs/JobMappingTable/Columns.tsx
Labels: bug

#3034 Use left joins in subset queries for nullable foreign keys
  backend/pkg/table-dependency/table-dependency.go
  internal/benthos/benthos-builder/builders/benthos-builder_test.go
  internal/benthos/benthos-builder/builders/sql.go
  internal/benthos/benthos-builder/shared/types.go
  worker/pkg/query-builder2/query-builder_integration_test.go
  worker/pkg/query-builder2/querybuilder.go
  worker/pkg/query-builder2/subset.go
  worker/pkg/query-builder2/testdata/mssql/setup.sql
  worker/pkg/query-builder2/testdata/postgres/setup.sql
  worker/pkg/query-builder2/wrapper.go
  worker/pkg/workflows/datasync/workflow/testdata/postgres/subsetting/job_mappings.go
  worker/pkg/workflows/datasync/workflow/testdata/postgres/subsetting/setup.sql
  worker/pkg/workflows/datasync/workflow/testdata/postgres/subsetting/tests.go
Labels: Improvement

#3023 Mysql and Mssql processors
  internal/benthos/benthos-builder/benthos-builder.go
  internal/benthos/benthos-builder/builders/aws-s3.go
  internal/benthos/benthos-builder/builders/benthos-builder_test.go
  internal/benthos/benthos-builder/builders/generate-ai.go
  internal/benthos/benthos-builder/builders/generate.go
  internal/benthos/benthos-builder/builders/sql-util.go
  internal/benthos/benthos-builder/builders/sql.go
  worker/pkg/benthos/config.go
  worker/pkg/benthos/environment/environment.go
  worker/pkg/benthos/json/processor_neosync_json.go
  worker/pkg/benthos/sql/json_processor.go
  worker/pkg/benthos/sql/json_processor_test.go
  worker/pkg/benthos/sql/output_sql_insert.go
  worker/pkg/benthos/sql/output_sql_update.go
  worker/pkg/benthos/sql/processor_neosync_mssql.go
  worker/pkg/benthos/sql/processor_neosync_mssql_test.go
  worker/pkg/benthos/sql/processor_neosync_mysql.go
  worker/pkg/benthos/sql/processor_neosync_mysql_test.go
  worker/pkg/benthos/sql/processor_neosync_pgx.go
  worker/pkg/benthos/sql/processor_neosync_pgx_test.go
  worker/pkg/query-builder/insert-query-builder.go
  worker/pkg/query-builder/query-builder.go
  worker/pkg/query-builder/query-builder_test.go
  worker/pkg/workflows/datasync/workflow/testdata/mssql/data-types/create-table.sql
  worker/pkg/workflows/datasync/workflow/testdata/mssql/data-types/insert.sql
  worker/pkg/workflows/datasync/workflow/testdata/mssql/data-types/job_mappings.go
  worker/pkg/workflows/datasync/workflow/testdata/mssql/simple/tests.go
  worker/pkg/workflows/datasync/workflow/testdata/mysql/init-schema/tests.go
  worker/pkg/workflows/datasync/workflow/testdata/postgres/all-types/job_mappings.go
  worker/pkg/workflows/datasync/workflow/testdata/postgres/all-types/setup.sql
  worker/pkg/workflows/datasync/workflow/testdata/postgres/all-types/tests.go
Labels: Improvement

#3036 Fix CLI build - remove cgo import
  backend/pkg/sqlmanager/shared/types.go
  internal/benthos/benthos-builder/builders/benthos-builder_test.go
  internal/benthos/benthos-builder/builders/sql.go
  internal/benthos/benthos-builder/shared/types.go
  worker/pkg/query-builder2/subset.go
  worker/pkg/query-builder2/wrapper.go
Labels: bug

#3037 NEOS-1668. NEOS-1670: Align subset table
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/subsets/components/SubsetCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/subset/page.tsx
  frontend/apps/web/components/jobs/subsets/EditItem.tsx
  frontend/apps/web/components/jobs/subsets/subset-table/column.tsx
  frontend/apps/web/components/jobs/subsets/subset-table/data-table.tsx
Labels: Improvement

#3044 NEOS-1672: Fixes worker error shutdown, k8s helm secret revisions
  backend/charts/api/templates/_helpers.tpl
  backend/charts/api/templates/api-env-vars.yaml
  backend/charts/api/templates/db-migrations-env-vars.yaml
  backend/charts/api/templates/deployment.yaml
  backend/internal/cmds/mgmt/mgmt.go
  frontend/apps/web/charts/app/templates/_helpers.tpl
  frontend/apps/web/charts/app/templates/app-env-vars.yaml
  frontend/apps/web/charts/app/templates/deployment.yaml
  internal/connection-manager/manager.go
  worker/charts/worker/templates/_helpers.tpl
  worker/charts/worker/templates/deployment.yaml
  worker/charts/worker/templates/env-vars.yaml
  worker/internal/cmds/worker/serve/serve.go
  worker/internal/cmds/worker/worker.go
Labels: bug

#3042 Fixes postgres and mysql dates / timestamps
  cli/internal/cmds/neosync/sync/sync_integration_test.go
  internal/testutil/testcontainers/mysql/mysql.go
  internal/testutil/testcontainers/postgres/postgres.go
  internal/testutil/testdata/postgres/alltypes/create-tables.sql
  worker/pkg/benthos/json/processor_neosync_json.go
  worker/pkg/benthos/sql/processor_neosync_mysql.go
  worker/pkg/benthos/sql/processor_neosync_pgx.go
  worker/pkg/benthos/sql/processor_neosync_pgx_test.go
Labels: bug, CLI

#3050 Fixes broken end to end test
  cli/internal/cmds/neosync/sync/sync_integration_test.go
  internal/testutil/testdata/postgres/alltypes/create-tables.sql
Labels: bug

#3051 NEOS-1678: minor subset page styling updates
  frontend/apps/web/components/jobs/subsets/EditItem.tsx
  frontend/apps/web/components/jobs/subsets/ValidateQueryBadge.tsx
  frontend/apps/web/components/jobs/subsets/subset-table/column.tsx
Labels: Improvement

#3055 NEOS-1674: [MIGRATION] update invite member workflow to allow specifying user role
  backend/gen/go/db/models.go
  backend/gen/go/db/users.sql.go
  backend/gen/go/protos/mgmt/v1alpha1/user_account.pb.go
  backend/internal/dtomaps/users.go
  backend/internal/ee/rbac/allow_all_client.go
  backend/internal/ee/rbac/policy.go
  backend/internal/ee/rbac/rbac_integration_test.go
  backend/internal/ee/rbac/roles.go
  backend/internal/neosyncdb/integration_test.go
  backend/internal/neosyncdb/users.go
  backend/internal/userdata/entity_enforcer.go
  backend/protos/mgmt/v1alpha1/user_account.proto
  backend/services/mgmt/v1alpha1/user-account-service/users.go
  backend/sql/postgresql/queries/users.sql
  backend/sql/postgresql/schema/20241216205042_add-member-invite-role.down.sql
  backend/sql/postgresql/schema/20241216205042_add-member-invite-role.up.sql
  compose.auth.yml
  docs/openapi/mgmt/v1alpha1/user_account.openapi.yaml
  docs/openapi/neosync.mgmt.v1alpha1.yaml
  docs/protos/mgmt/v1alpha1/user_account.proto.mdx
  docs/protos/proto_docs.json
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/hooks/components/stores.ts
  frontend/apps/web/app/(mgmt)/[account]/settings/members/components/InviteTable.tsx
  frontend/apps/web/app/(mgmt)/[account]/settings/members/components/InviteUserForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/settings/members/components/MemberTable.tsx
  frontend/apps/web/app/(mgmt)/[account]/settings/members/components/SelectAccountRole.tsx
  frontend/apps/web/app/(mgmt)/[account]/settings/members/components/UpdateMemberRoleDialog.tsx
  frontend/apps/web/app/(mgmt)/[account]/settings/members/components/UpdateMemberRoleForm.tsx
  frontend/apps/web/app/api/config/config.ts
  frontend/apps/web/app/config/app-config.ts
  frontend/apps/web/components/jobs/JobMappingTable/Columns.tsx
  frontend/apps/web/components/jobs/JobMappingTable/JobMappingTable.tsx
  frontend/apps/web/util/util.ts
  frontend/apps/web/util/zustand.stores.util.ts
  frontend/apps/web/yup-validations/invite-members.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/user_account_pb.ts
  keycloak/imports/neosync.json
  python/src/neosync/mgmt/v1alpha1/user_account_pb2.py
  python/src/neosync/mgmt/v1alpha1/user_account_pb2.pyi
Labels: bug, enhancement, database-migration

#3057 Fixes API keys not having correct permissions
  backend/internal/userdata/client.go
Labels: bug

#3060 NEOS-1681: update koala for unify
  charts/neosync/README.md
  docs/docs/guides/analytics.md
  docs/docusaurus.config.ts
  frontend/apps/web/app/BaseLayout.tsx
  frontend/apps/web/app/api/config/config.ts
  frontend/apps/web/app/config/app-config.ts
  frontend/apps/web/app/layout.tsx
  frontend/apps/web/charts/app/README.md
  frontend/apps/web/charts/app/templates/_helpers.tpl
  frontend/apps/web/charts/app/values.yaml
  frontend/apps/web/components/providers/unify-provider.tsx
Labels: Feature

#3064 NEOS-1685: move logs and metrics to be behind license
  backend/charts/api/README.md
  backend/charts/api/values.yaml
  backend/internal/cmds/mgmt/serve/connect/cmd.go
  charts/neosync/README.md
  docs/docs/guides/viewing-job-run-logs.md
Labels: Tech Debt

#3063 Moves authentication to require a valid license
  .gitignore
  Makefile
  backend/internal/cmds/mgmt/serve/connect/cmd.go
  compose.dev.yml
  docs/docs/deploy/authentication.md
  docs/docs/deploy/docker-compose.md
  docs/docs/guides/neosync-local-dev.md
Labels: Tech Debt

#3069 Removes Experimental Connection Flags and unused FE feature flags
  frontend/apps/web/app/(mgmt)/[account]/connections/util.ts
  frontend/apps/web/app/(mgmt)/[account]/new/connection/page.tsx
  frontend/apps/web/app/api/config/config.ts
  frontend/apps/web/app/config/app-config.ts
Labels: Tech Debt

#3071 NEOS-1691: 12-19 changelog
  docs/blog/2024-12-19-RBAC.md
Labels: documentation

#3077 Sets up artifact release for develop/v0 branches
  .github/workflows/artifact-release.yml
Labels: Tech Debt
