Repository nucleuscloud/neosync, pull requests merged in 2024-09, with the labels that each got.

#2579 NEOS-1389: adds support for duplicating nosql mapping rows
  frontend/apps/web/components/jobs/NosqlTable/NosqlTable.tsx
  frontend/apps/web/components/jobs/NosqlTable/data-table-row-actions.tsx
Labels: Feature

#2583 NEOS-1391:update table header
  frontend/apps/web/components/jobs/NosqlTable/TableMappings/ColumnHeader.tsx
  frontend/apps/web/components/jobs/SchemaTable/SchemaColumnHeader.tsx
  frontend/apps/web/components/jobs/SchemaTable/VirtualFkColumnHeaders.tsx
  frontend/apps/web/components/jobs/subsets/subset-table/data-table-column-header.tsx
Labels: enhancement

#2569 NEOS-1364 TSQL parser
  go.mod
  go.sum
  worker/pkg/query-builder2/integration_test.go
  worker/pkg/query-builder2/query-builder_integration_test.go
  worker/pkg/query-builder2/querybuilder.go
  worker/pkg/query-builder2/testdata/mssql/setup.sql
  worker/pkg/query-builder2/testdata/mssql/teardown.sql
  worker/pkg/query-builder2/testdata/postgres/setup.sql
  worker/pkg/query-builder2/testdata/postgres/teardown.sql
  worker/pkg/query-builder2/tsql/query-qualifier.go
  worker/pkg/query-builder2/tsql/query-qualifier_test.go
  worker/pkg/workflows/datasync/workflow/integration_test.go
  worker/pkg/workflows/datasync/workflow/testdata/gen-jobmappings-config.json
  worker/pkg/workflows/datasync/workflow/testdata/jobmapping_generator.go
  worker/pkg/workflows/datasync/workflow/testdata/mssql/simple/create-schema-production.sql
  worker/pkg/workflows/datasync/workflow/testdata/mssql/simple/create-schema-sales.sql
  worker/pkg/workflows/datasync/workflow/testdata/mssql/simple/create-schema.sql
  worker/pkg/workflows/datasync/workflow/testdata/mssql/simple/create-table.sql
  worker/pkg/workflows/datasync/workflow/testdata/mssql/simple/insert.sql
  worker/pkg/workflows/datasync/workflow/testdata/mssql/simple/job_mappings.go
  worker/pkg/workflows/datasync/workflow/testdata/mssql/simple/teardown.sql
  worker/pkg/workflows/datasync/workflow/testdata/mssql/simple/tests.go
Labels: enhancement

#2578 NEOS-1388 mssql identity column passthrough
  backend/pkg/sqlmanager/shared/types.go
  backend/pkg/sqlmanager/shared/utils.go
  worker/pkg/benthos/config.go
  worker/pkg/benthos/sql/output_sql_insert.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/activity.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/sync.go
  worker/pkg/workflows/datasync/workflow/testdata/mssql/simple/create-table.sql
  worker/pkg/workflows/datasync/workflow/testdata/mssql/simple/insert.sql
Labels: bug

#2592 NEOS-1393: adds support for postgres special characters except for double quotes
  backend/gen/go/db/dbschemas/postgresql/system.sql.go
  backend/pkg/dbschemas/sql/postgresql/queries/system.sql
  backend/pkg/sqlmanager/postgres/integration_test.go
  backend/pkg/sqlmanager/postgres/postgres-manager_integration_test.go
  backend/pkg/sqlmanager/postgres/testdata/setup.sql
  backend/pkg/sqlmanager/postgres/testdata/teardown.sql
Labels: bug

#2593 updates duplicate mapping functinality to be more performant
  frontend/apps/web/components/jobs/NosqlTable/NosqlTable.tsx
  frontend/apps/web/components/jobs/NosqlTable/data-table-row-actions.tsx
Labels: enhancement

#2580 Run Config Refactor
  backend/pkg/table-dependency/circular-dependencies.go
  backend/pkg/table-dependency/circular-dependencies_test.go
  backend/pkg/table-dependency/dependency-builder.go
  backend/pkg/table-dependency/dependency-builder_test.go
  backend/pkg/table-dependency/table-dependency.go
  backend/pkg/table-dependency/table-dependency_test.go
  cli/internal/cmds/neosync/sync/sync.go
  worker/pkg/query-builder2/query-builder_integration_test.go
  worker/pkg/query-builder2/subset.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/benthos-builder_test.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/processors.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/processors_test.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/sync-dynamodb.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/sync-mongo.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/sync.go
Labels: Devex

#2595 NEOS-1398: disable truncate and on conflict options in sql server
  backend/gen/go/protos/mgmt/v1alpha1/job.pb.go
  backend/protos/mgmt/v1alpha1/job.proto
  docs/protos/data/proto_docs.json
  frontend/apps/web/components/jobs/Form/DestinationOptionsForm.tsx
  frontend/packages/sdk/src/client/mgmt/v1alpha1/job_pb.ts
Labels: bug

#2598 NEOS-1320: adds sql server documentation
  compose.yml
  docs/docs/connections/sqlserver.md
  docs/sidebars.ts
  docs/src/CustomComponents/IconHandler.tsx
  docs/static/img/mssql-connection.png
  docs/static/img/mssql-permissions.png
Labels: Docs

#2597 NEOS-1384 Fix mssql default
  worker/pkg/benthos/config.go
  worker/pkg/benthos/sql/output_sql_insert.go
  worker/pkg/benthos/sql/output_sql_insert_test.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/sync-dynamodb.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/sync-mongo.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/sync.go
  worker/pkg/workflows/datasync/workflow/testdata/mssql/simple/create-table.sql
  worker/pkg/workflows/datasync/workflow/testdata/mssql/simple/insert.sql
  worker/pkg/workflows/datasync/workflow/testdata/mssql/simple/job_mappings.go
  worker/pkg/workflows/datasync/workflow/testdata/mssql/simple/teardown.sql
  worker/pkg/workflows/datasync/workflow/testdata/mssql/simple/tests.go
  worker/pkg/workflows/datasync/workflow/testdata/mysql/init-schema/job_mappings.go
  worker/pkg/workflows/datasync/workflow/testdata/mysql/multiple-dbs/job_mappings.go
  worker/pkg/workflows/datasync/workflow/workflow_integration_test.go
Labels: bug

#2599 Fix Mssql subset not saving
  backend/internal/nucleusdb/jobs.go
Labels: bug

#2600 NEOS-1400: Enable sql server truncate
  backend/gen/go/protos/mgmt/v1alpha1/job.pb.go
  backend/pkg/sqlmanager/mssql/mssql-manager.go
  backend/protos/mgmt/v1alpha1/job.proto
  docs/protos/data/proto_docs.json
  frontend/apps/web/components/jobs/Form/DestinationOptionsForm.tsx
  frontend/packages/sdk/src/client/mgmt/v1alpha1/job_pb.ts
  worker/pkg/workflows/datasync/activities/run-sql-init-table-stmts/init-statement-builder.go
  worker/pkg/workflows/datasync/workflow/testdata/mssql/simple/tests.go
Labels: enhancement

#2604 enables fk subsetting option on frontend
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/subsets/components/SubsetCard.tsx
Labels: enhancement

#2605 rewrites truncation docs for mssql
  docs/docs/connections/sqlserver.md
Labels: Docs

#2607 NEOS-1395 Improve the readability of TSQL query qualifier
  worker/pkg/query-builder2/tsql/query-qualifier.go
Labels: Devex

#2611 NEOS-1402: expose generated columns in constraints in job mapping table
  backend/pkg/sqlmanager/mssql/mssql-manager.go
  backend/pkg/sqlmanager/mysql/mysql-manager.go
  backend/pkg/sqlmanager/postgres/postgres-manager.go
  backend/pkg/sqlmanager/shared/types.go
  backend/pkg/sqlmanager/shared/utils.go
  frontend/apps/web/components/jobs/SchemaTable/SchemaColumns.tsx
  frontend/apps/web/components/jobs/SchemaTable/SchemaTableToolBar.tsx
  frontend/apps/web/components/jobs/SchemaTable/SchemaTableViewOptions.tsx
  frontend/apps/web/components/jobs/SchemaTable/TransformerSelect.tsx
  frontend/apps/web/components/jobs/SchemaTable/schema-constraint-handler.ts
  worker/pkg/query-builder2/query-builder_integration_test.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/benthos-builder_test.go
Labels: enhancement

#2588 NEOS-1338: Add support for checking the connection in the connect page
  backend/gen/go/protos/mgmt/v1alpha1/connection.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/connection.pb.validate.go
  backend/gen/go/protos/mgmt/v1alpha1/mgmtv1alpha1connect/connection.connect.go
  backend/gen/go/protos/mgmt/v1alpha1/mgmtv1alpha1connect/mock_ConnectionServiceClient.go
  backend/protos/mgmt/v1alpha1/connection.proto
  backend/services/mgmt/v1alpha1/connection-service/connection.go
  docs/protos/data/proto_docs.json
  frontend/apps/web/app/(mgmt)/[account]/new/job/connect/page.tsx
  frontend/apps/web/app/globals.css
  frontend/apps/web/components/ui/button.tsx
  frontend/apps/web/components/ui/form.tsx
  frontend/apps/web/tailwind.config.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/connection-ConnectionService_connectquery.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/connection_connect.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/connection_pb.ts
Labels: enhancement

#2614 update the dynamdo db docs
  docs/docs/connections/dynamodb.md
Labels: Docs

#2581 NEOS-1379: handle duplicate mongo mappings
  frontend/apps/web/components/jobs/NosqlTable/NosqlTable.tsx
Labels: enhancement

#2613 Updates Docs to latest Docusaurus version
  docs/blog/2023-12-04-neosync-init.md
  docs/blog/2023-12-18-public-facing-apis.md
  docs/blog/2024-01-04-custom-code-transformers.md
  docs/blog/2024-01-18-conditional-transformers.md
  docs/blog/2024-02-01-circular-dependencies.md
  docs/blog/2024-02-15-terraform.md
  docs/blog/2024-02-29-foreign-key-transformations copy.md
  docs/blog/2024-03-14-metrics.md
  docs/blog/2024-03-28-partial-table-syncs copy.md
  docs/blog/2024-04-11-customer-generate-transformers copy.md
  docs/blog/2024-04-25-postgres-permissions copy.md
  docs/blog/2024-05-07-ai-generate-jobs.md
  docs/blog/2024-05-23-flexible-schema-references copy.md
  docs/blog/2024-06-06-real-time-validation.md
  docs/blog/2024-06-20-mongodb.md
  docs/blog/2024-07-04-job-cloning.md
  docs/blog/2024-07-18-transformers-in-javascript copy.md
  docs/blog/2024-08-01-dynamodb.md
  docs/blog/2024-08-15-dynamodb-upgrades copy.md
  docs/blog/2024-08-29-sql-server-support.md
  docs/blog/authors.yml
  docs/package-lock.json
  docs/package.json
  docs/src/css/overrides.css
  docs/src/theme/Blog/Components/Author/index.tsx
  docs/src/theme/Blog/Components/Author/styles.module.css
  docs/src/theme/DocBreadcrumbs/Items/Home/index.tsx
  docs/src/theme/DocBreadcrumbs/Items/Home/styles.module.css
  docs/src/theme/DocBreadcrumbs/index.tsx
  docs/src/theme/DocBreadcrumbs/styles.module.css
  docs/src/theme/DocSidebarItem/Category/index.tsx
  docs/src/theme/DocSidebarItem/Html/index.tsx
  docs/src/theme/DocSidebarItem/Html/styles.module.css
  docs/src/theme/DocSidebarItem/Link/index.tsx
  docs/src/theme/EditThisPage/index.tsx
  docs/src/theme/Navbar/Logo/index.tsx
  docs/src/theme/PaginatorNavLink/index.tsx
Labels: Docs

#2621 NEOS-1408: add option to apply defaults to job mapping table
  frontend/apps/web/components/ConfirmationDialog.tsx
  frontend/apps/web/components/DeleteConfirmationDialog.tsx
  frontend/apps/web/components/jobs/SchemaTable/SchemaTableToolBar.tsx
  frontend/apps/web/components/ui/alert-dialog.tsx
  frontend/apps/web/package.json
  frontend/package-lock.json
Labels: enhancement

#2622 NEOS-1412: Update transformer change
  frontend/apps/web/app/(mgmt)/[account]/connections/[id]/components/AwsS3Form.tsx
  frontend/apps/web/app/(mgmt)/[account]/connections/[id]/components/DynamoDBForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/connections/[id]/components/MssqlForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/connections/[id]/components/MysqlForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/connections/[id]/components/PostgresForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/connection/aws-s3/AwsS3Form.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/connection/gcp-cloud-storage/GcpCloudStorageForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/connection/mssql/MssqlForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/connection/mysql/MysqlForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/connection/postgres/PostgresForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/connect/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/transform-form-validations.ts
  frontend/apps/web/app/(mgmt)/[account]/transformers/[id]/components/UpdateTransformerForm.tsx
  frontend/apps/web/components/FormError.tsx
  frontend/apps/web/components/ui/form.tsx
Labels: bug

#2623 NEOS-1394:update tables
  frontend/apps/web/app/(mgmt)/[account]/runs/[id]/components/JobRunLogsTable/data-table.tsx
  frontend/apps/web/components/ListBox/ListBox.tsx
  frontend/apps/web/components/jobs/NosqlTable/TableMappings/TableMappingsTable.tsx
  frontend/apps/web/components/jobs/SchemaTable/AiSchemaPageTable.tsx
  frontend/apps/web/components/jobs/SchemaTable/SchemaPageTable.tsx
  frontend/apps/web/components/jobs/SchemaTable/VirtualFkPageTable.tsx
  frontend/apps/web/components/jobs/subsets/subset-table/data-table.tsx
  frontend/apps/web/components/permissions/PermissionsDataTable.tsx
  frontend/apps/web/components/permissions/PermissionsDialog.tsx
Labels: bug

#2624 NEOS-1406:fix aws dynamodb form
  frontend/apps/web/app/(mgmt)/[account]/connections/util.ts
  frontend/apps/web/app/(mgmt)/[account]/new/connection/aws-s3/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/connection/dynamodb/DynamoDBForm.tsx
Labels: bug

#2625 update copy
  frontend/apps/web/app/(mgmt)/[account]/new/job/connect/page.tsx
  frontend/apps/web/components/jobs/SchemaTable/SchemaTableToolBar.tsx
Labels: enhancement

#2631 NEOS:1416: simplify isDuplicate mapping logic for NoSql db
  frontend/apps/web/components/jobs/NosqlTable/NosqlTable.tsx
Labels: enhancement

#2632 NEOS-1415: re enable team accounts in oss
  backend/services/mgmt/v1alpha1/user-account-service/users.go
  frontend/apps/web/app/(mgmt)/[account]/settings/billing/page.tsx
  frontend/apps/web/components/site-header/AccountSwitcher.tsx
  frontend/apps/web/components/site-header/SiteHeader.tsx
Labels: bug

#2633 NEOS-1415: enables account switcher in neosynccloud, disables create team for cloud
  backend/services/mgmt/v1alpha1/user-account-service/users.go
  frontend/apps/web/components/site-header/AccountSwitcher.tsx
Labels: bug

#2634 NEOS-1371 support postgres array types
  backend/pkg/sqlmanager/shared/types.go
  backend/pkg/sqlmanager/sql-manager.go
  go.mod
  internal/dynamodb/utils.go
  internal/dynamodb/utils_test.go
  internal/gotype-parser/parser_test.go
  internal/gotype-parser/parsers.go
  internal/postgres/utils.go
  internal/postgres/utils_test.go
  worker/internal/connection-tunnel-manager/manager.go
  worker/internal/connection-tunnel-manager/manager_test.go
  worker/internal/connection-tunnel-manager/providers/provider.go
  worker/pkg/benthos/sql/input_sql_raw.go
  worker/pkg/query-builder/query-builder.go
  worker/pkg/workflows/datasync/workflow/testdata/gen-jobmappings-config.json
  worker/pkg/workflows/datasync/workflow/testdata/postgres/all-types/job_mappings.go
  worker/pkg/workflows/datasync/workflow/testdata/postgres/all-types/schema-create.sql
  worker/pkg/workflows/datasync/workflow/testdata/postgres/all-types/setup.sql
  worker/pkg/workflows/datasync/workflow/testdata/postgres/all-types/teardown.sql
  worker/pkg/workflows/datasync/workflow/testdata/postgres/all-types/tests.go
  worker/pkg/workflows/datasync/workflow/workflow_integration_test.go
Labels: enhancement

#2635 NEOS-1414: add otel trace and meter instrumentation to api and worker
  backend/dev/build/Dockerfile.dev
  backend/internal/cmds/mgmt/serve/connect/cmd.go
  compose.dev.yml
  docs/docs/connections/dynamodb.md
  docs/docs/deploy/environment-variables.md
  go.mod
  go.sum
  internal/otel/otel.go
  worker/dev/build/Dockerfile.dev
  worker/internal/cmds/worker/serve/serve.go
Labels: enhancement

#2639 NEOS-1422: remove tabs when no virtual foreign keys
  frontend/apps/web/components/jobs/SchemaTable/SchemaTable.tsx
Labels: enhancement

#2644 NEOS-1425 Fixes SQL Server unique identifier type in sync
  internal/sqlserver/utils.go
  worker/pkg/benthos/sql/input_sql_raw.go
  worker/pkg/workflows/datasync/workflow/testdata/gen-jobmappings-config.json
  worker/pkg/workflows/datasync/workflow/testdata/mssql/data-types/create-schema.sql
  worker/pkg/workflows/datasync/workflow/testdata/mssql/data-types/create-table.sql
  worker/pkg/workflows/datasync/workflow/testdata/mssql/data-types/insert.sql
  worker/pkg/workflows/datasync/workflow/testdata/mssql/data-types/job_mappings.go
  worker/pkg/workflows/datasync/workflow/testdata/mssql/data-types/teardown.sql
  worker/pkg/workflows/datasync/workflow/testdata/mssql/data-types/tests.go
  worker/pkg/workflows/datasync/workflow/workflow_integration_test.go
Labels: bug

#2642 NEOS-1427, NEOS-1428: [MIGRATION] adds methods for checking account status
  backend/gen/go/db/mock_Querier.go
  backend/gen/go/db/models.go
  backend/gen/go/db/querier.go
  backend/gen/go/db/users.sql.go
  backend/gen/go/protos/mgmt/v1alpha1/mgmtv1alpha1connect/mock_UserAccountServiceClient.go
  backend/gen/go/protos/mgmt/v1alpha1/mgmtv1alpha1connect/user_account.connect.go
  backend/gen/go/protos/mgmt/v1alpha1/user_account.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/user_account.pb.validate.go
  backend/internal/cmds/mgmt/serve/connect/cmd.go
  backend/internal/dtomaps/users.go
  backend/pkg/metrics/usage.go
  backend/pkg/metrics/usage_test.go
  backend/protos/mgmt/v1alpha1/user_account.proto
  backend/services/mgmt/v1alpha1/integration_tests/integration_test.go
  backend/services/mgmt/v1alpha1/integration_tests/integration_util_test.go
  backend/services/mgmt/v1alpha1/integration_tests/user-account-service_integration_test.go
  backend/services/mgmt/v1alpha1/metrics-service/metrics.go
  backend/services/mgmt/v1alpha1/metrics-service/metrics_test.go
  backend/services/mgmt/v1alpha1/user-account-service/billing.go
  backend/services/mgmt/v1alpha1/user-account-service/billing_test.go
  backend/services/mgmt/v1alpha1/user-account-service/service.go
  backend/services/mgmt/v1alpha1/user-account-service/users.go
  backend/services/mgmt/v1alpha1/user-account-service/users_test.go
  backend/sql/postgresql/queries/users.sql
  backend/sql/postgresql/schema/20240909203811_accounts-add-allowed-record-count.down.sql
  backend/sql/postgresql/schema/20240909203811_accounts-add-allowed-record-count.up.sql
  docs/protos/data/proto_docs.json
  frontend/packages/sdk/src/client/mgmt/v1alpha1/user_account-UserAccountService_connectquery.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/user_account_connect.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/user_account_pb.ts
Labels: enhancement

#2646 NEOS-1426 Fix SQL Server bit data type in sync
  internal/sqlserver/utils.go
  internal/sqlserver/utils_test.go
  worker/pkg/benthos/sql/output_sql_insert.go
  worker/pkg/benthos/sql/output_sql_insert_test.go
  worker/pkg/query-builder/query-builder.go
  worker/pkg/workflows/datasync/workflow/testdata/mssql/data-types/create-table.sql
  worker/pkg/workflows/datasync/workflow/testdata/mssql/data-types/insert.sql
  worker/pkg/workflows/datasync/workflow/testdata/mssql/data-types/job_mappings.go
Labels: bug

#2638 NEOS-1423: make transformer slide out controlled
  compose.dev.yml
  frontend/apps/web/app/(mgmt)/[account]/transformers/EditTransformerOptions.tsx
Labels: enhancement

#2637 NEOS-1403:update forms to not shift on errors
  frontend/apps/web/app/(mgmt)/[account]/new/job/connect/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/define/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/generate/single/schema/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateCardNumber.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateCategoricalForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateCountryForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateEmailForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateGenderForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateInt64Form.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateInternationalPhoneNumberForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateStateForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateStringForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateStringPhoneNumberForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateUuidForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformCharacterScrambleForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformE164PhoneNumberForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformEmailForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformFirstNameForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformFloat64Form.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformFullNameForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformInt64Form.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformInt64PhoneForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformLastNameForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformPhoneNumberForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformStringForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/[id]/components/UpdateTransformerForm.tsx
  frontend/apps/web/components/ListBox/ListBox.tsx
  frontend/apps/web/components/jobs/NosqlTable/NosqlTable.tsx
  frontend/apps/web/components/ui/form.tsx
Labels: enhancement

#2655 NEOS-1441: adds dialog for showing SELECT from job run
  backend/services/mgmt/v1alpha1/job-service/runs.go
  compose.dev.yml
  frontend/apps/web/app/(mgmt)/[account]/runs/[id]/components/JobRunActivityTable.tsx
  frontend/apps/web/app/(mgmt)/[account]/runs/[id]/components/JobRunActivityTable/data-table.tsx
  frontend/apps/web/app/(mgmt)/[account]/runs/[id]/page.tsx
  frontend/apps/web/components/CopyButton.tsx
  frontend/apps/web/package.json
  frontend/package-lock.json
Labels: enhancement

#2650 NEOS-1417: update yup error messages
  frontend/apps/web/app/(mgmt)/[account]/new/api-key/NewApiKeyForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/[id]/destination/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/job-form-validations.ts
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/settings/api-keys/[id]/regenerate/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/settings/members/components/InviteUserForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/settings/temporal/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/EditTransformerOptions.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/[id]/components/UpdateTransformerForm.tsx
  frontend/apps/web/app/api/webhooks/keycloak/add-to-crm/route.ts
  frontend/apps/web/app/api/webhooks/keycloak/slack/route.ts
  frontend/apps/web/app/api/webhooks/keycloak/welcome-email/route.ts
  frontend/apps/web/components/jobs/NosqlTable/NosqlTable.tsx
  frontend/apps/web/components/site-header/AccountSwitcher.tsx
  frontend/apps/web/yup-validations/account-switcher.ts
  frontend/apps/web/yup-validations/apikey.ts
  frontend/apps/web/yup-validations/connections.ts
  frontend/apps/web/yup-validations/invite-members.ts
  frontend/apps/web/yup-validations/jobs.ts
  frontend/apps/web/yup-validations/temporal.ts
  frontend/apps/web/yup-validations/transformer-validations.ts
Labels: enhancement

#2640 NEOS-1421, NEOS-1420: Schema page updates
  frontend/apps/web/components/ListBox/ListBox.tsx
  frontend/apps/web/components/jobs/SchemaTable/FormErrorsCard.tsx
Labels: Improvement

#2662 NEOS-1443: Properly escapes special schema, table, column when transforming primary keys
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/processors.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/sync.go
  worker/pkg/workflows/datasync/workflow/integration_test.go
  worker/pkg/workflows/datasync/workflow/testdata/primary-key-transformer/create.sql
  worker/pkg/workflows/datasync/workflow/testdata/primary-key-transformer/insert.sql
  worker/pkg/workflows/datasync/workflow/testdata/primary-key-transformer/job_mappings.go
  worker/pkg/workflows/datasync/workflow/testdata/primary-key-transformer/teardown.sql
  worker/pkg/workflows/datasync/workflow/testdata/primary-key-transformer/tests.go
Labels: bug

#2663 re-enables no console lint for frontend
  frontend/apps/web/.eslintrc.json
  frontend/apps/web/app/(mgmt)/[account]/runs/[id]/page.tsx
Labels: Tech Debt, ignore-for-release

#2652 NEOS-1432: update workflow to have account status check
  Makefile
  backend/services/mgmt/v1alpha1/integration_tests/user-account-service_integration_test.go
  backend/services/mgmt/v1alpha1/user-account-service/billing.go
  docs/docs/deploy/environment-variables.md
  worker/internal/cmds/worker/serve/serve.go
  worker/pkg/workflows/datasync/activities/account-status/activity.go
  worker/pkg/workflows/datasync/activities/account-status/activity_test.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/activity.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/benthos-builder.go
  worker/pkg/workflows/datasync/activities/run-sql-init-table-stmts/activity.go
  worker/pkg/workflows/datasync/activities/run-sql-init-table-stmts/init-statement-builder_test.go
  worker/pkg/workflows/datasync/activities/sync-activity-opts/activity.go
  worker/pkg/workflows/datasync/activities/sync-redis-clean-up/activity.go
  worker/pkg/workflows/datasync/workflow/workflow.go
  worker/pkg/workflows/datasync/workflow/workflow_integration_test.go
  worker/pkg/workflows/datasync/workflow/workflow_test.go
Labels: enhancement

#2664 NEOS-1431: update docs to remove broken links and fill in missing docs
  docs/docs/transformers/system.md
Labels: Docs

#2665 NEOS-1438 Destination option to skip foreign key constraint errors in sync
  backend/gen/go/protos/mgmt/v1alpha1/job.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/job.pb.validate.go
  backend/protos/mgmt/v1alpha1/job.proto
  backend/sql/postgresql/models/models.go
  docs/protos/data/proto_docs.json
  frontend/apps/web/app/(mgmt)/[account]/jobs/util.ts
  frontend/apps/web/app/(mgmt)/[account]/new/job/connect/page.tsx
  frontend/apps/web/components/jobs/Form/DestinationOptionsForm.tsx
  frontend/apps/web/yup-validations/jobs.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/job_pb.ts
  worker/pkg/benthos/config.go
  worker/pkg/benthos/sql/output_sql_insert.go
  worker/pkg/benthos/sql/output_sql_update.go
  worker/pkg/benthos/utils.go
  worker/pkg/query-builder/query-builder.go
  worker/pkg/query-builder/query-builder_test.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/sync.go
  worker/pkg/workflows/datasync/workflow/testdata/gen-jobmappings-config.json
  worker/pkg/workflows/datasync/workflow/testdata/skip-fk-violations/create.sql
  worker/pkg/workflows/datasync/workflow/testdata/skip-fk-violations/insert.sql
  worker/pkg/workflows/datasync/workflow/testdata/skip-fk-violations/job_mappings.go
  worker/pkg/workflows/datasync/workflow/testdata/skip-fk-violations/teardown.sql
  worker/pkg/workflows/datasync/workflow/testdata/skip-fk-violations/tests.go
  worker/pkg/workflows/datasync/workflow/testdata/types.go
  worker/pkg/workflows/datasync/workflow/workflow_integration_test.go
Labels: Feature

#2653 NEOS-1439: update name field lengths
  backend/gen/go/protos/mgmt/v1alpha1/api_key.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/connection.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/transformer.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/user_account.pb.go
  backend/protos/mgmt/v1alpha1/api_key.proto
  backend/protos/mgmt/v1alpha1/connection.proto
  backend/protos/mgmt/v1alpha1/job.proto
  backend/protos/mgmt/v1alpha1/transformer.proto
  backend/protos/mgmt/v1alpha1/user_account.proto
  frontend/apps/web/app/(mgmt)/[account]/connections/components/ConnectionsTable/columns.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/layout.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/components/DataTable/columns.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/job-form-validations.ts
  frontend/apps/web/app/(mgmt)/[account]/settings/api-keys/[id]/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/settings/api-keys/components/ApiKeysTable/columns.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/components/UserDefinedTransformersTable/columns.tsx
  frontend/apps/web/components/ResourceId.tsx
  frontend/apps/web/components/TruncatedText.tsx
  frontend/apps/web/components/headers/PageHeader.tsx
  frontend/apps/web/components/jobs/SchemaTable/TransformerSelect.tsx
  frontend/apps/web/yup-validations/account-switcher.ts
  frontend/apps/web/yup-validations/apikey.ts
  frontend/apps/web/yup-validations/connections.ts
  frontend/apps/web/yup-validations/transformer-validations.ts
Labels: enhancement

#2669 Fix SQL Server identity column count after insert
  backend/pkg/sqlmanager/mssql/mssql-manager.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/sync.go
  worker/pkg/workflows/datasync/activities/run-sql-init-table-stmts/init-statement-builder.go
Labels: bug

#2670 fixed heading
  frontend/apps/web/components/headers/PageHeader.tsx
Labels: bug

#2671 NEOS-1407, NEOS-1444 Support passthrough for postgres Identity Generated Always columns
  backend/gen/go/protos/mgmt/v1alpha1/job.pb.go
  backend/pkg/dbconnect-config/mssql.go
  backend/pkg/dbconnect-config/postgres.go
  backend/pkg/mongomanager/utils.go
  backend/pkg/sqlmanager/postgres/postgres-manager.go
  cli/internal/output/output.go
  docs/protos/data/proto_docs.json
  frontend/apps/web/components/jobs/SchemaTable/transformer-handler.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/job_pb.ts
  worker/pkg/benthos/dynamodb/output.go
  worker/pkg/benthos/sql/output_sql_insert.go
  worker/pkg/benthos/transformers/utils/integer_utils.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/sync.go
  worker/pkg/workflows/datasync/workflow/testdata/postgres/all-types/job_mappings.go
  worker/pkg/workflows/datasync/workflow/testdata/postgres/all-types/setup.sql
Labels: enhancement

#2672 Replaces Docker Compose Watch with Bind Mounts
  .gitignore
  Makefile
  backend/dev/build/.air.toml
  backend/dev/build/Dockerfile.dev
  compose.dev.yml
  compose/temporal/compose.yml
  docs/docs/guides/neosync-local-dev.md
  frontend/apps/web/dev/build/Dockerfile.dev
  worker/cmd/worker/main.go
  worker/dev/build/.air.toml
  worker/dev/build/Dockerfile.dev
Labels: Tech Debt

#2677 NEOS-1454: publish changelog for 9-12
  docs/blog/2024-09-12-apply-default-transformers.md
Labels: Docs

#2673 NEOS-1442:disables the Apply Default Transformers button until a table is selected
  frontend/apps/web/components/jobs/SchemaTable/SchemaTableToolBar.tsx
Labels: Improvement

#2679 NEOS-1451: custom transformers not showing up in bulk set
  frontend/apps/web/components/jobs/Form/DynamoDBSourceOptionsForm.tsx
  frontend/apps/web/components/jobs/NosqlTable/NosqlTable.tsx
  frontend/apps/web/components/jobs/SchemaTable/SchemaColumns.tsx
  frontend/apps/web/components/jobs/SchemaTable/SchemaTableToolBar.tsx
  frontend/apps/web/util/util.ts
Labels: bug

#2681 updates tooltipproviders in attributes column to not be submit buttons
  frontend/apps/web/components/jobs/SchemaTable/SchemaColumns.tsx
Labels: bug

#2682 NEOS-1424: fixes ability to remove a team invite
  frontend/apps/web/app/(mgmt)/[account]/settings/members/components/InviteTable.tsx
Labels: bug

#2684 Adds search input to job mapping table, fixes sort states
  frontend/apps/web/components/DualListBox/ColumnHeader.tsx
  frontend/apps/web/components/jobs/NosqlTable/TableMappings/ColumnHeader.tsx
  frontend/apps/web/components/jobs/SchemaTable/SchemaColumnHeader.tsx
  frontend/apps/web/components/jobs/SchemaTable/SchemaColumns.tsx
  frontend/apps/web/components/jobs/SchemaTable/SchemaPageTable.tsx
  frontend/apps/web/components/jobs/subsets/subset-table/column.tsx
Labels: enhancement

#2683 NEOS-1459: update schema page table max height
  frontend/apps/web/components/jobs/SchemaTable/SchemaPageTable.tsx
Labels: Improvement

#2686 NEOS-1453: disables bulk transformer button based on selected rows
  frontend/apps/web/app/(mgmt)/[account]/transformers/EditTransformerOptions.tsx
  frontend/apps/web/components/jobs/SchemaTable/SchemaTableToolBar.tsx
  frontend/apps/web/components/jobs/SchemaTable/SchemaTableViewOptions.tsx
Labels: bug

#2678 NEOS-1457 Support postgres JSON and JSONB arrays
  backend/pkg/sqlmanager/postgres/postgres-manager.go
  backend/pkg/sqlmanager/postgres/postgres-manager_test.go
  internal/dynamodb/utils.go
  internal/gotype-parser/parser_test.go
  internal/gotype-parser/parsers.go
  internal/gotypeutil/gotypeutil.go
  internal/gotypeutil/gotypeutil_test.go
  internal/gotypeutil/parser_test.go
  internal/gotypeutil/parsers.go
  internal/postgres/utils.go
  internal/postgres/utils_test.go
  worker/pkg/benthos/config.go
  worker/pkg/benthos/sql/output_sql_insert.go
  worker/pkg/query-builder/query-builder.go
  worker/pkg/query-builder/query-builder_test.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/benthos-builder.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/sync.go
  worker/pkg/workflows/datasync/activities/run-sql-init-table-stmts/init-statement-builder.go
  worker/pkg/workflows/datasync/activities/shared/shared.go
  worker/pkg/workflows/datasync/workflow/testdata/postgres/all-types/job_mappings.go
  worker/pkg/workflows/datasync/workflow/testdata/postgres/all-types/schema-create.sql
  worker/pkg/workflows/datasync/workflow/testdata/postgres/all-types/setup.sql
  worker/pkg/workflows/datasync/workflow/testdata/postgres/all-types/teardown.sql
  worker/pkg/workflows/datasync/workflow/testdata/postgres/all-types/tests.go
  worker/pkg/workflows/datasync/workflow/testdata/postgres/subsetting/teardown.sql
Labels: bug, Postgresql

#2687 NEOS-1456: replaces the transformer sheet with a dialog
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateCardNumber.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateCategoricalForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateCountryForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateEmailForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateFloat64Form.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateGenderForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateInt64Form.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateInternationalPhoneNumberForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateJavascriptForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateStateForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateStringForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateStringPhoneNumberForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateUuidForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformCharacterScrambleForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformE164PhoneNumberForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformEmailForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformFirstNameForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformFloat64Form.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformFullNameForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformInt64Form.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformInt64PhoneForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformJavascriptForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformLastNameForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformPhoneNumberForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformStringForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/EditTransformerOptions.tsx
Labels: Improvement

#2691 NEOS-1463 Fix postgres UUID array
  internal/postgres/utils.go
  worker/pkg/workflows/datasync/workflow/testdata/postgres/all-types/job_mappings.go
  worker/pkg/workflows/datasync/workflow/testdata/postgres/all-types/setup.sql
Labels: bug, Postgresql

#2692 updates transform character scramble to return empty strings and nils properly
  worker/pkg/benthos/transformers/transform_character_scramble.go
  worker/pkg/benthos/transformers/transform_character_scramble_test.go
Labels: bug

#2693 adds missing env vars for otel support to backend
  backend/charts/api/templates/deployment.yaml
Labels: enhancement

#2694 Fix query builder index out of range error
  worker/pkg/query-builder/query-builder.go
  worker/pkg/query-builder/query-builder_test.go
Labels: bug

#2697 NEOS-1467: update benthos specs and docs to match
  docs/docs/transformers/system.md
  worker/pkg/benthos/transformers/generate_bool.go
  worker/pkg/benthos/transformers/generate_card_number.go
  worker/pkg/benthos/transformers/generate_country.go
  worker/pkg/benthos/transformers/generate_first_name.go
  worker/pkg/benthos/transformers/generate_float.go
  worker/pkg/benthos/transformers/generate_full_address.go
  worker/pkg/benthos/transformers/generate_gender.go
  worker/pkg/benthos/transformers/generate_int64.go
  worker/pkg/benthos/transformers/generate_int64_phone_number.go
  worker/pkg/benthos/transformers/generate_international_phone_number.go
  worker/pkg/benthos/transformers/generate_random_string.go
  worker/pkg/benthos/transformers/generate_sha256hash.go
  worker/pkg/benthos/transformers/generate_ssn.go
  worker/pkg/benthos/transformers/generate_state.go
  worker/pkg/benthos/transformers/generate_string_phone_number.go
  worker/pkg/benthos/transformers/generate_unix_timestamp.go
  worker/pkg/benthos/transformers/generate_zipcode.go
  worker/pkg/benthos/transformers/transform_character_scramble.go
  worker/pkg/benthos/transformers/transform_email.go
  worker/pkg/benthos/transformers/transform_float.go
  worker/pkg/benthos/transformers/transform_int64.go
  worker/pkg/benthos/transformers/transform_int64_phone_number.go
  worker/pkg/benthos/transformers/transform_lastname.go
  worker/pkg/benthos/transformers/transform_string.go
  worker/pkg/benthos/transformers/transform_string_phone_number.go
Labels: Improvement

#2690 NEOS-1462: Add transformer links to app
  docs/docs/transformers/system.md
  frontend/apps/web/app/(mgmt)/[account]/connections/[id]/permissions/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateJavascriptForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformCharacterScrambleForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformJavascriptForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/EditTransformerOptions.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/[id]/components/UpdateTransformerForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/systemTransformers/[source]/page.tsx
  frontend/apps/web/components/headers/PageHeader.tsx
  frontend/apps/web/components/labels/LearnMoreLink.tsx
  frontend/apps/web/components/labels/LearnMoreTag.tsx
  frontend/apps/web/components/permissions/PermissionsDialog.tsx
Labels: enhancement

#2702 Reduces bastion host network error logs
  backend/pkg/sshtunnel/tunnel.go
Labels: Tech Debt

#2704 NEOS-1471: update sql server bastion host docs
  docs/docs/connections/sqlserver.md
  docs/static/img/sqlconn.png
Labels: documentation

#2696 NEOS-1248:add optional chaining to toDate() func to avoid "toDate() is not a function" errors
  frontend/apps/web/app/(mgmt)/[account]/connections/components/ConnectionsTable/columns.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/components/NextRuns.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/components/DataTable/columns.tsx
  frontend/apps/web/app/(mgmt)/[account]/runs/[id]/components/JobRunActivityTable/columns.tsx
  frontend/apps/web/app/(mgmt)/[account]/runs/[id]/components/JobRunActivityTable/data-table.tsx
  frontend/apps/web/app/(mgmt)/[account]/runs/components/JobRunsTable/columns.tsx
  frontend/apps/web/app/(mgmt)/[account]/settings/api-keys/components/ApiKeysTable/columns.tsx
  frontend/apps/web/app/(mgmt)/[account]/settings/members/components/InviteTable.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/components/UserDefinedTransformersTable/columns.tsx
Labels: bug

#2706 NEOS-1468 Add generate job workflow integration test
  worker/pkg/workflows/datasync/workflow/testdata/generate-job/setup.sql
  worker/pkg/workflows/datasync/workflow/testdata/generate-job/teardown.sql
  worker/pkg/workflows/datasync/workflow/workflow_integration_test.go
Labels: Devex

#2709 NEOS-1472: add frontend banner that displays account status
  frontend/apps/web/app/(mgmt)/[account]/settings/billing/page.tsx
  frontend/apps/web/components/headers/SubPageHeader.tsx
  frontend/apps/web/components/site-header/SiteHeader.tsx
  frontend/apps/web/components/site-header/Upgrade.tsx
  frontend/apps/web/components/site-header/UpgradeButton.tsx
  frontend/apps/web/components/ui/dialog.tsx
Labels: enhancement

#2674 NEOS-1449: adds a running timer to the run id page
  frontend/apps/web/app/(mgmt)/[account]/runs/[id]/page.tsx
Labels: enhancement

#2711 Updates Bastion Host Guide docs to include different SSH Algorithms
  docs/docs/guides/connect-with-bastion-host.md
Labels: Docs

#2695 NEOS-1419: add real time connection validation for the Generate job
  frontend/apps/web/app/(mgmt)/[account]/new/job/connect/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/generate/single/connect/page.tsx
  frontend/apps/web/components/connections/TestConnectionBadge.tsx
Labels: enhancement

#2715 Fix(worker-chart): remove empty label if value not set
  worker/charts/worker/templates/deployment.yaml
Labels: enhancement

#2717 Adds extraEnvVars to api deployment init container for db migrations
  backend/charts/api/README.md
  backend/charts/api/templates/deployment.yaml
  backend/charts/api/values.yaml
  charts/neosync/README.md
Labels: enhancement

#2718 NEOS-1478 Separate sql statements from args
  internal/postgres/utils.go
  worker/pkg/benthos/sql/output_sql_insert.go
  worker/pkg/query-builder/query-builder.go
  worker/pkg/query-builder/query-builder_test.go
  worker/pkg/workflows/datasync/workflow/testdata/javascript-transformers/create.sql
  worker/pkg/workflows/datasync/workflow/testdata/postgres/all-types/job_mappings.go
  worker/pkg/workflows/datasync/workflow/testdata/postgres/all-types/setup.sql
  worker/pkg/workflows/datasync/workflow/testdata/postgres/all-types/tests.go
Labels: bug

#2719 feat(charts): make nucleusEnv an optional label for all charts
  backend/charts/api/templates/deployment.yaml
  frontend/apps/web/charts/app/templates/deployment.yaml
Labels: enhancement

#2724 data sync mode docs
  docs/docs/guides/incremental-additions.md
  docs/sidebars.ts
  docs/static/img/destoptions.png
Labels: documentation

#2725 Fix SQL Server identity reset bug
  worker/pkg/workflows/datasync/activities/run-sql-init-table-stmts/init-statement-builder.go
Labels: bug

#2723 NEOS-1464 Support MYSQL Bit, Date and Json types
  backend/pkg/dbconnect-config/mysql.go
  backend/pkg/dbconnect-config/mysql_test.go
  backend/pkg/sqlmanager/mysql/integration_test.go
  backend/pkg/sqlmanager/mysql_sql-manager_integration_test.go
  backend/pkg/sqlmanager/sql-manager.go
  internal/mysql/mysql.go
  internal/sqlscanners/scanners.go
  internal/sqlscanners/scanners_test.go
  worker/pkg/benthos/environment/environment.go
  worker/pkg/benthos/sql/input_sql_raw.go
  worker/pkg/benthos/sql/output_sql_insert.go
  worker/pkg/benthos/sql/output_sql_insert_test.go
  worker/pkg/query-builder/query-builder.go
  worker/pkg/query-builder/query-builder_test.go
  worker/pkg/workflows/datasync/activities/sync/activity.go
  worker/pkg/workflows/datasync/workflow/integration_test.go
  worker/pkg/workflows/datasync/workflow/testdata/gen-jobmappings-config.json
  worker/pkg/workflows/datasync/workflow/testdata/mysql/all-types/create-dbs.sql
  worker/pkg/workflows/datasync/workflow/testdata/mysql/all-types/create.sql
  worker/pkg/workflows/datasync/workflow/testdata/mysql/all-types/insert.sql
  worker/pkg/workflows/datasync/workflow/testdata/mysql/all-types/job_mappings.go
  worker/pkg/workflows/datasync/workflow/testdata/mysql/all-types/teardown.sql
  worker/pkg/workflows/datasync/workflow/testdata/mysql/all-types/tests.go
  worker/pkg/workflows/datasync/workflow/workflow_integration_test.go
Labels: enhancement

#2721 NEOS-1429, NEOS-1475: [MIGRATION]: adds self-checkout billing to neosync cloud
  .mockery.yml
  backend/dev/build/Dockerfile.dev
  backend/gen/go/db/mock_Querier.go
  backend/gen/go/db/models.go
  backend/gen/go/db/querier.go
  backend/gen/go/db/users.sql.go
  backend/gen/go/protos/mgmt/v1alpha1/mgmtv1alpha1connect/mock_UserAccountServiceClient.go
  backend/gen/go/protos/mgmt/v1alpha1/mgmtv1alpha1connect/user_account.connect.go
  backend/gen/go/protos/mgmt/v1alpha1/user_account.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/user_account.pb.validate.go
  backend/internal/cmds/mgmt/serve/connect/cmd.go
  backend/internal/dtomaps/users.go
  backend/internal/nucleusdb/enums.go
  backend/internal/nucleusdb/users.go
  backend/internal/nucleusdb/users_test.go
  backend/protos/mgmt/v1alpha1/user_account.proto
  backend/services/mgmt/v1alpha1/integration_tests/integration_test.go
  backend/services/mgmt/v1alpha1/integration_tests/user-account-service_integration_test.go
  backend/services/mgmt/v1alpha1/user-account-service/billing.go
  backend/services/mgmt/v1alpha1/user-account-service/service.go
  backend/services/mgmt/v1alpha1/user-account-service/users.go
  backend/sql/postgresql/queries/users.sql
  backend/sql/postgresql/schema/20240917185036_add-account-stripe-custid.down.sql
  backend/sql/postgresql/schema/20240917185036_add-account-stripe-custid.up.sql
  compose.dev.yml
  docs/protos/data/proto_docs.json
  frontend/apps/web/app/(mgmt)/[account]/settings/billing/page.tsx
  frontend/apps/web/app/api/config/config.ts
  frontend/apps/web/app/config/app-config.ts
  frontend/apps/web/components/site-header/AccountSwitcher.tsx
  frontend/apps/web/components/site-header/SiteHeader.tsx
  frontend/apps/web/components/site-header/Upgrade.tsx
  frontend/apps/web/components/site-header/UpgradeButton.tsx
  frontend/packages/sdk/src/client/mgmt/v1alpha1/user_account-UserAccountService_connectquery.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/user_account_connect.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/user_account_pb.ts
  go.mod
  go.sum
  internal/billing/mock_Interface.go
  internal/billing/stripe-billing.go
  internal/billing/stripe-billing_test.go
Labels: enhancement, database-migration

#2728 NEOS-1483 SQL types to Javascript types transformer docs
  docs/docs/transformers/sql-javascript-transformer.md
  docs/sidebars.ts
  internal/postgres/utils.go
Labels: bug, Docs

#2730 Updates dev frontend app helmfile reference in docs
  docs/docs/deploy/kubernetes.md
Labels: documentation

#2731 Fix SQL type to JS type doc spell check comment
  docs/docs/transformers/sql-javascript-transformer.md
Labels: Docs

#2735 NEOS-1433 Updates javascript transformer to use patch function
  worker/pkg/benthos/javascript/functions.go
  worker/pkg/benthos/javascript/functions_test.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/processors.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/processors_test.go
Labels: bug

#2740 Updates View Select Query to use Monaco Editor
  frontend/apps/web/app/(mgmt)/[account]/runs/[id]/page.tsx
  frontend/apps/web/package.json
  frontend/package-lock.json
Labels: enhancement

#2741 NEOS-1489 Fix default being converted to database DEFAULT
  backend/pkg/sqlmanager/mssql/mssql-manager.go
  backend/pkg/sqlmanager/mssql/mssql-manager_integration_test.go
  backend/pkg/sqlmanager/mssql/testdata/source-setup/004.sql
  backend/pkg/sqlmanager/mysql/mysql-manager.go
  backend/pkg/sqlmanager/postgres/postgres-manager.go
  backend/pkg/sqlmanager/postgres/postgres-manager_integration_test.go
  backend/pkg/sqlmanager/postgres/testdata/setup.sql
  backend/pkg/sqlmanager/sql-manager.go
  internal/gotypeutil/strings.go
  internal/gotypeutil/strings_test.go
  internal/sqlserver/utils.go
  internal/sqlserver/utils_test.go
  worker/pkg/benthos/config.go
  worker/pkg/benthos/sql/output_sql_insert.go
  worker/pkg/query-builder/query-builder.go
  worker/pkg/query-builder/query-builder_test.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/activity.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/benthos-builder.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/benthos-builder_test.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/generate.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/sync.go
  worker/pkg/workflows/datasync/workflow/testdata/postgres/all-types/setup.sql
Labels: bug

#2739 NEOS-1490: updates logic to apply passthrough to identity columns
  frontend/apps/web/components/jobs/SchemaTable/SchemaTableToolBar.tsx
Labels: bug

#2738 NEOS-1474: update usage metrics to use date attribute for counts
  .mockery.yml
  backend/pkg/metrics/labels.go
  backend/pkg/metrics/labels_test.go
  backend/pkg/metrics/usage.go
  backend/pkg/metrics/usage_test.go
  backend/pkg/metrics/util.go
  backend/pkg/metrics/util_test.go
  backend/services/mgmt/v1alpha1/integration_tests/integration_test.go
  backend/services/mgmt/v1alpha1/metrics-service/metrics.go
  backend/services/mgmt/v1alpha1/metrics-service/metrics_test.go
  internal/mocks/github.com/prometheus/client_golang/api/prometheus/v1/mock_API.go
Labels: enhancement

#2736 NEOS-1476: send usage metrics to stripe for billing
  backend/gen/go/db/mock_Querier.go
  backend/gen/go/db/querier.go
  backend/gen/go/db/users.sql.go
  backend/gen/go/protos/mgmt/v1alpha1/mgmtv1alpha1connect/mock_UserAccountServiceClient.go
  backend/gen/go/protos/mgmt/v1alpha1/mgmtv1alpha1connect/user_account.connect.go
  backend/gen/go/protos/mgmt/v1alpha1/user_account.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/user_account.pb.validate.go
  backend/internal/auth/apikey/client.go
  backend/internal/cmds/mgmt/mgmt.go
  backend/internal/cmds/mgmt/run/run.go
  backend/internal/cmds/mgmt/run/stripe-usage/cmd.go
  backend/internal/cmds/mgmt/run/stripe-usage/cmd_test.go
  backend/internal/cmds/mgmt/serve/connect/cmd.go
  backend/protos/mgmt/v1alpha1/user_account.proto
  backend/services/mgmt/v1alpha1/integration_tests/connection-service_integration_test.go
  backend/services/mgmt/v1alpha1/integration_tests/integration_test.go
  backend/services/mgmt/v1alpha1/integration_tests/integration_util_test.go
  backend/services/mgmt/v1alpha1/integration_tests/jobs-service_integration_test.go
  backend/services/mgmt/v1alpha1/integration_tests/user-account-service_integration_test.go
  backend/services/mgmt/v1alpha1/user-account-service/billing.go
  backend/sql/postgresql/queries/users.sql
  docs/protos/data/proto_docs.json
  frontend/packages/sdk/src/client/mgmt/v1alpha1/user_account-UserAccountService_connectquery.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/user_account_connect.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/user_account_pb.ts
  internal/billing/mock_Interface.go
  internal/billing/stripe-billing.go
Labels: enhancement

#2742 NEOS-1487 Adds source connection type to worker logs
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/activity.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/ai-generate.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/benthos-builder.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/benthos-builder_test.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/generate.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/sync-dynamodb.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/sync-mongo.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/sync.go
  worker/pkg/workflows/datasync/activities/run-sql-init-table-stmts/init-statement-builder.go
  worker/pkg/workflows/datasync/activities/shared/shared.go
  worker/pkg/workflows/datasync/workflow/workflow.go
Labels: Devex

#2745 Disable codecov github annotations
  codecov.yml
Labels: Devex

#2744 OpenTelemetry Updates for Worker, Stripe, Backend
  backend/internal/cmds/mgmt/run/stripe-usage/cmd.go
  backend/internal/cmds/mgmt/serve/connect/cmd.go
  internal/otel/otel.go
  worker/internal/cmds/worker/serve/serve.go
Labels: bug, enhancement

#2747 publish 926 changelog
  docs/blog/2024-09-26-revamped-bulk-transformer-support.md
Labels: documentation

#2748 update date in changelog docs
  docs/blog/2024-09-26-revamped-bulk-transformer-support.md
Labels: documentation

#2749 NEOS-1493 Fix Postgres and Mysql JSON marshaling
  internal/mysql/mysql.go
  internal/mysql/mysql_test.go
  internal/postgres/utils.go
  internal/postgres/utils_test.go
  worker/pkg/query-builder/query-builder.go
  worker/pkg/query-builder/query-builder_test.go
  worker/pkg/workflows/datasync/workflow/testdata/mysql/all-types/create.sql
  worker/pkg/workflows/datasync/workflow/testdata/mysql/all-types/insert.sql
  worker/pkg/workflows/datasync/workflow/testdata/mysql/all-types/job_mappings.go
  worker/pkg/workflows/datasync/workflow/testdata/mysql/all-types/tests.go
  worker/pkg/workflows/datasync/workflow/testdata/postgres/all-types/job_mappings.go
  worker/pkg/workflows/datasync/workflow/testdata/postgres/all-types/setup.sql
  worker/pkg/workflows/datasync/workflow/testdata/postgres/all-types/tests.go
Labels: bug

#2751 updates transformer fn values to allow retaining empty strings
  worker/pkg/benthos/transformers/transform_first_name.go
  worker/pkg/benthos/transformers/transform_first_name_test.go
  worker/pkg/benthos/transformers/transform_string.go
  worker/pkg/benthos/transformers/transform_string_phone_number.go
Labels: bug

#2753 NEOS-1496: move invite member button to heading
  frontend/apps/web/app/(mgmt)/[account]/settings/api-keys/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/settings/members/components/InviteTable.tsx
  frontend/apps/web/app/(mgmt)/[account]/settings/members/components/InviteUserForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/settings/members/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/settings/temporal/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/settings/usage/page.tsx
  frontend/apps/web/components/headers/SubPageHeader.tsx
Labels: bug

#2754 exposes simple version in support header
  backend/gen/go/protos/mgmt/v1alpha1/mgmtv1alpha1connect/user_account.connect.go
  backend/gen/go/protos/mgmt/v1alpha1/user_account.pb.go
  backend/protos/mgmt/v1alpha1/user_account.proto
  docs/protos/data/proto_docs.json
  frontend/apps/web/components/site-header/NeosyncVersion.tsx
  frontend/apps/web/components/site-header/SiteHeader.tsx
  frontend/packages/sdk/src/client/mgmt/v1alpha1/user_account-UserAccountService_connectquery.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/user_account_connect.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/user_account_pb.ts
Labels: enhancement

#2755 Fixes Backend Docker Build Arguments during CI builds
  .github/workflows/artifact-release.yml
  docker/Dockerfile.backend
Labels: Tech Debt

#2752 NEOS-1485: reduce workflow checkaccountstatus for paid accounts
  backend/gen/go/protos/mgmt/v1alpha1/user_account.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/user_account.pb.validate.go
  backend/protos/mgmt/v1alpha1/user_account.proto
  backend/services/mgmt/v1alpha1/integration_tests/user-account-service_integration_test.go
  backend/services/mgmt/v1alpha1/user-account-service/billing.go
  docs/protos/data/proto_docs.json
  frontend/packages/sdk/src/client/mgmt/v1alpha1/user_account_pb.ts
  worker/pkg/workflows/datasync/activities/account-status/activity.go
  worker/pkg/workflows/datasync/workflow/workflow.go
  worker/pkg/workflows/datasync/workflow/workflow_test.go
Labels: enhancement
