Repository nucleuscloud/neosync, pull requests merged in 2024-11, with the labels that each got.

#2893 Fix mysql date and datetime in CLI sync
  backend/pkg/dbconnect-config/mysql.go
  backend/pkg/dbconnect-config/mysql_test.go
  backend/pkg/sqlconnect/mock_SqlConnector.go
  backend/pkg/sqlconnect/sql-connector.go
  backend/services/mgmt/v1alpha1/connection-data-service/connection-data.go
  backend/services/mgmt/v1alpha1/connection-service/connection.go
  cli/internal/cmds/neosync/sync/job.go
  cli/internal/cmds/neosync/sync/sync.go
  cli/internal/cmds/neosync/sync/sync_integration_test.go
  internal/benthos/benthos-builder/benthos-builder.go
  internal/benthos/benthos-builder/builders/aws-s3.go
  internal/benthos/benthos-builder/builders/mongodb.go
  internal/testutil/testdata/mysql/alltypes/create-schema.sql
  internal/testutil/testdata/mysql/alltypes/create-tables.sql
  internal/testutil/testdata/mysql/alltypes/teardown.sql
  internal/testutil/testdata/mysql/humanresources/create-tables.sql
  internal/testutil/testdata/postgres/alltypes/create-tables.sql
  worker/pkg/benthos/config.go
  worker/pkg/benthos/environment/environment.go
  worker/pkg/benthos/json/sql_processor.go
Labels: bug

#2897 Refactors Temporal Client Manager to use cleaner interface
  .mockery.yml
  backend/internal/cmds/mgmt/serve/connect/cmd.go
  backend/internal/temporal/client-manager/manager-client.go
  backend/internal/temporal/client-manager/manager-client_test.go
  backend/internal/temporal/client-manager/mock_TemporalClientManagerClient.go
  backend/internal/temporal/clientmanager/cache.go
  backend/internal/temporal/clientmanager/client_factory.go
  backend/internal/temporal/clientmanager/config.go
  backend/internal/temporal/clientmanager/config_provider.go
  backend/internal/temporal/clientmanager/config_provider_test.go
  backend/internal/temporal/clientmanager/config_test.go
  backend/internal/temporal/clientmanager/manager.go
  backend/internal/temporal/clientmanager/mock_ConfigProvider.go
  backend/internal/temporal/clientmanager/mock_DB.go
  backend/internal/temporal/clientmanager/mock_Interface.go
  backend/pkg/integration-test/integration-test.go
  backend/services/mgmt/v1alpha1/integration_tests/jobs-service_integration_test.go
  backend/services/mgmt/v1alpha1/integration_tests/user-account-service_integration_test.go
  backend/services/mgmt/v1alpha1/job-service/jobs.go
  backend/services/mgmt/v1alpha1/job-service/jobs_test.go
  backend/services/mgmt/v1alpha1/job-service/runs.go
  backend/services/mgmt/v1alpha1/job-service/runs_test.go
  backend/services/mgmt/v1alpha1/job-service/service.go
  backend/services/mgmt/v1alpha1/user-account-service/account-temporal-config.go
  backend/services/mgmt/v1alpha1/user-account-service/service.go
Labels: Tech Debt

#2902 NEOS-1598: Updates Postgres Source Options to include New Column Addition Strategy
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/DataSyncConnectionCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/util.ts
  frontend/apps/web/app/(mgmt)/[account]/new/job/connect/page.tsx
  frontend/apps/web/components/jobs/Form/NewColumnAdditionStrategyOptionsForm.tsx
  frontend/apps/web/components/jobs/Form/PostgresDBSourceOptionsForm.tsx
  frontend/apps/web/components/jobs/Form/SourceOptionsForm.tsx
  frontend/apps/web/yup-validations/jobs.ts
Labels: enhancement

#2904 NEOS-1600: Adds docs for new column addition strategies
  docs/docs/deploy/environment-variables.md
  docs/docs/guides/new-column-addition-strategies.md
  docs/sidebars.ts
  frontend/apps/web/components/jobs/Form/NewColumnAdditionStrategyOptionsForm.tsx
Labels: Docs

#2908 Fixes many postgres and mysql types in CLI sync
  cli/internal/cmds/neosync/sync/sync_integration_test.go
  internal/benthos/benthos-builder/benthos-builder.go
  internal/benthos/benthos-builder/builders/sql.go
  internal/sqlserver/utils.go
  internal/sqlserver/utils_test.go
  internal/testutil/testdata/postgres/alltypes/create-tables.sql
  internal/testutil/utils.go
  worker/pkg/benthos/config.go
  worker/pkg/benthos/json/sql_processor.go
  worker/pkg/benthos/sql/output_sql_insert.go
  worker/pkg/query-builder/insert-query-builder.go
  worker/pkg/query-builder/query-builder.go
  worker/pkg/query-builder/query-builder_test.go
Labels: bug, Devex

#2909 NEOS-1601: update regex to allow multi word last names
  worker/pkg/benthos/transformers/transformer_initializer_test.go
Labels: bug

#2910 NEOS-1602: expose sql connection options in app
  docs/docs/connections/sqlserver.md
  docs/docs/guides/troubleshooting.md
  frontend/apps/web/app/(mgmt)/[account]/connections/[id]/components/MssqlForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/connections/[id]/components/MysqlForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/connections/[id]/components/PostgresForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/connections/[id]/components/connection-component.tsx
  frontend/apps/web/app/(mgmt)/[account]/connections/util.ts
  frontend/apps/web/app/(mgmt)/[account]/new/connection/mssql/MssqlForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/connection/mysql/MysqlForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/connection/postgres/PostgresForm.tsx
  frontend/apps/web/yup-validations/connections.ts
  frontend/apps/web/yup-validations/number.ts
Labels: enhancement

#2912 NEOS-1590: exposes batching config sql options in app
  frontend/apps/web/app/(mgmt)/[account]/connections/[id]/components/MssqlForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/util.ts
  frontend/apps/web/components/FormHeader.tsx
  frontend/apps/web/components/NumberedInput.tsx
  frontend/apps/web/components/jobs/Form/AwsS3DestinationOptionsForm.tsx
  frontend/apps/web/components/jobs/Form/DestinationOptionsForm.tsx
  frontend/apps/web/components/jobs/Form/MssqlDBDestinationOptionsForm.tsx
  frontend/apps/web/components/jobs/Form/MysqlDBDestinationOptionsForm.tsx
  frontend/apps/web/components/jobs/Form/PostgresDBDestinationOptionsForm.tsx
  frontend/apps/web/yup-validations/jobs.ts
Labels: enhancement

#2911 Fix S3 to SQL database types
  cli/internal/cmds/neosync/sync/sync_integration_test.go
  internal/benthos/benthos-builder/builders/sql.go
  internal/testutil/utils.go
  worker/pkg/benthos/config.go
  worker/pkg/benthos/environment/environment.go
  worker/pkg/benthos/sql/json_processor.go
  worker/pkg/benthos/sql/json_processor_test.go
Labels: bug

#2907 NEOS-1596: add in ip address transformer to backend, worker
  backend/gen/go/protos/mgmt/v1alpha1/transformer.pb.go
  backend/protos/mgmt/v1alpha1/transformer.proto
  backend/services/mgmt/v1alpha1/transformers-service/system_transformers.go
  backend/sql/postgresql/models/transformers.go
  docs/docs/transformers/gen-javascript-transformer.md
  docs/openapi/mgmt/v1alpha1/anonymization.openapi.yaml
  docs/openapi/mgmt/v1alpha1/job.openapi.yaml
  docs/openapi/mgmt/v1alpha1/transformer.openapi.yaml
  docs/protos/mgmt/v1alpha1/transformer.proto.mdx
  docs/protos/proto_docs.json
  frontend/apps/web/@types/neosync-transformers.d.ts
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateIpAddressForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformerForm.tsx
  frontend/apps/web/util/util.ts
  frontend/apps/web/yup-validations/transformer-validations.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/transformer_pb.ts
  internal/benthos/benthos-builder/builders/processors.go
  python/src/neosync/mgmt/v1alpha1/transformer_pb2.py
  python/src/neosync/mgmt/v1alpha1/transformer_pb2.pyi
  worker/pkg/benthos/transformers/gen_generate_ip_address.go
  worker/pkg/benthos/transformers/gen_neosync_transformers.go
  worker/pkg/benthos/transformers/generate_ip_address.go
  worker/pkg/benthos/transformers/generate_ip_address_test.go
  worker/pkg/benthos/transformers/transformer_initializer.go
  worker/pkg/benthos/transformers/transformer_initializer_test.go
Labels: Feature

#2914 adds ability to disable charts in helm umbrella chart
  charts/neosync/Chart.yaml
  charts/neosync/README.md
  charts/neosync/values.yaml
Labels: enhancement

#2916 NEOS-1603: add in 11-07 changelog
  docs/blog/2024-11-07-column-strategy.md
Labels: Docs

#2918 NEOS-1604: fixes dest opt batch dto to handle fallback
  backend/sql/postgresql/models/models.go
Labels: enhancement

#2925 NEOS-1606: update frontend to properly handle dest opts
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/destinations/components/DestinationConnectionCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/util.ts
  frontend/apps/web/app/(mgmt)/[account]/new/job/[id]/destination/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/aigenerate/single/connect/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/connect/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/generate/single/connect/page.tsx
  frontend/apps/web/components/jobs/Form/MssqlDBDestinationOptionsForm.tsx
  frontend/apps/web/components/jobs/Form/MysqlDBDestinationOptionsForm.tsx
  frontend/apps/web/components/jobs/Form/PostgresDBDestinationOptionsForm.tsx
Labels: bug

#2926 Fix CLI sync postgres uuid being incorrect
  internal/benthos/benthos-builder/builders/sql.go
  worker/pkg/benthos/dynamodb/output.go
  worker/pkg/benthos/sql/json_processor.go
Labels: bug, CLI

#2931 NEOS-1611: exposes neosync cloud option for worker, adds EE license to worker
  charts/neosync/README.md
  worker/charts/worker/README.md
  worker/charts/worker/templates/env-vars.yaml
  worker/charts/worker/values.yaml
  worker/internal/cmds/worker/serve/serve.go
Labels: enhancement

#2932 NEOS-1610: add eu ip addresses to docs
  docs/docs/guides/neosync-ip-ranges.md
Labels: Docs

#2933 sets versioning strat on frontend to force package updates
  .github/dependabot.yml
Labels: Tech Debt, ignore-for-release

#2927 NEOS-1609: update ip addres function to handle ipv4 and ipv6 byte ranges correctly
  worker/pkg/benthos/transformers/generate_ip_address.go
  worker/pkg/benthos/transformers/generate_ip_address_test.go
Labels: bug

#2924 Add init schema support for SQL Server in worker
  backend/pkg/mssql-querier/mock_Querier.go
  backend/pkg/mssql-querier/querier.go
  backend/pkg/mssql-querier/system.sql.go
  backend/pkg/sqlmanager/mssql/integration_test.go
  backend/pkg/sqlmanager/mssql/mssql-manager.go
  backend/pkg/sqlmanager/mssql/mssql-manager_integration_test.go
  backend/pkg/sqlmanager/mssql/mssql-manager_test.go
  backend/pkg/sqlmanager/mssql/testdata/dest-setup/001.sql
  backend/pkg/sqlmanager/mssql/testdata/dest-setup/002.sql
  backend/pkg/sqlmanager/mssql/testdata/source-setup/001.sql
  backend/pkg/sqlmanager/mssql/testdata/source-setup/002.sql
  backend/pkg/sqlmanager/mssql/testdata/source-setup/003.sql
  backend/pkg/sqlmanager/mssql/testdata/source-setup/004.sql
  backend/pkg/sqlmanager/mssql/testdata/source-setup/005.sql
  backend/pkg/sqlmanager/mssql/testdata/source-setup/006.sql
  backend/pkg/sqlmanager/mssql/testdata/source-setup/007.sql
  backend/pkg/sqlmanager/mssql/testdata/source-setup/008.sql
  backend/pkg/sqlmanager/shared/types.go
  frontend/apps/web/components/jobs/Form/MssqlDBDestinationOptionsForm.tsx
  internal/ee/mssql-manager/ee-mssql-manager.go
  internal/ee/mssql-manager/ee-mssql-manager_test.go
  internal/ee/mssql-manager/generate-sql.go
  internal/testutil/testcontainers/sqlserver/sqlserver.go
  worker/internal/cmds/worker/serve/serve.go
  worker/pkg/workflows/datasync/activities/run-sql-init-table-stmts/activity.go
  worker/pkg/workflows/datasync/activities/run-sql-init-table-stmts/init-statement-builder.go
  worker/pkg/workflows/datasync/activities/run-sql-init-table-stmts/init-statement-builder_test.go
  worker/pkg/workflows/datasync/workflow/testdata/mssql/simple/tests.go
  worker/pkg/workflows/datasync/workflow/workflow_integration_test.go
Labels: Feature

#2938 Fix SQL Server truncate tables order
  worker/pkg/workflows/datasync/activities/run-sql-init-table-stmts/init-statement-builder.go
  worker/pkg/workflows/datasync/workflow/testdata/mssql/simple/create-table.sql
Labels: bug

#2940 Fixes some S3 to Postgres types
  internal/testutil/testdata/postgres/alltypes/create-tables.sql
  worker/pkg/benthos/sql/json_processor.go
Labels: bug

#2941 Fix S3 to Postgres arrays
  worker/pkg/benthos/sql/json_processor.go
Labels: bug

#2951 Fixes REDIS values never being unset, allows disabling backend migrations init container in helm charts
  backend/charts/api/README.md
  backend/charts/api/templates/deployment.yaml
  backend/charts/api/values.yaml
  charts/neosync/README.md
  worker/charts/worker/templates/env-vars.yaml
Labels: bug, enhancement, Helm

#2954 Fixes Postgres jsonb in CLI sync
  cli/internal/cmds/neosync/sync/sync.go
  internal/postgres/utils.go
  worker/pkg/benthos/sql/json_processor.go
Labels: bug

#2955 Adds accountid unary interceptor to backend
  backend/internal/cmds/mgmt/serve/connect/cmd.go
  backend/internal/connect/interceptors/accountid/interceptor.go
  backend/internal/connect/interceptors/accountid/interceptor_test.go
  backend/pkg/logger/logger.go
  backend/services/mgmt/v1alpha1/job-service/jobs.go
  go.mod
  go.sum
Labels: enhancement

#2958 Moves bookend logger lower in mw stack to benefit from more attrs
  backend/internal/cmds/mgmt/serve/connect/cmd.go
  backend/internal/connect/interceptors/bookend/interceptor.go
  backend/internal/connect/interceptors/bookend/interceptor_test.go
Labels: enhancement

#2944 Introducing Neosync Guru on Gurubase.io
  README.md
Labels: documentation

#2961 Change info log to debug in post table sync activity
  worker/pkg/workflows/datasync/activities/post-table-sync/activity.go
Labels: Devex

#2965 Fixes Postgres money and xml arrays in sync
  internal/postgres/utils.go
  internal/postgres/utils_test.go
  worker/pkg/benthos/sql/json_processor.go
Labels: bug, Devex

#2960 NEOS-1618: Fixes IP Address Form, FK Col Rendering, JM Table Perf
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/DataGenConnectionCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/DataSyncConnectionCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/useOnApplyDefaultClick.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/useOnImportMappings.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/util.ts
  frontend/apps/web/app/(mgmt)/[account]/new/job/generate/single/schema/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/schema/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateIpAddressForm.tsx
  frontend/apps/web/components/jobs/JobMappingTable/AttributesCell.tsx
  frontend/apps/web/components/jobs/JobMappingTable/Columns.tsx
  frontend/apps/web/components/jobs/JobMappingTable/ConstraintsCell.tsx
  frontend/apps/web/components/jobs/JobMappingTable/DataTypeCell.tsx
  frontend/apps/web/components/jobs/JobMappingTable/IndeterminateCheckbox.tsx
  frontend/apps/web/components/jobs/JobMappingTable/JobMappingTable.tsx
  frontend/apps/web/components/jobs/NosqlTable/AddNewNosqlRecord.tsx
  frontend/apps/web/components/jobs/NosqlTable/EditCollection.tsx
  frontend/apps/web/components/jobs/NosqlTable/EditDocumentKey.tsx
  frontend/apps/web/components/jobs/NosqlTable/NosqlTable.tsx
  frontend/apps/web/components/jobs/SchemaTable/AiSchemaColumns.tsx
  frontend/apps/web/components/jobs/SchemaTable/RowAlert.tsx
  frontend/apps/web/components/jobs/SchemaTable/SchemaColumnHeader.tsx
  frontend/apps/web/components/jobs/SchemaTable/SchemaColumns.tsx
  frontend/apps/web/components/jobs/SchemaTable/SchemaPageTable.tsx
  frontend/apps/web/components/jobs/SchemaTable/SchemaTable.tsx
  frontend/apps/web/components/jobs/SchemaTable/SchemaTableToolBar.tsx
  frontend/apps/web/components/jobs/SchemaTable/TransformerSelect.tsx
  frontend/apps/web/components/jobs/SchemaTable/schema-constraint-handler.ts
  frontend/apps/web/components/jobs/SchemaTable/transformer-handler.ts
  frontend/apps/web/components/jobs/SchemaTable/useOnExportMappings.tsx
  frontend/apps/web/components/jobs/SchemaTable/util.ts
  frontend/apps/web/components/labels/LearnMoreLink.tsx
  frontend/apps/web/util/util.ts
  frontend/apps/web/yup-validations/transformer-validations.ts
Labels: bug, Tech Debt

#2968 NEOS-1628: Optimizes Bulk Set and Apply Default
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/DataGenConnectionCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/DataSyncConnectionCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/useOnApplyDefaultClick.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/useOnTransformerBulkUpdateClick.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/generate/single/schema/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/schema/page.tsx
  frontend/apps/web/components/jobs/SchemaTable/ApplyDefaultTransformersButton.tsx
Labels: Devex

#2970 NEOS-1631: reduce constraint text
  frontend/apps/web/components/jobs/JobMappingTable/Columns.tsx
  frontend/apps/web/components/jobs/JobMappingTable/ConstraintsCell.tsx
Labels: enhancement

#2971 NEOS-1625: updates temporal schedule errors to be unique
  backend/services/mgmt/v1alpha1/job-service/jobs.go
Labels: bug

#2973 NEOS-1633:changelog for 11-21
  docs/blog/2024-11-07-column-strategy copy.md
  docs/blog/2024-11-21-eu-infrastructure.md
Labels: Docs

#2975 NEOS-1634: Fixes AnonymizeSingle nil pointer exception on error
  backend/dev/build/Dockerfile.dev
  backend/internal/cmds/mgmt/serve/connect/cmd.go
  backend/services/mgmt/v1alpha1/anonymization-service/anonymization.go
  worker/dev/build/Dockerfile.dev
Labels: bug

#2977 Tidies up backend and worker logging
  backend/internal/dtomaps/job-runs.go
  backend/services/mgmt/v1alpha1/connection-data-service/connection-data.go
  backend/services/mgmt/v1alpha1/job-service/jobs.go
  backend/services/mgmt/v1alpha1/job-service/runs.go
  backend/services/mgmt/v1alpha1/transformers-service/system_transformers.go
  backend/services/mgmt/v1alpha1/transformers-service/userdefined_transformers.go
  worker/pkg/benthos/openai_generate/openai_generate.go
  worker/pkg/workflows/datasync/activities/sync-redis-clean-up/activity.go
Labels: Devex

#2978 NEOS-1638: fixes table styling
  frontend/apps/web/components/TruncatedText.tsx
  frontend/apps/web/components/jobs/JobMappingTable/Columns.tsx
  frontend/apps/web/components/jobs/JobMappingTable/JobMappingTable.tsx
  frontend/apps/web/util/util.ts
Labels: Devex

#2980 fixes worker dev dockerfile
  worker/dev/build/Dockerfile.dev
Labels: bug, ignore-for-release

#2982 NEOS-1639: [MIGRATION] adds JobHook with Pre and Post Sync Timing Support to API
  backend/gen/go/db/job-hooks.sql.go
  backend/gen/go/db/jobs.sql.go
  backend/gen/go/db/mock_Querier.go
  backend/gen/go/db/models.go
  backend/gen/go/db/querier.go
  backend/gen/go/protos/mgmt/v1alpha1/anonymization.pb.json.go
  backend/gen/go/protos/mgmt/v1alpha1/api_key.pb.json.go
  backend/gen/go/protos/mgmt/v1alpha1/auth.pb.json.go
  backend/gen/go/protos/mgmt/v1alpha1/connection.pb.json.go
  backend/gen/go/protos/mgmt/v1alpha1/connection_data.pb.json.go
  backend/gen/go/protos/mgmt/v1alpha1/job.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/job.pb.json.go
  backend/gen/go/protos/mgmt/v1alpha1/metrics.pb.json.go
  backend/gen/go/protos/mgmt/v1alpha1/mgmtv1alpha1connect/job.connect.go
  backend/gen/go/protos/mgmt/v1alpha1/mgmtv1alpha1connect/mock_JobServiceClient.go
  backend/gen/go/protos/mgmt/v1alpha1/mgmtv1alpha1connect/mock_JobServiceHandler.go
  backend/gen/go/protos/mgmt/v1alpha1/transformer.pb.json.go
  backend/gen/go/protos/mgmt/v1alpha1/user_account.pb.json.go
  backend/internal/cmds/mgmt/serve/connect/cmd.go
  backend/internal/dtomaps/job-hooks.go
  backend/internal/ee/LICENSE.md
  backend/internal/ee/hooks/jobs/service.go
  backend/internal/ee/hooks/jobs/user-account.go
  backend/internal/errors/errors.go
  backend/pkg/integration-test/integration-test.go
  backend/protos/mgmt/v1alpha1/job.proto
  backend/services/mgmt/v1alpha1/integration_tests/jobs-service_integration_test.go
  backend/services/mgmt/v1alpha1/job-service/hooks.go
  backend/services/mgmt/v1alpha1/job-service/service.go
  backend/sql/postgresql/queries/job-hooks.sql
  backend/sql/postgresql/queries/jobs.sql
  backend/sql/postgresql/schema/20241121225729_add-job-hooks.down.sql
  backend/sql/postgresql/schema/20241121225729_add-job-hooks.up.sql
  buf.gen.yaml
  docs/openapi/mgmt/v1alpha1/job.openapi.yaml
  docs/openapi/neosync.mgmt.v1alpha1.yaml
  docs/protos/mgmt/v1alpha1/job.proto.mdx
  docs/protos/proto_docs.json
  frontend/packages/sdk/src/client/mgmt/v1alpha1/job-JobService_connectquery.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/job_connect.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/job_pb.ts
  internal/connection-tunnel-manager/mock_ConnectionProvider.go
  internal/testutil/testcontainers/sqlserver/sqlserver.go
  python/src/neosync/mgmt/v1alpha1/job_pb2.py
  python/src/neosync/mgmt/v1alpha1/job_pb2.pyi
  python/src/neosync/mgmt/v1alpha1/job_pb2_grpc.py
  worker/pkg/workflows/datasync/workflow/integration_test.go
Labels: enhancement

#2991 NEOS-1643: Integrates JobHooks into Data Sync Workflow
  backend/internal/cmds/mgmt/serve/connect/cmd.go
  internal/ee/license/cascade.go
  internal/ee/license/cloud.go
  worker/internal/cmds/worker/serve/serve.go
  worker/pkg/workflows/datasync/activities/jobhooks-by-timing/activity.go
  worker/pkg/workflows/datasync/activities/jobhooks-by-timing/activity_test.go
  worker/pkg/workflows/datasync/activities/run-sql-init-table-stmts/activity.go
  worker/pkg/workflows/datasync/activities/run-sql-init-table-stmts/init-statement-builder.go
  worker/pkg/workflows/datasync/activities/run-sql-init-table-stmts/init-statement-builder_test.go
  worker/pkg/workflows/datasync/workflow/workflow.go
  worker/pkg/workflows/datasync/workflow/workflow_integration_test.go
Labels: enhancement

#2993 Neosync Interval and Interval Array type
  internal/benthos/benthos-builder/builders/sql.go
  internal/neosync-types/array.go
  internal/neosync-types/array_test.go
  internal/neosync-types/interval.go
  internal/neosync-types/interval_test.go
  internal/neosync-types/registry.go
  internal/neosync-types/registry_test.go
  internal/neosync-types/types.go
  internal/postgres/utils.go
  internal/testutil/testdata/postgres/alltypes/create-tables.sql
  worker/pkg/benthos/config.go
  worker/pkg/benthos/environment/environment.go
  worker/pkg/benthos/neosync_connection_data/neosync_connection_data_input.go
  worker/pkg/benthos/sql/json_processor.go
  worker/pkg/benthos/sql/processor_neosync_pgx.go
  worker/pkg/query-builder/insert-query-builder.go
  worker/pkg/query-builder/query-builder_test.go
  worker/pkg/workflows/datasync/workflow/testdata/javascript-transformers/tests.go
  worker/pkg/workflows/datasync/workflow/testdata/postgres/virtual-foreign-keys/tests.go
  worker/pkg/workflows/datasync/workflow/workflow_integration_test.go
Labels: enhancement, Improvement

#2996 Exposes language parameter in TransformPiiText
  backend/gen/go/protos/mgmt/v1alpha1/transformer.pb.go
  backend/internal/cmds/mgmt/serve/connect/cmd.go
  backend/protos/mgmt/v1alpha1/transformer.proto
  backend/services/mgmt/v1alpha1/anonymization-service/anonymization.go
  backend/services/mgmt/v1alpha1/anonymization-service/service.go
  docs/openapi/mgmt/v1alpha1/anonymization.openapi.yaml
  docs/openapi/mgmt/v1alpha1/job.openapi.yaml
  docs/openapi/mgmt/v1alpha1/transformer.openapi.yaml
  docs/openapi/neosync.mgmt.v1alpha1.yaml
  docs/protos/mgmt/v1alpha1/transformer.proto.mdx
  docs/protos/proto_docs.json
  frontend/packages/sdk/src/client/mgmt/v1alpha1/transformer_pb.ts
  internal/ee/transformers/functions/functions.go
  internal/json-anonymizer/json-anonymizer.go
  python/src/neosync/mgmt/v1alpha1/transformer_pb2.py
  python/src/neosync/mgmt/v1alpha1/transformer_pb2.pyi
  worker/pkg/benthos/transformers/transformer_initializer.go
  worker/pkg/benthos/transformers/transformer_initializer_test.go
Labels: enhancement
