Repository nucleuscloud/neosync, pull requests merged in 2024-07, with the labels that each got.

#2245 NEOS-1221 allow setting openai batch size
  backend/gen/go/protos/mgmt/v1alpha1/job.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/job.pb.validate.go
  backend/protos/mgmt/v1alpha1/job.proto
  backend/sql/postgresql/models/models.go
  docs/protos/data/proto_docs.json
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/AiDataGenConnectionCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/util.ts
  frontend/apps/web/app/(mgmt)/[account]/new/job/aigenerate/single/schema/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/schema.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/job_pb.ts
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/ai-generate.go
Labels: enhancement

#2246 Updates dependabot to allow minor npm prod dependency grouping
  .github/dependabot.yml
Labels: Devex

#2256 NEOS-1216 make neosync generators available in javascript transformer
  worker/pkg/benthos/javascript/functions.go
  worker/pkg/benthos/transformers/gen_generate_bool.go
  worker/pkg/benthos/transformers/gen_generate_card_number.go
  worker/pkg/benthos/transformers/gen_generate_categorical.go
  worker/pkg/benthos/transformers/gen_generate_city.go
  worker/pkg/benthos/transformers/gen_generate_email.go
  worker/pkg/benthos/transformers/gen_generate_first_name.go
  worker/pkg/benthos/transformers/gen_generate_float.go
  worker/pkg/benthos/transformers/gen_generate_full_address.go
  worker/pkg/benthos/transformers/gen_generate_full_name.go
  worker/pkg/benthos/transformers/gen_generate_gender.go
  worker/pkg/benthos/transformers/gen_generate_int64.go
  worker/pkg/benthos/transformers/gen_generate_int64_phone_number.go
  worker/pkg/benthos/transformers/gen_generate_international_phone_number.go
  worker/pkg/benthos/transformers/gen_generate_last_name.go
  worker/pkg/benthos/transformers/gen_generate_random_string.go
  worker/pkg/benthos/transformers/gen_generate_sha256hash.go
  worker/pkg/benthos/transformers/gen_generate_ssn.go
  worker/pkg/benthos/transformers/gen_generate_state.go
  worker/pkg/benthos/transformers/gen_generate_street_address.go
  worker/pkg/benthos/transformers/gen_generate_string_phone_number.go
  worker/pkg/benthos/transformers/gen_generate_unix_timestamp.go
  worker/pkg/benthos/transformers/gen_generate_username.go
  worker/pkg/benthos/transformers/gen_generate_utc_timestamp.go
  worker/pkg/benthos/transformers/gen_generate_uuid.go
  worker/pkg/benthos/transformers/gen_generate_zipcode.go
  worker/pkg/benthos/transformers/gen_neosync_transformers.go
  worker/pkg/benthos/transformers/generate_bool.go
  worker/pkg/benthos/transformers/generate_card_number.go
  worker/pkg/benthos/transformers/generate_categorical.go
  worker/pkg/benthos/transformers/generate_city.go
  worker/pkg/benthos/transformers/generate_email.go
  worker/pkg/benthos/transformers/generate_first_name.go
  worker/pkg/benthos/transformers/generate_float.go
  worker/pkg/benthos/transformers/generate_full_address.go
  worker/pkg/benthos/transformers/generate_full_name.go
  worker/pkg/benthos/transformers/generate_gender.go
  worker/pkg/benthos/transformers/generate_int64.go
  worker/pkg/benthos/transformers/generate_int64_phone_number.go
  worker/pkg/benthos/transformers/generate_international_phone_number.go
  worker/pkg/benthos/transformers/generate_last_name.go
  worker/pkg/benthos/transformers/generate_random_string.go
  worker/pkg/benthos/transformers/generate_sha256hash.go
  worker/pkg/benthos/transformers/generate_ssn.go
  worker/pkg/benthos/transformers/generate_state.go
  worker/pkg/benthos/transformers/generate_street_address.go
  worker/pkg/benthos/transformers/generate_string_phone_number.go
  worker/pkg/benthos/transformers/generate_unix_timestamp.go
  worker/pkg/benthos/transformers/generate_username.go
  worker/pkg/benthos/transformers/generate_utc_timestamp.go
  worker/pkg/benthos/transformers/generate_uuid.go
  worker/pkg/benthos/transformers/generate_zipcode.go
  worker/pkg/benthos/transformers/types.go
  worker/pkg/workflows/datasync/workflow/testdata/javascript-transformers/create.sql
  worker/pkg/workflows/datasync/workflow/testdata/javascript-transformers/tests.go
Labels: Feature

#2259 fixes db migrations docs nesting
  docs/docs/deploy/kubernetes.md
Labels: documentation

#2260 NEOS-1198, NEOS-1225 Adds sidecars to helm charts, adds auth trust host, updates helm docs
  README.md
  backend/charts/api/README.md
  backend/charts/api/templates/deployment.yaml
  backend/charts/api/values.yaml
  charts/neosync/README.md
  docs/docs/deploy/environment-variables.md
  docs/docs/deploy/kubernetes.md
  frontend/apps/web/charts/app/README.md
  frontend/apps/web/charts/app/templates/app-env-vars.yaml
  frontend/apps/web/charts/app/templates/deployment.yaml
  frontend/apps/web/charts/app/values.yaml
  worker/charts/worker/README.md
  worker/charts/worker/templates/deployment.yaml
  worker/charts/worker/values.yaml
Labels: enhancement

#2265 NEOS-1227 Fix building run configs for single table sync with dependencies
  backend/pkg/table-dependency/table-dependency.go
  backend/pkg/table-dependency/table-dependency_test.go
Labels: bug

#2276 Fix postgres init schema sequences not working
  backend/gen/go/db/dbschemas/postgresql/system.sql.go
  backend/pkg/dbschemas/sql/postgresql/queries/system.sql
  backend/pkg/sqlmanager/postgres/postgres-manager_integration_test.go
Labels: bug

#2291 NEOS-1235: fixes missing max connections on mysql clone
  frontend/apps/web/app/(mgmt)/[account]/new/connection/mysql/MysqlForm.tsx
Labels: bug

#2292 NEOS-1236 mysql and postgresql connections bugged when using connect by url
  frontend/apps/web/app/(mgmt)/[account]/connections/[id]/components/MysqlForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/connections/[id]/components/PostgresForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/connections/[id]/components/connection-component.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/connection/supabase/SupabaseLogo.tsx
  frontend/apps/web/components/providers/prism
  frontend/apps/web/components/providers/prism.svg
  frontend/apps/web/yup-validations/connections.ts
Labels: bug

#2293 updates github release to include more bug labels
  .github/release.yml
Labels: ignore-for-release

#2295 NEOS-1239 update buf to use authentication token
  backend/scripts/gen.sh
  docs/docs/guides/neosync-local-dev.md
Labels: ignore-for-release

#2296 Fix SQL query to retrieve MySQL foreign key constraints
  backend/gen/go/db/dbschemas/mysql/system.sql.go
  backend/pkg/dbschemas/sql/mysql/queries/system.sql
  backend/pkg/dbschemas/sql/mysql/schema/system.sql
  backend/pkg/sqlmanager/mysql/mysql-manager.go
  worker/pkg/workflows/datasync/workflow/workflow.go
Labels: bug

#2302 Updates getJobRunLogs hook to use Tanstack Query
  frontend/apps/web/app/(mgmt)/[account]/runs/[id]/components/JobRunLogs.tsx
  frontend/apps/web/libs/hooks/useGetJobRunLogs.ts
  frontend/apps/web/libs/utils.ts
Labels: Devex, Tech Debt

#2303 NEOS-1243: Moves GetConnectionSchemaMap to Go API and replaces SWR Hook
  backend/gen/go/protos/mgmt/v1alpha1/connection_data.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/connection_data.pb.validate.go
  backend/gen/go/protos/mgmt/v1alpha1/mgmtv1alpha1connect/connection_data.connect.go
  backend/protos/mgmt/v1alpha1/connection_data.proto
  backend/services/mgmt/v1alpha1/connection-data-service/connection-data.go
  docs/protos/data/proto_docs.json
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/AiDataGenConnectionCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/DataGenConnectionCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/DataSyncConnectionCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/util.ts
  frontend/apps/web/app/(mgmt)/[account]/new/job/aigenerate/single/schema/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/generate/single/schema/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/schema/page.tsx
  frontend/apps/web/app/api/accounts/[accountId]/connections/[id]/schema/map/route.ts
  frontend/apps/web/components/jobs/NosqlTable/NosqlTable.tsx
  frontend/apps/web/components/jobs/SchemaTable/AiSchemaTable.tsx
  frontend/apps/web/components/jobs/SchemaTable/SchemaTable.tsx
  frontend/apps/web/components/jobs/SchemaTable/VirtualForeignKeyForm.tsx
  frontend/apps/web/components/jobs/SchemaTable/schema-constraint-handler.ts
  frontend/apps/web/libs/hooks/types.ts
  frontend/apps/web/libs/hooks/useGenericErrorToast.ts
  frontend/apps/web/libs/hooks/useGetConnectionSchemaMap.ts
  frontend/apps/web/libs/hooks/useGetJobRunLogs.ts
  frontend/apps/web/libs/hooks/useNucleusAuthenticatedFetch.ts
  frontend/apps/web/package.json
  frontend/package-lock.json
  frontend/packages/sdk/src/client/mgmt/v1alpha1/connection_data-ConnectionDataService_connectquery.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/connection_data_connect.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/connection_data_pb.ts
Labels: Improvement, Tech Debt

#2309 NEOS-1243: Updates Yup Validation Hooks to use Tanstack Mutations
  frontend/apps/web/app/(mgmt)/[account]/connections/[id]/components/AwsS3Form.tsx
  frontend/apps/web/app/(mgmt)/[account]/connections/[id]/components/GcpCloudStorageForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/connections/[id]/components/MongoDbForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/connections/[id]/components/MysqlForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/connections/[id]/components/OpenAiForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/connections/[id]/components/PostgresForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/connections/util.ts
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/DataGenConnectionCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/DataSyncConnectionCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/util.ts
  frontend/apps/web/app/(mgmt)/[account]/new/connection/aws-s3/AwsS3Form.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/connection/gcp-cloud-storage/GcpCloudStorageForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/connection/mongodb/MongoDBForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/connection/mysql/MysqlForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/connection/openai/OpenAiForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/connection/postgres/PostgresForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/define/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/generate/single/schema/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/schema.ts
  frontend/apps/web/app/(mgmt)/[account]/new/job/schema/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedGenerateCardNumber.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedGenerateCategoricalForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedGenerateEmailForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedGenerateFloat64Form.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedGenerateGenderForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedGenerateInt64Form.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedGenerateInternationalPhoneNumberForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedGenerateJavascriptForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedGenerateStringForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedGenerateStringPhoneNumberForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedGenerateUuidForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedTransformCharacterScrambleForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedTransformE164PhoneNumberForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedTransformEmailForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedTransformFirstNameForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedTransformFloat64Form.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedTransformFullNameForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedTransformInt64Form.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedTransformInt64PhoneForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedTransformJavascriptForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedTransformLastNameForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedTransformPhoneNumberForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedTransformStringForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/schema.ts
  frontend/apps/web/app/(mgmt)/[account]/transformers/Sheetforms/GenerateJavascriptForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/Sheetforms/TransformJavascriptForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/[id]/components/UpdateUserDefinedTransformerForm.tsx
  frontend/apps/web/app/api/accounts/[accountId]/connections/is-connection-name-available/route.ts
  frontend/apps/web/app/api/accounts/[accountId]/jobs/is-job-name-available/route.ts
  frontend/apps/web/app/api/accounts/[accountId]/jobs/validate-mappings/route.ts
  frontend/apps/web/app/api/accounts/[accountId]/transformers/is-transformer-name-available/route.ts
  frontend/apps/web/app/api/accounts/[accountId]/transformers/user-defined/validate-code/route.ts
  frontend/apps/web/libs/requests/validateJobMappings.ts
  frontend/apps/web/yup-validations/connections.ts
Labels: Devex, Tech Debt

#2310 Removes got usage from frontend in favor of fetch
  frontend/apps/web/app/api/webhooks/keycloak/slack/route.ts
  frontend/apps/web/package.json
  frontend/package-lock.json
Labels: dependencies, Tech Debt

#2306 workflow: add github action for checking pr label
  .github/workflows/pull-request.yml
Labels: ignore-for-release

#2317 Fix javascript transformer docs examples
  docs/.prettierignore
  docs/docs/transformers/gen-javascript-transformer.md
  docs/protos/mgmt/v1alpha1/connection_data.proto.mdx
  worker/pkg/benthos/transformers/neosync_js_transformer_docs_generator.go
Labels: Docs

#2323 NEOS-1252: Update Generate State transformer to support returning back a 2-letter state code or the full state name
  backend/gen/go/protos/mgmt/v1alpha1/transformer.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/transformer.pb.validate.go
  backend/protos/mgmt/v1alpha1/transformer.proto
  backend/services/mgmt/v1alpha1/transformers-service/system_transformers.go
  backend/sql/postgresql/models/transformers.go
  docs/docs/transformers/gen-javascript-transformer.md
  docs/docs/transformers/system.md
  docs/protos/data/proto_docs.json
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedGenerateStateForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedTransformerForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/schema.ts
  frontend/apps/web/app/(mgmt)/[account]/transformers/EditTransformerOptions.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/Sheetforms/GenerateStateForm.tsx
  frontend/packages/sdk/src/client/mgmt/v1alpha1/transformer_pb.ts
  worker/pkg/benthos/transformers/data-sets/states.go
  worker/pkg/benthos/transformers/gen_generate_state.go
  worker/pkg/benthos/transformers/generate_full_address.go
  worker/pkg/benthos/transformers/generate_state.go
  worker/pkg/benthos/transformers/generate_state_test.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/benthos-builder_test.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/processors.go
Labels: Improvement

#2330 updated changelog
  docs/blog/2024-07-04-job-cloning.md
  docs/blog/2024-07-18-transformers-in-javascript.md
Labels: Docs

#2335 Fix sync with circular dependency and primary key transformation
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/benthos-builder.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/benthos-builder_test.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/processors.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/sync-mongo.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/sync.go
  worker/pkg/workflows/datasync/workflow/testdata/gen-jobmappings-config.json
  worker/pkg/workflows/datasync/workflow/testdata/primary-key-transformer/create.sql
  worker/pkg/workflows/datasync/workflow/testdata/primary-key-transformer/insert.sql
  worker/pkg/workflows/datasync/workflow/testdata/primary-key-transformer/job_mappings.go
  worker/pkg/workflows/datasync/workflow/testdata/primary-key-transformer/teardown.sql
  worker/pkg/workflows/datasync/workflow/testdata/primary-key-transformer/tests.go
  worker/pkg/workflows/datasync/workflow/workflow.go
  worker/pkg/workflows/datasync/workflow/workflow_integration_test.go
Labels: bug

#2336 Run worker integration tests in parallel
  worker/pkg/workflows/datasync/workflow/integration_test.go
  worker/pkg/workflows/datasync/workflow/workflow_integration_test.go
Labels: Devex

#2334 NEOS-1259 adds benthos dynamodb input connector
  .mockery.yml
  go.mod
  worker/pkg/benthos/dynamodb/input.go
  worker/pkg/benthos/dynamodb/input_test.go
  worker/pkg/benthos/dynamodb/mock_dynamoDBAPIV2.go
  worker/pkg/benthos/environment/environment.go
  worker/pkg/workflows/datasync/activities/sync/mock_BenthosStreamManagerClient.go
Labels: enhancement

#2343 Mysql composite key integration test
  worker/pkg/workflows/datasync/workflow/testdata/gen-jobmappings-config.json
  worker/pkg/workflows/datasync/workflow/testdata/mysql/composite-keys/create.sql
  worker/pkg/workflows/datasync/workflow/testdata/mysql/composite-keys/insert.sql
  worker/pkg/workflows/datasync/workflow/testdata/mysql/composite-keys/job_mappings.go
  worker/pkg/workflows/datasync/workflow/testdata/mysql/composite-keys/teardown.sql
  worker/pkg/workflows/datasync/workflow/testdata/mysql/composite-keys/tests.go
  worker/pkg/workflows/datasync/workflow/workflow_integration_test.go
Labels: Tech Debt

#2345 Increase test container timeout
  worker/pkg/workflows/datasync/workflow/integration_test.go
Labels: bug

#2227 Increase workflow integration test timeout
  worker/pkg/workflows/datasync/workflow/workflow_integration_test.go
Labels: bug

#2341 NEOS-1265: expose dynamodb as connection
  .mockery.yml
  backend/gen/go/protos/mgmt/v1alpha1/connection.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/connection.pb.validate.go
  backend/internal/aws/aws-manager.go
  backend/internal/cmds/mgmt/serve/connect/cmd.go
  backend/protos/mgmt/v1alpha1/connection.proto
  backend/services/mgmt/v1alpha1/connection-data-service/connection-data_test.go
  backend/services/mgmt/v1alpha1/connection-data-service/service.go
  backend/services/mgmt/v1alpha1/connection-service/connection.go
  backend/services/mgmt/v1alpha1/connection-service/connection_test.go
  backend/services/mgmt/v1alpha1/connection-service/service.go
  backend/sql/postgresql/models/models.go
  docs/protos/data/proto_docs.json
  frontend/apps/web/app/(mgmt)/[account]/connections/[id]/components/DynamoDBForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/connections/[id]/components/connection-component.tsx
  frontend/apps/web/app/(mgmt)/[account]/connections/[id]/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/connections/[id]/permissions/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/connections/components/ConnectionsTable/columns.tsx
  frontend/apps/web/app/(mgmt)/[account]/connections/util.ts
  frontend/apps/web/app/(mgmt)/[account]/new/connection/dynamodb/DynamoDBForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/connection/dynamodb/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/connection/page.tsx
  frontend/apps/web/app/api/config/config.ts
  frontend/apps/web/app/config/app-config.ts
  frontend/apps/web/components/connections/ConnectionIcon.tsx
  frontend/apps/web/components/permissions/PermissionsDialog.tsx
  frontend/apps/web/components/permissions/columns.tsx
  frontend/apps/web/yup-validations/connections.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/connection_pb.ts
  internal/aws/aws-manager.go
  internal/aws/dynamodb-client.go
  internal/aws/dynamodb-client_test.go
  internal/aws/mock_NeosyncAwsManagerClient.go
  internal/aws/mock_dynamoDBAPIV2.go
  worker/pkg/benthos/dynamodb/input.go
Labels: enhancement

#2347 fixes broken docker images by adding missing internal folder
  docker/Dockerfile.backend
  docker/Dockerfile.worker
Labels: bug, ignore-for-release

#2349 Add permissions to mysql form
  frontend/apps/web/app/(mgmt)/[account]/connections/[id]/components/MysqlForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/connections/[id]/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/connection/mysql/MysqlForm.tsx
Labels: enhancement, Mysql

#2353 add public roadmap link to git repo
  README.md
Labels: documentation

#2354 NEOS-1257, NEOS-1256, NEOS-1261: fix some minor styling updates in the Neosync app
  frontend/apps/web/app/(mgmt)/[account]/transformers/Sheetforms/GenerateJavascriptForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/Sheetforms/TransformJavascriptForm.tsx
  frontend/apps/web/components/ButtonText.tsx
  frontend/apps/web/components/jobs/subsets/EditItem.tsx
Labels: Improvement

#2366 NEOS-1274: add dynamodb table mappings to new destination flow form
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/destinations/components/DestinationConnectionCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/[id]/destination/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/aigenerate/single/connect/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/connect/ConnectionSelectContent.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/connect/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/generate/single/connect/page.tsx
  frontend/apps/web/components/jobs/Form/DestinationOptionsForm.tsx
  frontend/apps/web/components/jobs/NosqlTable/NosqlTable.tsx
  frontend/apps/web/components/jobs/NosqlTable/TableMappings/TableMappingsCard.tsx
Labels: enhancement

#2355 added 'temporal-network' network and changed temporalio/admin-tools
  compose.yml
Labels: Devex, ignore-for-release

#2369 NEOS-1275 add dynamodb worker integration test
  .github/workflows/go.yml
  go.mod
  go.sum
  internal/aws/aws-manager.go
  worker/pkg/workflows/datasync/workflow/integration_test.go
  worker/pkg/workflows/datasync/workflow/workflow_integration_test.go
Labels: ignore-for-release

#2371 NEOS-1277: updates destination card to use confirmation dialog when deleting destination
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/destinations/components/DestinationConnectionCard.tsx
Labels: enhancement

#2372 NEOS-1263: add adopters list
  ADOPTERS.md
Labels: documentation

#2373 add markdown headers to adopters list
  ADOPTERS.md
Labels: documentation

#2374 Update ADOPTERS.md
  ADOPTERS.md
Labels: documentation

#2377 NEOS-1279 disallow switching to invalid destinations
  backend/services/mgmt/v1alpha1/job-service/jobs.go
  frontend/apps/web/app/(mgmt)/[account]/connections/[id]/components/connection-component.tsx
  frontend/apps/web/app/(mgmt)/[account]/connections/util.ts
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/destinations/components/DestinationConnectionCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/destinations/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/connection/components/ConnectionCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/connection/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/[id]/destination/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/aigenerate/single/connect/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/connect/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/generate/single/connect/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/schema.ts
  frontend/apps/web/components/connections/ConnectionIcon.tsx
Labels: enhancement, Fast Follow

#2382 NEOS-1285: fixes connection clone button redirect
  frontend/apps/web/app/(mgmt)/[account]/connections/components/ConnectionsTable/data-table-row-actions.tsx
  frontend/apps/web/app/(mgmt)/[account]/connections/util.ts
  frontend/apps/web/app/(mgmt)/[account]/new/connection/components/ConnectionCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/connection/page.tsx
  frontend/apps/web/components/CloneConnectionButton.tsx
Labels: bug, Regression

#2383 NEOS-1278 add dynamodb local compose for local development
  compose.dev.yml
  compose/README.md
  compose/compose-db-dynamo.yml
Labels: ignore-for-release
