Repository nucleuscloud/neosync, pull requests merged in 2024-08, with the labels that each got.

#2386 NEOS-1290: updates benthos dynamodb input to use partiql instead of scan
  worker/pkg/benthos/dynamodb/input.go
  worker/pkg/benthos/dynamodb/input_test.go
  worker/pkg/benthos/dynamodb/mock_dynamoDBAPIV2.go
Labels: enhancement, Fast Follow

#2387 adds codecov ignore for backend gen code
  codecov.yml
Labels: ignore-for-release

#2385 NEOS-1288 add subsetting to dynamodb backend/worker
  backend/gen/go/protos/mgmt/v1alpha1/job.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/job.pb.validate.go
  backend/protos/mgmt/v1alpha1/job.proto
  backend/sql/postgresql/models/models.go
  docs/protos/data/proto_docs.json
  frontend/packages/sdk/src/client/mgmt/v1alpha1/job_pb.ts
  worker/pkg/benthos/config.go
  worker/pkg/benthos/dynamodb/input.go
  worker/pkg/benthos/dynamodb/input_test.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/benthos-builder.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/sync-dynamodb.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/sync-dynamodb_test.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/sync.go
  worker/pkg/workflows/datasync/workflow/workflow_integration_test.go
Labels: enhancement

#2388 NEOS-1272 Add neosync transformers auto complete to javascript transformer
  frontend/apps/web/@types/neosync-transformers.d.ts
  frontend/apps/web/app/(mgmt)/[account]/transformers/Sheetforms/GenerateJavascriptForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/Sheetforms/TransformJavascriptForm.tsx
  frontend/apps/web/app/api/files/neosync-transformer-declarations/route.ts
  frontend/apps/web/libs/hooks/useReadNeosyncTransfomerDeclarationFile.ts
  frontend/apps/web/tsconfig.json
  worker/pkg/benthos/transformers/generator_utils.go
  worker/pkg/benthos/transformers/generators.go
  worker/pkg/benthos/transformers/neosync_js_transformer_docs_generator.go
  worker/pkg/benthos/transformers/neosync_transformer_list_generator.go
  worker/pkg/benthos/transformers/neosync_transformer_typescript_declaration_generator.go
Labels: Improvement

#2390 Fix neosync transformer declaration file path
  frontend/apps/web/app/(mgmt)/[account]/transformers/Sheetforms/TransformJavascriptForm.tsx
  frontend/apps/web/app/api/files/neosync-transformer-declarations/route.ts
Labels: bug

#2392 NEOS-1294: Adds ability to configure resource reqs for app in helm chart
  backend/charts/api/values.yaml
  charts/neosync/README.md
  frontend/apps/web/charts/app/README.md
  frontend/apps/web/charts/app/templates/deployment.yaml
  frontend/apps/web/charts/app/values.yaml
  worker/charts/worker/values.yaml
Labels: enhancement

#2394 NEOS-1291 expose dynamodb subsetting to frontend app
  backend/gen/go/protos/mgmt/v1alpha1/job.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/job.pb.validate.go
  backend/internal/nucleusdb/jobs.go
  backend/internal/nucleusdb/jobs_test.go
  backend/pkg/sqlmanager/sql-manager.go
  backend/protos/mgmt/v1alpha1/job.proto
  backend/services/mgmt/v1alpha1/connection-data-service/connection-data.go
  backend/services/mgmt/v1alpha1/job-service/jobs.go
  backend/sql/postgresql/models/models.go
  docs/protos/data/proto_docs.json
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/layout.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/util.ts
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/subsets/components/SubsetCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/util.ts
  frontend/apps/web/app/(mgmt)/[account]/new/job/schema/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/subset/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/page.tsx
  frontend/apps/web/components/jobs/SchemaTable/StringSelect.tsx
  frontend/apps/web/components/jobs/SchemaTable/TransformerSelect.tsx
  frontend/apps/web/components/jobs/subsets/EditItem.tsx
  frontend/apps/web/components/jobs/subsets/utils.ts
  frontend/apps/web/components/site-header/AccountSwitcher.tsx
  frontend/apps/web/components/ui/command.tsx
  frontend/apps/web/components/ui/popover.tsx
  frontend/apps/web/package.json
  frontend/package-lock.json
  frontend/packages/sdk/src/client/mgmt/v1alpha1/job_pb.ts
Labels: enhancement

#2395 Fix neosync transformer declaration file generator
  docs/docs/transformers/gen-javascript-transformer.md
  frontend/apps/web/@types/neosync-transformers.d.ts
  worker/pkg/benthos/transformers/gen_generate_state.go
  worker/pkg/benthos/transformers/generate_state.go
  worker/pkg/benthos/transformers/neosync_transformer_typescript_declaration_generator.go
Labels: documentation, Improvement

#2397 NEOS-1296: unable to validate javascript transformers
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedGenerateJavascriptForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/schema.ts
  frontend/apps/web/app/(mgmt)/[account]/transformers/Sheetforms/GenerateJavascriptForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/Sheetforms/TransformJavascriptForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/[id]/components/UpdateUserDefinedTransformerForm.tsx
Labels: bug

#2405 NEOS-1297: adds ability to provide annotations on deployment and pod template in helm charts
  backend/charts/api/README.md
  backend/charts/api/templates/deployment.yaml
  backend/charts/api/values.yaml
  charts/neosync/README.md
  frontend/apps/web/charts/app/README.md
  frontend/apps/web/charts/app/templates/deployment.yaml
  frontend/apps/web/charts/app/values.yaml
  worker/charts/worker/README.md
  worker/charts/worker/templates/deployment.yaml
  worker/charts/worker/values.yaml
Labels: enhancement

#2411 update changelog
  docs/blog/2024-07-18-transformers-in-javascript copy.md
  docs/blog/2024-08-01-dynamodb.md
Labels: documentation

#2412 update changelog date
  docs/blog/2024-08-01-dynamodb.md
Labels: documentation

#2414 NEOS-1298: Fixes Benthos DynamoDB Input AWS Creds Parser
  worker/pkg/benthos/dynamodb/input.go
Labels: bug

#2416 NEOS-1293 Fix Benthos Type Loss for DynamoDB
  go.mod
  worker/pkg/benthos/dynamodb/input.go
  worker/pkg/benthos/dynamodb/input_test.go
  worker/pkg/benthos/dynamodb/output.go
  worker/pkg/benthos/environment/environment.go
  worker/pkg/workflows/datasync/activities/sync/activity.go
Labels: bug

#2420 NEOS-1300: add support for dynamodb key deep link for mutations
  backend/pkg/table-dependency/table-dependency.go
  frontend/apps/web/components/jobs/NosqlTable/NosqlTable.tsx
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/benthos-builder_test.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/generate.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/processors.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/sync-dynamodb.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/sync-mongo.go
Labels: bug, enhancement

#2422 NEOS-1307: updates js builder method to handle js paths
  backend/pkg/table-dependency/table-dependency.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/benthos-builder_test.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/processors.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/processors_test.go
Labels: enhancement

#2423 Adds DynamoDB Documentation
  docs/docs/connections/dynamodb.md
  docs/sidebars.ts
  docs/src/CustomComponents/IconHandler.tsx
Labels: documentation

#2427 NEOS-1295: moves seed to be deferred for transformations
  docs/docs/transformers/gen-javascript-transformer.md
  worker/pkg/benthos/transformers/gen_generate_int64.go
  worker/pkg/benthos/transformers/generate_bool.go
  worker/pkg/benthos/transformers/generate_email.go
  worker/pkg/benthos/transformers/generate_first_name.go
  worker/pkg/benthos/transformers/generate_float.go
  worker/pkg/benthos/transformers/generate_full_name.go
  worker/pkg/benthos/transformers/generate_gender.go
  worker/pkg/benthos/transformers/generate_int64.go
  worker/pkg/benthos/transformers/generate_last_name.go
  worker/pkg/benthos/transformers/generate_ssn.go
  worker/pkg/benthos/transformers/generate_username.go
  worker/pkg/benthos/transformers/transform_email.go
  worker/pkg/benthos/transformers/transform_first_name.go
  worker/pkg/benthos/transformers/transform_float.go
  worker/pkg/benthos/transformers/transform_full_name.go
  worker/pkg/benthos/transformers/transform_lastname.go
  worker/pkg/benthos/transformers/utils/integer_utils.go
Labels: bug

#2429 Adds more benthos dynamodb input tests
  worker/pkg/benthos/dynamodb/input.go
  worker/pkg/benthos/dynamodb/input_test.go
  worker/pkg/rng/rng_test.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/benthos-builder_test.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/processors_test.go
Labels: Tech Debt, ignore-for-release

#2432 Updates Transform Forms to no longer depend on React-Hook-Forms
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedGenerateCardNumber.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedGenerateCategoricalForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedGenerateEmailForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedGenerateFloat64Form.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedGenerateGenderForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedGenerateInt64Form.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedGenerateInternationalPhoneNumberForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedGenerateJavascriptForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedGenerateStateForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedGenerateStringForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedGenerateStringPhoneNumberForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedGenerateUuidForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedTransformCharacterScrambleForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedTransformE164PhoneNumberForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedTransformEmailForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedTransformFirstNameForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedTransformFloat64Form.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedTransformFullNameForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedTransformInt64Form.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedTransformInt64PhoneForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedTransformJavascriptForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedTransformLastNameForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedTransformPhoneNumberForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedTransformStringForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedTransformerForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/util.ts
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/schema.ts
  frontend/apps/web/app/(mgmt)/[account]/transformers/[id]/components/UpdateUserDefinedTransformerForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/systemTransformers/[source]/page.tsx
  frontend/apps/web/components/FormErrorMessage.tsx
Labels: Tech Debt

#2433 Consolidates Transformer Forms
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/DataGenConnectionCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/DataSyncConnectionCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/util.ts
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedGenerateJavascriptForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedTransformCharacterScrambleForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedTransformJavascriptForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/UserDefinedTransformerForms/UserDefinedTransformerForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/schema.ts
  frontend/apps/web/app/(mgmt)/[account]/transformers/EditTransformerOptions.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/Sheetforms/GenerateCardNumberForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/Sheetforms/GenerateCategoricalForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/Sheetforms/GenerateEmailForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/Sheetforms/GenerateFloat64Form.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/Sheetforms/GenerateGenderForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/Sheetforms/GenerateInt64Form.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/Sheetforms/GenerateInternationalPhoneNumberForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/Sheetforms/GenerateJavascriptForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/Sheetforms/GenerateRandomStringForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/Sheetforms/GenerateStateForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/Sheetforms/GenerateStringPhoneNumberForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/Sheetforms/GenerateUuidForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/Sheetforms/TransformCharacterScrambleForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/Sheetforms/TransformE164PhoneNumberForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/Sheetforms/TransformEmailForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/Sheetforms/TransformFirstNameForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/Sheetforms/TransformFloat64Form.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/Sheetforms/TransformFullNameForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/Sheetforms/TransformInt64Form.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/Sheetforms/TransformInt64PhoneForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/Sheetforms/TransformJavascriptForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/Sheetforms/TransformLastNameForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/Sheetforms/TransformPhoneNumberForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/Sheetforms/TransformStringForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/Sheetforms/util.ts
  frontend/apps/web/components/jobs/Form/DynamoDBSourceOptionsForm.tsx
  frontend/apps/web/components/jobs/NosqlTable/NosqlTable.tsx
  frontend/apps/web/components/jobs/SchemaTable/SchemaColumns.tsx
  frontend/apps/web/components/jobs/SchemaTable/SchemaTableToolBar.tsx
  frontend/apps/web/util/util.ts
Labels: Tech Debt

#2434 Renames Transformer Forms to remove UserDefined prefix
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateCardNumber.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateCategoricalForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateEmailForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateFloat64Form.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateGenderForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateInt64Form.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateInternationalPhoneNumberForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateJavascriptForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateStateForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateStringForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateStringPhoneNumberForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateUuidForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformCharacterScrambleForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformE164PhoneNumberForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformEmailForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformFirstNameForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformFloat64Form.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformFullNameForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformInt64Form.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformInt64PhoneForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformJavascriptForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformLastNameForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformPhoneNumberForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformStringForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformerForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/util.ts
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/EditTransformerOptions.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/[id]/components/UpdateTransformerForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/[id]/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/systemTransformers/[source]/page.tsx
Labels: Tech Debt

#2436 NEOS-1302: updates all toasts to use sonner
  frontend/apps/web/app/(mgmt)/[account]/connections/[id]/components/RemoveConnectionButton.tsx
  frontend/apps/web/app/(mgmt)/[account]/connections/[id]/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/connections/[id]/permissions/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/connections/components/ConnectionsTable/data-table-row-actions.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/components/ActivitySyncOptionsCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/components/JobPauseButton.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/components/RecentRuns.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/components/ScheduleCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/components/WorkflowSettingsCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/destinations/components/DestinationConnectionCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/layout.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/AiDataGenConnectionCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/DataGenConnectionCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/DataSyncConnectionCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/subsets/components/SubsetCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/components/DataTable/data-table-row-actions.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/api-key/NewApiKeyForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/connection/aws-s3/AwsS3Form.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/connection/dynamodb/DynamoDBForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/connection/gcp-cloud-storage/GcpCloudStorageForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/connection/mongodb/MongoDBForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/connection/mysql/MysqlForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/connection/openai/OpenAiForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/connection/postgres/PostgresForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/[id]/destination/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/aigenerate/single/schema/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/generate/single/schema/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/schema/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/subset/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/runs/[id]/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/runs/components/JobRunsTable/data-table-row-actions.tsx
  frontend/apps/web/app/(mgmt)/[account]/settings/api-keys/[id]/components/RemoveAccountApiKeyButton.tsx
  frontend/apps/web/app/(mgmt)/[account]/settings/api-keys/[id]/regenerate/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/settings/billing/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/settings/members/components/InviteTable.tsx
  frontend/apps/web/app/(mgmt)/[account]/settings/members/components/InviteUserForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/settings/members/components/MemberTable.tsx
  frontend/apps/web/app/(mgmt)/[account]/settings/temporal/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/[id]/components/RemoveTransformerButton.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/[id]/components/UpdateTransformerForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/components/UserDefinedTransformersTable/data-table-row-actions.tsx
  frontend/apps/web/app/BaseLayout.tsx
  frontend/apps/web/app/invite/page.tsx
  frontend/apps/web/components/CopyButton.tsx
  frontend/apps/web/components/jobs/SchemaTable/VirtualForeignKeyForm.tsx
  frontend/apps/web/components/onboarding-checklist/OnboardingChecklist.tsx
  frontend/apps/web/components/providers/query-provider.tsx
  frontend/apps/web/components/site-header/AccountSwitcher.tsx
  frontend/apps/web/components/site-header/UserNav.tsx
  frontend/apps/web/components/ui/sonner.tsx
  frontend/apps/web/components/ui/toast.tsx
  frontend/apps/web/components/ui/toaster.tsx
  frontend/apps/web/components/ui/use-toast.ts
  frontend/apps/web/knip.ts
  frontend/apps/web/package.json
  frontend/package-lock.json
Labels: Tech Debt

#2438 fixes source options form not being submittable, among others
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/util.ts
  frontend/apps/web/app/(mgmt)/[account]/new/job/connect/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/EditTransformerOptions.tsx
  frontend/apps/web/components/jobs/Form/SourceOptionsForm.tsx
  frontend/apps/web/yup-validations/jobs.ts
Labels: bug

#2437 NEOS-1311: syntax error neosyncaddindexifnotexists
  backend/pkg/sqlmanager/mysql/mysql-manager.go
  backend/pkg/sqlmanager/mysql/mysql-manager_integration_test.go
  backend/pkg/sqlmanager/mysql/testdata/setup.sql
Labels: bug

#2439 Fixes DTO->Data Layer DynamoDB Source Connection Model Mappings
  backend/sql/postgresql/models/models.go
  backend/sql/postgresql/models/transformers.go
Labels: bug

#2440 replaces all uses of use form persist
  frontend/apps/web/app/(mgmt)/[account]/new/job/aigenerate/single/connect/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/connect/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/define/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/generate/single/connect/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/generate/single/schema/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/schema/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/subset/page.tsx
  frontend/apps/web/app/(mgmt)/useFormPersist.tsx
  frontend/apps/web/package.json
  frontend/package-lock.json
Labels: Tech Debt

#2442 NEOS-1312: rollsback need for default jm and system transforms to be passthrough in UI
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/DataGenConnectionCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/DataSyncConnectionCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/util.ts
  frontend/apps/web/app/(mgmt)/[account]/jobs/util.ts
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/EditTransformerOptions.tsx
  frontend/apps/web/components/jobs/Form/DynamoDBSourceOptionsForm.tsx
  frontend/apps/web/components/jobs/NosqlTable/NosqlTable.tsx
  frontend/apps/web/components/jobs/SchemaTable/SchemaColumns.tsx
  frontend/apps/web/components/jobs/SchemaTable/SchemaTableToolBar.tsx
  frontend/apps/web/yup-validations/jobs.ts
Labels: bug

#2444 NEOS-1310: expose consistentread as dynamodb source option
  backend/gen/go/protos/mgmt/v1alpha1/job.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/job.pb.validate.go
  backend/protos/mgmt/v1alpha1/job.proto
  backend/sql/postgresql/models/models.go
  docs/protos/data/proto_docs.json
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/DataSyncConnectionCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/util.ts
  frontend/apps/web/app/(mgmt)/[account]/new/connection/openai/OpenAiForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/connect/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/schema.ts
  frontend/apps/web/components/jobs/Form/DynamoDBSourceOptionsForm.tsx
  frontend/apps/web/components/jobs/Form/SourceOptionsForm.tsx
  frontend/apps/web/yup-validations/jobs.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/job_pb.ts
  worker/pkg/benthos/config.go
  worker/pkg/benthos/dynamodb/input.go
  worker/pkg/benthos/dynamodb/input_test.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/sync-dynamodb.go
Labels: enhancement

#2446 NEOS-1313: fixes transformer config validations
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/components/ActivitySyncOptionsCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/components/JobCloneButton.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/components/WorkflowSettingsCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/AiDataGenConnectionCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/DataGenConnectionCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/subsets/components/SubsetCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/util.ts
  frontend/apps/web/app/(mgmt)/[account]/new/job/JobsProgressSteps.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/aigenerate/single/connect/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/aigenerate/single/schema/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/connect/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/define/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/generate/single/connect/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/generate/single/schema/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/job-form-validations.ts
  frontend/apps/web/app/(mgmt)/[account]/new/job/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/schema/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/subset/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/transform-form-validations.ts
  frontend/apps/web/app/(mgmt)/[account]/transformers/EditTransformerOptions.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/[id]/components/UpdateTransformerForm.tsx
  frontend/apps/web/components/jobs/NosqlTable/NosqlTable.tsx
  frontend/apps/web/components/jobs/SchemaTable/SchemaColumns.tsx
  frontend/apps/web/components/jobs/SchemaTable/SchemaTable.tsx
  frontend/apps/web/components/jobs/SchemaTable/SchemaTableToolBar.tsx
  frontend/apps/web/components/jobs/subsets/utils.ts
  frontend/apps/web/yup-validations/bigint.ts
  frontend/apps/web/yup-validations/jobs.ts
  frontend/apps/web/yup-validations/number.ts
Labels: bug, Tech Debt

#2447 Truncates long document keys in DyanmoDB table and relational columns
  frontend/apps/web/components/TruncatedText.tsx
  frontend/apps/web/components/jobs/Form/DynamoDBSourceOptionsForm.tsx
  frontend/apps/web/components/jobs/NosqlTable/NosqlTable.tsx
  frontend/apps/web/components/jobs/SchemaTable/SchemaColumns.tsx
Labels: enhancement

#2450 NEOS-1303: fix scroll bug
  frontend/apps/web/components/jobs/SchemaTable/TransformerSelect.tsx
Labels: bug

#2449 Adds more integration tests for api user service
  backend/internal/auth/jwt/client.go
  backend/services/mgmt/v1alpha1/user-account-service/account-onboading_test.go
  backend/services/mgmt/v1alpha1/user-account-service/account-onboarding.go
  backend/services/mgmt/v1alpha1/user-account-service/account-onboarding_integration_test.go
  backend/services/mgmt/v1alpha1/user-account-service/account-temporal-config.go
  backend/services/mgmt/v1alpha1/user-account-service/account-temporal-config_test.go
  backend/services/mgmt/v1alpha1/user-account-service/account-temporal_integration_test.go
  backend/services/mgmt/v1alpha1/user-account-service/integration_test.go
  backend/services/mgmt/v1alpha1/user-account-service/users.go
  backend/services/mgmt/v1alpha1/user-account-service/users_integration_auth_test.go
  backend/services/mgmt/v1alpha1/user-account-service/users_integration_noauth_test.go
  backend/services/mgmt/v1alpha1/user-account-service/users_integration_test.go
  backend/services/mgmt/v1alpha1/user-account-service/users_test.go
  worker/pkg/http/client/client.go
  worker/pkg/http/client/client_test.go
Labels: Tech Debt

#2453 Add dynamo output tests + default transformer processor test
  worker/pkg/benthos/default_transform/processor_test.go
  worker/pkg/benthos/dynamodb/output_test.go
  worker/pkg/benthos/transformers/transform_int64.go
  worker/pkg/benthos/transformers/utils/integer_utils.go
  worker/pkg/workflows/datasync/workflow/testdata/types.go
  worker/pkg/workflows/datasync/workflow/workflow_integration_test.go
Labels: bug, Devex

#2462 Dynamo handle empty sort key
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/sync-dynamodb.go
Labels: bug

#2466 update parquet to support go version 1.23
  go.mod
  go.sum
Labels: dependencies

#2468 remove `fatal: No names found, cannot describe anything.` warning during development builds
  backend/scripts/build.sh
  cli/Makefile
Labels: bug, Tech Debt

#2471 updates default openai common models to document latest gpt models
  frontend/apps/web/app/(mgmt)/[account]/new/job/aigenerate/single/schema/SelectModelNames.tsx
Labels: Improvement

#2472 fixup wait behavior inside of makefile
  Makefile
Labels: bug

#2465 NEOS-1316: add sql server as neosync connection
  .mockery.yml
  backend/gen/go/protos/mgmt/v1alpha1/connection.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/connection.pb.validate.go
  backend/internal/cmds/mgmt/serve/connect/cmd.go
  backend/pkg/mssql-querier/db.go
  backend/pkg/mssql-querier/mock_Querier.go
  backend/pkg/mssql-querier/querier.go
  backend/pkg/mssql-querier/system.sql.go
  backend/pkg/sqlconnect/pgpool.go
  backend/pkg/sqlconnect/sql-connector.go
  backend/pkg/sqlconnect/sql-connector_test.go
  backend/pkg/sqlconnect/sqldb.go
  backend/pkg/sqlmanager/mssql/integration_test.go
  backend/pkg/sqlmanager/mssql/mssql-manager.go
  backend/pkg/sqlmanager/mssql/mssql-manager_integration_test.go
  backend/pkg/sqlmanager/mssql/testdata/README.md
  backend/pkg/sqlmanager/mssql/testdata/dest-setup/001.sql
  backend/pkg/sqlmanager/mssql/testdata/dest-setup/002.sql
  backend/pkg/sqlmanager/mssql/testdata/source-setup/001.sql
  backend/pkg/sqlmanager/mssql/testdata/source-setup/002.sql
  backend/pkg/sqlmanager/mssql/testdata/source-setup/003.sql
  backend/pkg/sqlmanager/mssql/testdata/teardown/001.sql
  backend/pkg/sqlmanager/shared/types.go
  backend/pkg/sqlmanager/sql-manager.go
  backend/pkg/sqlmanager/sql-manager_test.go
  backend/protos/mgmt/v1alpha1/connection.proto
  backend/services/mgmt/v1alpha1/connection-service/connection.go
  backend/services/mgmt/v1alpha1/connection-service/connection_test.go
  backend/services/mgmt/v1alpha1/connection-service/service.go
  backend/sql/postgresql/models/models.go
  cli/internal/cmds/neosync/sync/sync.go
  compose.dev.yml
  compose/compose-db-mssql.yml
  docs/protos/data/proto_docs.json
  frontend/apps/web/app/(mgmt)/[account]/connections/[id]/components/MssqlForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/connections/[id]/components/connection-component.tsx
  frontend/apps/web/app/(mgmt)/[account]/connections/util.ts
  frontend/apps/web/app/(mgmt)/[account]/new/connection/mssql/MssqlForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/connection/mssql/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/connection/page.tsx
  frontend/apps/web/app/api/config/config.ts
  frontend/apps/web/app/config/app-config.ts
  frontend/apps/web/components/connections/ConnectionIcon.tsx
  frontend/apps/web/components/permissions/PermissionsDialog.tsx
  frontend/apps/web/components/permissions/columns.tsx
  frontend/apps/web/yup-validations/connections.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/connection_pb.ts
  go.mod
  go.sum
  worker/internal/cmds/worker/serve/serve.go
  worker/internal/connection-tunnel-manager/manager_test.go
  worker/pkg/workflows/datasync/workflow/workflow_integration_test.go
Labels: enhancement

#2482 NEOS-1317 wire up sql server CRUD to job service
  backend/gen/go/protos/mgmt/v1alpha1/job.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/job.pb.validate.go
  backend/protos/mgmt/v1alpha1/job.proto
  backend/services/mgmt/v1alpha1/job-service/jobs.go
  backend/sql/postgresql/models/models.go
  docs/protos/data/proto_docs.json
  frontend/packages/sdk/src/client/mgmt/v1alpha1/job_pb.ts
Labels: enhancement

#2483 Update critical errors list
  worker/pkg/benthos/utils.go
Labels: bug

#2484 NEOS-1329: replace sqlmanager tests with real databases
  backend/pkg/sqlconnect/sql-connector.go
  backend/pkg/sqlmanager/mssql_sql-manager_integration_test.go
  backend/pkg/sqlmanager/mysql_sql-manager_integration_test.go
  backend/pkg/sqlmanager/postgres_sql-manager_integration_test.go
  backend/pkg/sqlmanager/sql-manager_test.go
Labels: Tech Debt

#2485 add new changelog
  docs/blog/2024-08-15-dynamodb-upgrades.md
Labels: documentation

#2486 update changelog
  docs/blog/2024-08-15-dynamodb-upgrades.md
Labels: documentation

#2487 update path
  docs/blog/2024-08-15-dynamodb-upgrades.md
Labels: documentation

#2493 NEOS-1339: fix max height on transformer select
  frontend/apps/web/app/(mgmt)/[account]/new/job/aigenerate/single/schema/SampleTable/SampleTable.tsx
  frontend/apps/web/components/jobs/SchemaTable/TransformerSelect.tsx
Labels: enhancement

#2488 feat: update SampleTable to use Form fields to match parent field
  frontend/apps/web/app/(mgmt)/[account]/new/job/aigenerate/single/schema/SampleTable/SampleTable.tsx
Labels: bug

#2492 NEOS-1343: Fixes self-referencing logic in worker when following FK constraints
  .github/workflows/go.yml
  backend/pkg/sqlconnect/pgpool.go
  backend/pkg/sqlconnect/sql-connector.go
  backend/pkg/sqlconnect/sqldb.go
  backend/pkg/sqlmanager/sql-manager.go
  backend/pkg/table-dependency/table-dependency.go
  backend/pkg/table-dependency/table-dependency_test.go
  backend/services/mgmt/v1alpha1/metrics-service/metrics.go
  cli/internal/output/output.go
  go.mod
  go.sum
  worker/internal/cmds/worker/serve/serve.go
  worker/pkg/benthos/mongodb/input.go
  worker/pkg/benthos/transformers/utils/integer_utils.go
  worker/pkg/query-builder/query-builder_integration_test.go
  worker/pkg/query-builder2/integration_test.go
  worker/pkg/query-builder2/query-builder_integration_test.go
  worker/pkg/query-builder2/querybuilder.go
  worker/pkg/query-builder2/subset.go
  worker/pkg/query-builder2/testdata/setup.sql
  worker/pkg/query-builder2/testdata/teardown.sql
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/benthos-builder_test.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/sync.go
  worker/pkg/workflows/datasync/workflow/testdata/gen-jobmappings-config.json
  worker/pkg/workflows/datasync/workflow/testdata/postgres/circular-dependencies/tests.go
  worker/pkg/workflows/datasync/workflow/testdata/postgres/subsetting/job_mappings.go
  worker/pkg/workflows/datasync/workflow/testdata/postgres/subsetting/schema-create.sql
  worker/pkg/workflows/datasync/workflow/testdata/postgres/subsetting/setup.sql
  worker/pkg/workflows/datasync/workflow/testdata/postgres/subsetting/teardown.sql
  worker/pkg/workflows/datasync/workflow/testdata/postgres/subsetting/tests.go
  worker/pkg/workflows/datasync/workflow/workflow_integration_test.go
Labels: bug

#2501 Remove recursive query from querybuilder
  worker/pkg/query-builder/integration_test.go
  worker/pkg/query-builder2/query-builder_integration_test.go
  worker/pkg/query-builder2/querybuilder.go
  worker/pkg/workflows/datasync/workflow/testdata/postgres/subsetting/tests.go
  worker/pkg/workflows/datasync/workflow/testdata/postgres/virtual-foreign-keys/tests.go
Labels: bug

#2503 Querybuilder optimizations
  .github/workflows/go.yml
  worker/pkg/query-builder2/querybuilder.go
  worker/pkg/query-builder2/subset.go
  worker/pkg/workflows/datasync/activities/sync/activity_test.go
Labels: Devex

#2489 NEOS-1267 Add dynamodb support to Neosync CLI
  backend/gen/go/protos/mgmt/v1alpha1/connection_data.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/connection_data.pb.validate.go
  backend/protos/mgmt/v1alpha1/connection_data.proto
  backend/services/mgmt/v1alpha1/connection-data-service/connection-data.go
  cli/internal/benthos/config.go
  cli/internal/benthos/inputs/neosync-connection-data.go
  cli/internal/cmds/neosync/connections/list.go
  cli/internal/cmds/neosync/sync/dynamodb.go
  cli/internal/cmds/neosync/sync/sync.go
  cli/internal/cmds/neosync/sync/ui.go
  docs/protos/data/proto_docs.json
  frontend/packages/sdk/src/client/mgmt/v1alpha1/connection_data_pb.ts
  internal/aws/dynamodb-client.go
  internal/dynamodb/utils.go
  internal/dynamodb/utils_test.go
  worker/pkg/benthos/dynamodb/input.go
  worker/pkg/benthos/dynamodb/input_test.go
  worker/pkg/benthos/dynamodb/output.go
Labels: Improvement

#2511 Fix mysql connections with special characters
  backend/pkg/sqlconnect/sql-connector.go
  backend/pkg/sqlconnect/sql-connector_test.go
Labels: bug, Mysql

#2507 NEOS-1349: [migration] Adds RunContexts rpc
  backend/gen/go/db/mock_Querier.go
  backend/gen/go/db/models.go
  backend/gen/go/db/querier.go
  backend/gen/go/db/runcontexts.sql.go
  backend/gen/go/protos/mgmt/v1alpha1/job.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/job.pb.validate.go
  backend/gen/go/protos/mgmt/v1alpha1/mgmtv1alpha1connect/job.connect.go
  backend/gen/go/protos/mgmt/v1alpha1/mgmtv1alpha1connect/mock_JobServiceClient.go
  backend/gen/go/protos/mgmt/v1alpha1/mgmtv1alpha1connect/mock_JobServiceHandler.go
  backend/internal/cmds/mgmt/serve/connect/cmd.go
  backend/protos/mgmt/v1alpha1/job.proto
  backend/services/mgmt/v1alpha1/job-service/runs.go
  backend/services/mgmt/v1alpha1/job-service/service.go
  backend/sql/postgresql/queries/runcontexts.sql
  backend/sql/postgresql/schema/20240822000654_adds-updated-at-function.down.sql
  backend/sql/postgresql/schema/20240822000654_adds-updated-at-function.up.sql
  backend/sql/postgresql/schema/20240822000658_adds-run-context.down.sql
  backend/sql/postgresql/schema/20240822000658_adds-run-context.up.sql
  docs/protos/data/proto_docs.json
  frontend/packages/sdk/src/client/mgmt/v1alpha1/job-JobService_connectquery.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/job_connect.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/job_pb.ts
Labels: enhancement

#2514 NEOS-1352:update transformer height
  frontend/apps/web/components/jobs/SchemaTable/TransformerSelect.tsx
Labels: enhancement

#2512 NEOS-1346: updates worker to support runcontexts
  backend/gen/go/protos/mgmt/v1alpha1/job.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/mgmtv1alpha1connect/job.connect.go
  backend/gen/go/protos/mgmt/v1alpha1/mgmtv1alpha1connect/mock_JobServiceClient.go
  backend/gen/go/protos/mgmt/v1alpha1/mgmtv1alpha1connect/mock_JobServiceHandler.go
  backend/protos/mgmt/v1alpha1/job.proto
  backend/services/mgmt/v1alpha1/job-service/runs.go
  docs/protos/data/proto_docs.json
  frontend/packages/sdk/src/client/mgmt/v1alpha1/job_connect.ts
  worker/internal/cmds/worker/serve/serve.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/activity.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/benthos-builder.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/benthos-builder_test.go
  worker/pkg/workflows/datasync/activities/shared/shared.go
  worker/pkg/workflows/datasync/activities/sync/activity.go
  worker/pkg/workflows/datasync/activities/sync/activity_test.go
  worker/pkg/workflows/datasync/workflow/workflow.go
  worker/pkg/workflows/datasync/workflow/workflow_integration_test.go
Labels: enhancement

#2516 NEOS-1346: fixes nil pointer error with user uuids
  backend/services/mgmt/v1alpha1/job-service/runs.go
  backend/services/mgmt/v1alpha1/user-account-service/users.go
Labels: bug

#2504 NEOS-1345: split integration test suites
  .github/workflows/go.yml
  worker/pkg/query-builder/integration_test.go
  worker/pkg/query-builder/query-builder.go
  worker/pkg/query-builder/query-builder_integration_test.go
  worker/pkg/query-builder/query-builder_test.go
  worker/pkg/query-builder/testdata/setup.sql
  worker/pkg/query-builder/testdata/teardown.sql
Labels: Tech Debt

#2521 NEOS-1359:update mongodb documentation
  compose.dev.yml
  compose/compose-db-mongo.yml
  docs/docs/connections/mongodb.md
  docs/docs/guides/neosync-ip-ranges.md
  docs/docs/guides/syncing-data-in-mongodb.md
  docs/sidebars.ts
  docs/src/CustomComponents/IconHandler.tsx
  docs/static/img/mongo-coll.png
  docs/static/img/mongo-connect.png
  docs/static/img/mongo-define.png
  docs/static/img/mongo-email.png
  docs/static/img/mongoconn.png
  docs/static/img/mongodb-tm.png
  docs/static/img/mongojob.png
  docs/static/img/mongolocal.png
  docs/static/img/mongosh.png
  docs/static/img/mongotest.png
Labels: documentation

#2515 NEOS-1351 Add mongo db workflow integration test
  backend/pkg/mongomanager/utils.go
  backend/pkg/mongomanager/utils_test.go
  backend/services/mgmt/v1alpha1/connection-data-service/connection-data.go
  cli/internal/benthos/inputs/neosync-connection-data.go
  go.mod
  go.sum
  internal/dynamodb/utils.go
  internal/dynamodb/utils_test.go
  internal/types/types.go
  worker/pkg/benthos/dynamodb/input.go
  worker/pkg/benthos/dynamodb/output.go
  worker/pkg/benthos/metadata/utils.go
  worker/pkg/benthos/mongodb/common.go
  worker/pkg/benthos/mongodb/input.go
  worker/pkg/benthos/transformers/utils/float_utils.go
  worker/pkg/benthos/transformers/utils/integer_utils.go
  worker/pkg/workflows/datasync/workflow/integration_test.go
  worker/pkg/workflows/datasync/workflow/workflow_integration_test.go
Labels: Devex, Tech Debt

#2523 NEOS-1360: enables cgo for worker to enable postgres query parsing
  compose.dev.yml
  docker/Dockerfile.backend
  docker/Dockerfile.worker
  go.mod
  go.sum
  worker/Makefile
  worker/dev/build/Dockerfile.dev
  worker/pkg/query-builder2/querybuilder.go
  worker/scripts/build.sh
Labels: bug

#2527 Revert "NEOS-1360: enables cgo for worker to enable postgres query pa…
  compose.dev.yml
  docker/Dockerfile.backend
  docker/Dockerfile.worker
  go.mod
  go.sum
  worker/Makefile
  worker/dev/build/Dockerfile.dev
  worker/pkg/query-builder2/querybuilder.go
  worker/scripts/build.sh
Labels: bug, Tech Debt

#2529 NEOS-1360: Fixes postgres query optimizations by enabling CGO in backend/worker
  backend/Makefile
  backend/dev/build/Dockerfile.dev
  backend/scripts/build.sh
  compose.dev.yml
  docker/Dockerfile.backend
  docker/Dockerfile.worker
  go.mod
  go.sum
  worker/Makefile
  worker/dev/build/Dockerfile.dev
  worker/pkg/query-builder2/querybuilder.go
  worker/scripts/build.sh
Labels: bug

#2530 Further optimizes docker builds for backend, worker
  .dockerignore
  backend/dev/build/Dockerfile.dev
  compose.dev.yml
  docker/Dockerfile.backend
  docker/Dockerfile.worker
  worker/dev/build/Dockerfile.dev
Labels: Tech Debt

#2531 NEOS-1355: Update job cancel modal
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/components/RecentRuns.tsx
  frontend/apps/web/app/(mgmt)/[account]/runs/[id]/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/runs/components/JobRunsTable/data-table-row-actions.tsx
  frontend/apps/web/components/ConfirmationDialog.tsx
  frontend/apps/web/components/DeleteConfirmationDialog.tsx
Labels: Improvement

#2532 NEOS-1353: add placeholder valuess for mongo form
  frontend/apps/web/components/jobs/NosqlTable/NosqlTable.tsx
  frontend/apps/web/components/ui/select.tsx
Labels: enhancement

#2534 Adds integration tests for transformers service, sets up tests for jobs
  backend/gen/go/protos/mgmt/v1alpha1/transformer.pb.go
  backend/protos/mgmt/v1alpha1/transformer.proto
  backend/services/mgmt/v1alpha1/job-service/integration_test.go
  backend/services/mgmt/v1alpha1/job-service/integration_util_test.go
  backend/services/mgmt/v1alpha1/job-service/jobs_integration_test.go
  backend/services/mgmt/v1alpha1/transformers-service/integration_test.go
  backend/services/mgmt/v1alpha1/transformers-service/integration_util_test.go
  backend/services/mgmt/v1alpha1/transformers-service/system_transformers_integration_test.go
  backend/services/mgmt/v1alpha1/transformers-service/system_transformers_test.go
  backend/services/mgmt/v1alpha1/transformers-service/transformers_test.go
  backend/services/mgmt/v1alpha1/transformers-service/userdefined_transformers.go
  backend/services/mgmt/v1alpha1/transformers-service/userdefined_transformers_integration_test.go
  backend/sql/postgresql/models/models.go
  docs/protos/data/proto_docs.json
  frontend/packages/sdk/src/client/mgmt/v1alpha1/transformer_pb.ts
Labels: Tech Debt

#2506 Adds initial frontend utility tests
  frontend/apps/web/jest.config.ts
  frontend/apps/web/libs/fetcher.ts
  frontend/apps/web/libs/util.test.ts
  frontend/apps/web/package.json
  frontend/apps/web/util/util.test.ts
  frontend/apps/web/util/util.ts
  frontend/apps/web/yup-validations/bigint.test.ts
  frontend/apps/web/yup-validations/connections.ts
  frontend/apps/web/yup-validations/jobs.test.ts
  frontend/apps/web/yup-validations/number.test.ts
  frontend/package-lock.json
Labels: Tech Debt

#2543 NEOS-1344: Adds Docs on how to view run logs
  charts/neosync/README.md
  docs/docs/deploy/environment-variables.md
  docs/docs/guides/viewing-job-run-logs.md
  docs/sidebars.ts
  docs/static/img/runlogs.png
  frontend/apps/web/charts/app/README.md
  frontend/apps/web/charts/app/values.yaml
Labels: Docs

#2544 adds docs icon for logs page
  docs/src/CustomComponents/IconHandler.tsx
Labels: Docs

#2545 NEOS-1367: update buf GitHub action to use aio buf action
  .github/workflows/buf.yml
  backend/BUF_VERSION
Labels: Devex, Tech Debt

#2546 fixes jobs service integration tests
  backend/services/mgmt/v1alpha1/job-service/integration_test.go
Labels: Tech Debt

#2481 Nick/neos 1319 add sql server support to neosync worker
  backend/pkg/mssql-querier/mock_Querier.go
  backend/pkg/mssql-querier/querier.go
  backend/pkg/mssql-querier/system.sql.go
  backend/pkg/sqlmanager/mssql/mssql-manager.go
  worker/internal/connection-tunnel-manager/manager.go
  worker/internal/connection-tunnel-manager/manager_test.go
  worker/internal/connection-tunnel-manager/providers/provider.go
  worker/internal/connection-tunnel-manager/providers/provider_test.go
  worker/internal/connection-tunnel-manager/providers/sqlprovider/provider.go
  worker/internal/connection-tunnel-manager/providers/sqlprovider/provider_test.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/benthos-builder.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/sync.go
  worker/pkg/workflows/datasync/activities/run-sql-init-table-stmts/init-statement-builder.go
  worker/pkg/workflows/datasync/activities/shared/shared.go
  worker/pkg/workflows/datasync/workflow/integration_test.go
  worker/pkg/workflows/datasync/workflow/testdata/mssql/simple/create-schema.sql
  worker/pkg/workflows/datasync/workflow/testdata/mssql/simple/create-table.sql
  worker/pkg/workflows/datasync/workflow/testdata/mssql/simple/insert.sql
  worker/pkg/workflows/datasync/workflow/testdata/mssql/simple/teardown.sql
  worker/pkg/workflows/datasync/workflow/testdata/mssql/simple/tests.go
  worker/pkg/workflows/datasync/workflow/workflow_integration_test.go
Labels: enhancement

#2550 NEOS-1319: Fills out schema,constraint functions for mssql query manager
  backend/pkg/mssql-querier/system.sql.go
  backend/pkg/sqlmanager/mssql/integration_test.go
  backend/pkg/sqlmanager/mssql/mssql-manager.go
  backend/pkg/sqlmanager/mssql/mssql-manager_integration_test.go
  backend/pkg/sqlmanager/mssql/testdata/source-setup/003.sql
  backend/pkg/sqlmanager/mssql/testdata/source-setup/004.sql
Labels: bug, Tech Debt

#2541 NEOS-1318: expose sql server to sync jobs on frontend
  backend/gen/go/protos/mgmt/v1alpha1/connection_data.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/connection_data.pb.validate.go
  backend/protos/mgmt/v1alpha1/connection_data.proto
  backend/services/mgmt/v1alpha1/connection-data-service/connection-data.go
  docs/protos/data/proto_docs.json
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/destinations/components/DestinationConnectionCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/layout.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/DataSyncConnectionCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/util.ts
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/subsets/components/SubsetCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/util.ts
  frontend/apps/web/app/(mgmt)/[account]/new/job/connect/ConnectionSelectContent.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/connect/page.tsx
  frontend/apps/web/components/jobs/Form/DestinationOptionsForm.tsx
  frontend/apps/web/components/jobs/Form/SourceOptionsForm.tsx
  frontend/apps/web/components/jobs/NosqlTable/NosqlTable.tsx
  frontend/apps/web/components/jobs/subsets/utils.ts
  frontend/apps/web/components/ui/select.tsx
  frontend/apps/web/libs/utils.ts
  frontend/apps/web/yup-validations/jobs.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/connection_data_pb.ts
Labels: enhancement

#2554 Optimize Worker,Api Docker Compose Dev watchers
  .dockerignore
  compose.dev.yml
Labels: Tech Debt, ignore-for-release

#2555 NEOS-1372: add ability to configure ssh tunneling to mssql via backend
  .golangci.yaml
  backend/gen/go/protos/mgmt/v1alpha1/connection.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/connection.pb.validate.go
  backend/pkg/dbconnect-config/dbconnect-config.go
  backend/pkg/dbconnect-config/dbconnect-config_test.go
  backend/pkg/dbconnect-config/mssql.go
  backend/pkg/dbconnect-config/mssql_test.go
  backend/pkg/dbconnect-config/mysql.go
  backend/pkg/dbconnect-config/mysql_test.go
  backend/pkg/dbconnect-config/postgres.go
  backend/pkg/dbconnect-config/postgres_test.go
  backend/pkg/sqlconnect/pgpool.go
  backend/pkg/sqlconnect/sql-connector.go
  backend/pkg/sqlconnect/sql-connector_test.go
  backend/pkg/sqlconnect/sqldb.go
  backend/protos/mgmt/v1alpha1/connection.proto
  backend/sql/postgresql/models/models.go
  docs/protos/data/proto_docs.json
  frontend/packages/sdk/src/client/mgmt/v1alpha1/connection_pb.ts
  worker/internal/connection-tunnel-manager/manager_test.go
Labels: enhancement

#2558 NEOS-1375: optimize querybuilder selects to conditionally add joins
  worker/pkg/query-builder2/query-builder_integration_test.go
  worker/pkg/query-builder2/querybuilder.go
  worker/pkg/query-builder2/testdata/setup.sql
Labels: bug

#2560 NEOS-1377: Combines invite and main app layouts
  frontend/apps/web/app/(mgmt)/layout.tsx
  frontend/apps/web/app/layout.tsx
Labels: bug

#2562 NEOS-1374: expose ssh tunneling for mssql to frontend
  frontend/apps/web/app/(mgmt)/[account]/connections/[id]/components/MssqlForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/connections/[id]/components/connection-component.tsx
  frontend/apps/web/app/(mgmt)/[account]/connections/util.ts
  frontend/apps/web/app/(mgmt)/[account]/new/connection/mssql/MssqlForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/connection/postgres/PostgresForm.tsx
  frontend/apps/web/yup-validations/connections.ts
Labels: enhancement

#2565 NEOS-1380: fixes sql server role permissions performance
  backend/pkg/mssql-querier/system.sql.go
  backend/pkg/sqlconnect/sql-connector.go
  backend/pkg/sqlmanager/mssql/mssql-manager.go
  compose.dev.yml
Labels: bug

#2567 NEOS-1381: fixes inconsistent ordering of mssql constraints
  backend/pkg/sqlmanager/mssql/mssql-manager_integration_test.go
  backend/pkg/sqlmanager/shared/utils.go
  backend/pkg/sqlmanager/shared/utils_test.go
Labels: bug

#2570 NEOS-1273 filter foreign keys by null transformers
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/sync.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/sync_test.go
Labels: Improvement

#2573 updateChangelog
  docs/blog/2024-08-15-dynamodb-upgrades copy.md
  docs/blog/2024-08-29-sql-server-support.md
Labels: documentation

#2533 NEOS-1361, NEOS-1370: Support updating mongo mappings inline
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/DataSyncConnectionCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/schema/page.tsx
  frontend/apps/web/components/jobs/NosqlTable/NosqlTable.tsx
  frontend/apps/web/components/jobs/SchemaTable/SchemaPageTable.tsx
Labels: enhancement

#2574 NEOS-1383: optimize querybuilder queries
  worker/pkg/query-builder2/query-builder_integration_test.go
  worker/pkg/query-builder2/querybuilder.go
  worker/pkg/query-builder2/subset.go
Labels: enhancement

#2576 NEOS-1387: Country code transformer
  .vscode/settings.json
  backend/gen/go/protos/mgmt/v1alpha1/transformer.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/transformer.pb.validate.go
  backend/protos/mgmt/v1alpha1/transformer.proto
  backend/services/mgmt/v1alpha1/transformers-service/system_transformers.go
  backend/sql/postgresql/models/transformers.go
  docs/docs/transformers/gen-javascript-transformer.md
  docs/protos/data/proto_docs.json
  frontend/apps/web/@types/neosync-transformers.d.ts
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/GenerateCountryForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/TransformerForms/TransformerForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/transform-form-validations.ts
  frontend/apps/web/util/util.test.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/transformer_pb.ts
  worker/pkg/benthos/transformers/data-sets/country_codes.go
  worker/pkg/benthos/transformers/gen_generate_country.go
  worker/pkg/benthos/transformers/gen_generate_country_code.go
  worker/pkg/benthos/transformers/gen_neosync_transformers.go
  worker/pkg/benthos/transformers/generate_country.go
  worker/pkg/benthos/transformers/generate_country_test.go
  worker/pkg/benthos/transformers/generate_state_test.go
  worker/pkg/benthos/transformers/transformer_initializer.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/benthos-builder_test.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/processors.go
Labels: Feature
