Repository nucleuscloud/neosync, pull requests merged in 2025-04, with the labels that each got.

#3445 Fixes Scramble Identity not showing on frontend
  frontend/apps/web/components/jobs/SchemaTable/transformer-handler.ts
Labels: bug

#3443 NEOS-1541: expose transformpiitext method to benthos worker
  backend/internal/cmds/mgmt/serve/connect/cmd.go
  backend/internal/dtomaps/jobs.go
  backend/internal/dtomaps/transformers.go
  backend/pkg/integration-test/mux.go
  backend/services/mgmt/v1alpha1/anonymization-service/anonymization.go
  backend/services/mgmt/v1alpha1/anonymization-service/service.go
  backend/services/mgmt/v1alpha1/transformers-service/service.go
  backend/services/mgmt/v1alpha1/transformers-service/system_transformers.go
  backend/sql/postgresql/models/models.go
  backend/sql/postgresql/models/transformers.go
  frontend/apps/web/libs/hooks/useGetTransformersHandler.ts
  internal/benthos/benthos-builder/builders/benthos-builder_test.go
  internal/benthos/benthos-builder/builders/processors.go
  internal/integration-tests/api/anonymization-service_integration_test.go
  internal/integration-tests/worker/workflow/datasync-workflow.go
  internal/javascript/functions/neosync/functions.go
  internal/javascript/functions/neosync/functions_test.go
  internal/javascript/javascript.go
  tools/go.mod
  worker/internal/cmds/worker/serve/serve.go
  worker/pkg/benthos/environment/environment.go
  worker/pkg/benthos/javascript/processor.go
  worker/pkg/benthos/javascript/processor_test.go
  worker/pkg/benthos/transformer_executor/executor.go
  worker/pkg/benthos/transformer_executor/transform_pii_text_api.go
  worker/pkg/benthos/transformers/gen_transform_pii_text.go
  worker/pkg/benthos/transformers/transform_pii_text.go
  worker/pkg/benthos/transformers/transform_pii_text_test.go
  worker/pkg/workflows/tablesync/activities/sync/activity.go
  worker/pkg/workflows/tablesync/activities/sync/activity_test.go
  worker/pkg/workflows/tablesync/workflow/register/register.go
Labels: enhancement

#3447 Fixes SQLServer generated columns default transformer not appearing on frontend
  backend/gen/go/db/dbschemas/postgresql/mock_Querier.go
  backend/pkg/mssql-querier/mock_Querier.go
  backend/pkg/mssql-querier/querier.go
  backend/pkg/mssql-querier/system.sql.go
  backend/pkg/sqlmanager/mssql/mssql-manager.go
  internal/ee/mssql-manager/ee-mssql-manager.go
  internal/ee/mssql-manager/generate-sql.go
  internal/integration-tests/worker/workflow/mssql_test.go
  internal/testutil/testdata/mssql/alltypes/create-tables.sql
  internal/testutil/testdata/mssql/alltypes/job-mappings.go
Labels: bug

#3453 NEOS-1807: fixes panic in transform e164 phone number
  worker/pkg/benthos/transformers/transform_e164_phone_number.go
  worker/pkg/benthos/transformers/transform_e164_phone_number_test.go
Labels: bug

#3452 NEOS-1794: Refactors redis processor and output to use redis client
  cli/internal/cmds/neosync/sync/sync.go
  internal/benthos/benthos-builder/benthos-builder.go
  internal/benthos/benthos-builder/builders/benthos-builder_test.go
  internal/benthos/benthos-builder/builders/dynamodb.go
  internal/benthos/benthos-builder/builders/mongodb.go
  internal/benthos/benthos-builder/builders/processors.go
  internal/benthos/benthos-builder/builders/processors_test.go
  internal/benthos/benthos-builder/builders/sql.go
  internal/benthos/imports/imports.go
  internal/integration-tests/worker/workflow/datasync-workflow.go
  worker/internal/cmds/worker/serve/serve.go
  worker/pkg/benthos/config.go
  worker/pkg/benthos/environment/environment.go
  worker/pkg/benthos/redis/client.go
  worker/pkg/benthos/redis/output_hash.go
  worker/pkg/benthos/redis/processor.go
  worker/pkg/benthos/utils.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/activity.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/benthos-builder.go
  worker/pkg/workflows/datasync/activities/shared/shared.go
  worker/pkg/workflows/datasync/workflow/register/register.go
  worker/pkg/workflows/tablesync/activities/sync/activity.go
  worker/pkg/workflows/tablesync/activities/sync/activity_test.go
  worker/pkg/workflows/tablesync/workflow/register/register.go
Labels: Devex

#3435 NEOS-1790: Postgres init schema handle datatypes
  backend/gen/go/db/dbschemas/postgresql/mock_Querier.go
  backend/gen/go/db/dbschemas/postgresql/querier.go
  backend/gen/go/db/dbschemas/postgresql/system.sql.go
  backend/pkg/dbschemas/sql/postgresql/queries/system.sql
  backend/pkg/sqlmanager/mock_SqlDatabase.go
  backend/pkg/sqlmanager/mysql/mysql-manager.go
  backend/pkg/sqlmanager/postgres/postgres-manager.go
  backend/pkg/sqlmanager/shared/fingerprint.go
  backend/pkg/sqlmanager/shared/types.go
  backend/pkg/sqlmanager/sql-manager.go
  internal/ee/mssql-manager/ee-mssql-manager.go
  internal/integration-tests/worker/workflow/postgres_test.go
  internal/schema-manager/postgres/postgres.go
  internal/schema-manager/shared/schema-diff.go
  internal/schema-manager/shared/schema-diff_test.go
  internal/testutil/testdata/postgres/schema-init/alter-statements.sql
  internal/testutil/testdata/postgres/schema-init/create-tables.sql
  internal/testutil/testdata/postgres/schema-init/job-mappings.go
Labels: enhancement

#3454 NEOS-1798: Adds passthrough as a new column addition strategy
  backend/gen/go/protos/mgmt/v1alpha1/job.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/job.pb.json.go
  backend/protos/mgmt/v1alpha1/job.proto
  backend/sql/postgresql/models/models.go
  docs/openapi/mgmt/v1alpha1/job.openapi.yaml
  docs/openapi/neosync.mgmt.v1alpha1.yaml
  docs/protos/mgmt/v1alpha1/job.proto.mdx
  docs/protos/proto_docs.json
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/DataSyncConnectionCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/util.ts
  frontend/apps/web/app/(mgmt)/[account]/new/job/connect/page.tsx
  frontend/apps/web/components/jobs/Form/MssqlDBSourceOptionsForm.tsx
  frontend/apps/web/components/jobs/Form/NewColumnAdditionStrategyOptionsForm.tsx
  frontend/apps/web/components/jobs/Form/SourceOptionsForm.tsx
  frontend/apps/web/yup-validations/jobs.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/job_pb.ts
  internal/benthos/benthos-builder/builders/sql-util.go
  internal/benthos/benthos-builder/builders/sql.go
  internal/integration-tests/worker/workflow/postgres_test.go
  internal/integration-tests/worker/workflow/types.go
  internal/integration-tests/worker/workflow/workflow-integration_test.go
  internal/job/job.go
  python/src/neosync/mgmt/v1alpha1/job_pb2.py
  python/src/neosync/mgmt/v1alpha1/job_pb2.pyi
Labels: Feature

#3456 Add postgres automapper support for time datatypes
  internal/benthos/benthos-builder/builders/sql-util.go
Labels: enhancement

#3461 NEOS-1809: adds more critical errors for on conflict and check constraints
  worker/pkg/benthos/utils.go
Labels: bug

#3469 NEOS-1810: Handles upsert for postgres tables with deferrable constraints when on conflict update selected
  backend/gen/go/db/dbschemas/postgresql/system.sql.go
  backend/pkg/dbschemas/sql/postgresql/queries/system.sql
  backend/pkg/sqlmanager/postgres/postgres-manager.go
  backend/pkg/sqlmanager/shared/types.go
  internal/benthos/benthos-builder/builders/sql-util.go
  internal/benthos/benthos-builder/builders/sql.go
  internal/integration-tests/worker/workflow/postgres_test.go
  internal/testutil/testdata/postgres/schema-init/alter-statements.sql
  internal/testutil/testdata/postgres/schema-init/create-tables.sql
  internal/testutil/testdata/postgres/schema-init/job-mappings.go
  worker/pkg/benthos/config.go
  worker/pkg/benthos/sql/output_sql_insert.go
  worker/pkg/query-builder/insert-query-builder.go
  worker/pkg/workflows/datasync/activities/shared/shared.go
Labels: bug

#3471 Update warning to info
  worker/pkg/query-builder/insert-query-builder.go
Labels: Devex

#3475 Updates critical errors list to handle Mysql and SqlServer not null violations
  worker/pkg/benthos/utils.go
Labels: Devex

#3474 NEOS-1808: job run activity timeline status filter not working
  backend/services/mgmt/v1alpha1/job-service/runs.go
  frontend/apps/web/app/(mgmt)/[account]/runs/[id]/components/JobRunActivityTable.tsx
  frontend/apps/web/app/(mgmt)/[account]/runs/[id]/components/JobRunActivityTable/columns.tsx
  frontend/apps/web/app/(mgmt)/[account]/runs/[id]/components/JobRunActivityTable/data-table-column-header.tsx
  frontend/apps/web/app/(mgmt)/[account]/runs/[id]/components/JobRunActivityTable/data-table.tsx
  frontend/apps/web/components/RunTImeline/RunTimeline.tsx
  frontend/apps/web/components/jobs/SchemaTable/SchemaColumnHeader.tsx
Labels: enhancement

#3457 Update new column addition strategies docs
  docs/docs/guides/new-column-addition-strategies.md
Labels: Docs

#3476 NEOS-1801: updates helm charts to disable ee features by default
  charts/neosync/README.md
  frontend/apps/web/charts/app/README.md
  frontend/apps/web/charts/app/values.yaml
Labels: bug

#3478 Updates run page to show new schema reconciliation errors
  frontend/apps/web/app/(mgmt)/[account]/runs/[id]/components/JobRunActivityErrors.tsx
Labels: bug

#3479 add new changelogs for march
  docs/blog/2025-03-13-slack-integration.md
  docs/blog/2025-03-27-pii-detection-batch.md
Labels: Docs
