Repository nucleuscloud/neosync, pull requests merged in 2025-01, with the labels that each got.

#3085 Adds backoff interceptor to worker neosync clients
  go.mod
  go.sum
  internal/connectrpc/interceptors/retry/interceptor.go
  internal/connectrpc/interceptors/retry/interceptor_test.go
  worker/internal/cmds/worker/serve/serve.go
Labels: enhancement

#3089 bumps most of the app non-major dependencies
  frontend/apps/web/components/connections/ConnectionIcon.tsx
  frontend/apps/web/components/onboarding-checklist/Connect.tsx
  frontend/apps/web/package.json
  frontend/package-lock.json
  frontend/package.json
Labels: dependencies

#3097 Readds grouping of docs dependabot PRs
  .github/dependabot.yml
Labels: ignore-for-release

#3079 NEOS-1692:add in transform uuid transformer
  backend/gen/go/protos/mgmt/v1alpha1/transformer.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/transformer.pb.json.go
  backend/protos/mgmt/v1alpha1/transformer.proto
  backend/services/mgmt/v1alpha1/transformers-service/system_transformers.go
  backend/sql/postgresql/models/transformers.go
  docs/docs/transformers/gen-javascript-transformer.md
  docs/openapi/mgmt/v1alpha1/anonymization.openapi.yaml
  docs/openapi/mgmt/v1alpha1/job.openapi.yaml
  docs/openapi/mgmt/v1alpha1/transformer.openapi.yaml
  docs/protos/mgmt/v1alpha1/transformer.proto.mdx
  docs/protos/proto_docs.json
  frontend/apps/web/@types/neosync-transformers.d.ts
  frontend/apps/web/yup-validations/transformer-validations.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/transformer_pb.ts
  internal/benthos/benthos-builder/builders/processors.go
  python/src/neosync/mgmt/v1alpha1/transformer_pb2.py
  python/src/neosync/mgmt/v1alpha1/transformer_pb2.pyi
  worker/pkg/benthos/transformers/gen_neosync_transformers.go
  worker/pkg/benthos/transformers/gen_transform_uuid.go
  worker/pkg/benthos/transformers/transform_uuid.go
  worker/pkg/benthos/transformers/transform_uuid_test.go
  worker/pkg/benthos/transformers/transformer_initializer.go
  worker/pkg/benthos/transformers/transformer_initializer_test.go
  worker/pkg/rng/rng.go
Labels: enhancement, Feature

#3099 NEOS-1630: Updates Subset Table to be more performant
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/subsets/components/SubsetCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/job-form-validations.ts
  frontend/apps/web/app/(mgmt)/[account]/new/job/subset/page.tsx
  frontend/apps/web/components/FastTable/FastTable.tsx
  frontend/apps/web/components/FastTable/MemoizedCell.tsx
  frontend/apps/web/components/FastTable/MemoizedRow.tsx
  frontend/apps/web/components/jobs/JobMappingTable/JobMappingTable.tsx
  frontend/apps/web/components/jobs/subsets/EditItem.tsx
  frontend/apps/web/components/jobs/subsets/EditItemDialog.tsx
  frontend/apps/web/components/jobs/subsets/SubsetTable/ActionsCell.tsx
  frontend/apps/web/components/jobs/subsets/SubsetTable/Columns.tsx
  frontend/apps/web/components/jobs/subsets/SubsetTable/RootTableCell.tsx
  frontend/apps/web/components/jobs/subsets/SubsetTable/SubsetTable.tsx
  frontend/apps/web/components/jobs/subsets/subset-table/SubsetTable.tsx
  frontend/apps/web/components/jobs/subsets/subset-table/column.tsx
  frontend/apps/web/components/jobs/subsets/subset-table/data-table-column-header.tsx
  frontend/apps/web/components/jobs/subsets/subset-table/data-table.tsx
  frontend/apps/web/components/jobs/subsets/utils.ts
Labels: enhancement, Tech Debt

#3101 NEOS-1696, NEOS-1682: Adds bulk apply subsets, Adds mssql subset validation
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/hooks/components/JobConfigSqlForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/subsets/components/SubsetCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/job-form-validations.ts
  frontend/apps/web/app/(mgmt)/[account]/new/job/subset/page.tsx
  frontend/apps/web/components/jobs/subsets/SubsetTable/Columns.tsx
  frontend/apps/web/components/jobs/subsets/SubsetTable/SubsetTable.tsx
  frontend/apps/web/components/jobs/subsets/SubsetTable/SubsetTableToolbar.tsx
  frontend/apps/web/components/jobs/subsets/edit/EditItem.tsx
  frontend/apps/web/components/jobs/subsets/edit/EditItemDialog.tsx
  frontend/apps/web/components/jobs/subsets/edit/EditItems.tsx
  frontend/apps/web/components/jobs/subsets/edit/WhereEditor.tsx
  frontend/apps/web/components/jobs/subsets/edit/useOnBulkEditItemSave.tsx
  frontend/apps/web/components/jobs/subsets/edit/useOnEditItemSave.tsx
  frontend/apps/web/components/jobs/subsets/utils.ts
  frontend/apps/web/libs/hooks/monaco/useMonacoOnMount.ts
  frontend/apps/web/libs/hooks/monaco/useMonacoResizer.ts
  frontend/apps/web/libs/hooks/monaco/useMonacoTheme.ts
Labels: enhancement

#3102 NEOS-1683: Transformer Config form now properly appears on clone
  frontend/apps/web/app/(mgmt)/[account]/new/transformer/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/[id]/components/UpdateTransformerForm.tsx
Labels: bug

#3090 Refactors connection data service
  backend/gen/go/db/dbschemas/mysql/system.sql.go
  backend/internal/auth/jwt/mock_JwtValidator.go
  backend/internal/cmds/mgmt/serve/connect/cmd.go
  backend/internal/connectiondata/aws-s3.go
  backend/internal/connectiondata/connectiondata.go
  backend/internal/connectiondata/dynamodb.go
  backend/internal/connectiondata/gcp.go
  backend/internal/connectiondata/mongodb.go
  backend/internal/connectiondata/sql.go
  backend/internal/neosyncdb/mock_DBTX.go
  backend/pkg/dbschemas/sql/mysql/queries/system.sql
  backend/pkg/integration-test/mux.go
  backend/pkg/mongomanager/manager.go
  backend/pkg/mongomanager/utils.go
  backend/pkg/sqlconnect/mock_SqlDbContainer.go
  backend/pkg/sqlmanager/mock_SqlDatabase.go
  backend/pkg/sqlmanager/mssql/mssql-manager.go
  backend/pkg/sqlmanager/mysql/mysql-manager.go
  backend/pkg/sqlmanager/postgres/postgres-manager.go
  backend/pkg/sqlmanager/sql-manager.go
  backend/services/mgmt/v1alpha1/connection-data-service/connection-data.go
  backend/services/mgmt/v1alpha1/connection-data-service/connection-data_test.go
  backend/services/mgmt/v1alpha1/connection-data-service/service.go
  cli/internal/cmds/neosync/sync/sync.go
  cli/internal/cmds/neosync/sync/sync_integration_test.go
  go.mod
  internal/connection-manager/mock_ConnectionProvider.go
  internal/database-record-mapper/builder/builder.go
  internal/database-record-mapper/database-record-mapper.go
  internal/database-record-mapper/dynamodb/mapper.go
  internal/database-record-mapper/dynamodb/mapper_test.go
  internal/database-record-mapper/mongodb/mapper.go
  internal/database-record-mapper/mongodb/mapper_test.go
  internal/database-record-mapper/mssql/mapper.go
  internal/database-record-mapper/mssql/mapper_test.go
  internal/database-record-mapper/mysql/mapper.go
  internal/database-record-mapper/mysql/mapper_test.go
  internal/database-record-mapper/postgres/mapper.go
  internal/database-record-mapper/postgres/mapper_test.go
  internal/dynamodb/utils.go
  internal/dynamodb/utils_test.go
  internal/ee/presidio/mock_AnalyzeInterface.go
  internal/ee/presidio/mock_AnonymizeInterface.go
  internal/sqlserver/utils.go
  internal/sqlserver/utils_test.go
  worker/pkg/benthos/dynamodb/input.go
  worker/pkg/benthos/dynamodb/input_test.go
  worker/pkg/benthos/dynamodb/output.go
  worker/pkg/benthos/dynamodb/output_test.go
  worker/pkg/benthos/mongodb/common.go
  worker/pkg/benthos/mongodb/common_test.go
  worker/pkg/benthos/mongodb/input.go
  worker/pkg/benthos/neosync_connection_data/neosync_connection_data_input.go
  worker/pkg/benthos/neosync_connection_data/neosync_connection_data_input_test.go
  worker/pkg/benthos/sql/input_sql_raw.go
  worker/pkg/benthos/sql/input_sql_raw_test.go
  worker/pkg/benthos/sql/processor_neosync_pgx.go
  worker/pkg/benthos/sql/processor_neosync_pgx_test.go
  worker/pkg/query-builder/insert-query-builder.go
  worker/pkg/query-builder/query-builder.go
Labels: Devex

#3103 NEOS-1695: support creating schemas if they dont exist not just table
  backend/pkg/sqlmanager/mysql/mysql-manager.go
  backend/pkg/sqlmanager/postgres/postgres-manager.go
  backend/services/mgmt/v1alpha1/job-service/runs.go
  docs/docs/connections/postgres.md
  docs/docs/guides/incremental-additions.md
  frontend/apps/web/components/jobs/Form/MssqlDBDestinationOptionsForm.tsx
  frontend/apps/web/components/jobs/Form/MysqlDBDestinationOptionsForm.tsx
  frontend/apps/web/components/jobs/Form/PostgresDBDestinationOptionsForm.tsx
  internal/ee/mssql-manager/ee-mssql-manager.go
  worker/pkg/workflows/datasync/activities/run-sql-init-table-stmts/init-statement-builder.go
Labels: enhancement

#3106 NEOS-1697: Fixes Composite Mysql Indices, Optimizes SQL Manager Integration Tests
  backend/pkg/sqlmanager/mysql/integration_test.go
  backend/pkg/sqlmanager/mysql/mysql-manager.go
  backend/pkg/sqlmanager/mysql/mysql-manager_integration_test.go
  backend/pkg/sqlmanager/mysql/testdata/init.sql
  backend/pkg/sqlmanager/mysql/testdata/setup.sql
Labels: bug, Tech Debt

#3108 NEOS-1671: add ability to source a connection url from an env var
  backend/gen/go/db/dbschemas/mysql/system.sql.go
  backend/gen/go/protos/mgmt/v1alpha1/connection.pb.go
  backend/internal/cmds/mgmt/serve/connect/cmd.go
  backend/internal/ee/rbac/policy.go
  backend/pkg/dbconnect-config/mssql.go
  backend/pkg/dbconnect-config/mssql_test.go
  backend/pkg/dbconnect-config/mysql.go
  backend/pkg/dbconnect-config/mysql_test.go
  backend/pkg/dbconnect-config/postgres.go
  backend/pkg/dbconnect-config/postgres_test.go
  backend/pkg/integration-test/mux.go
  backend/protos/mgmt/v1alpha1/connection.proto
  backend/services/mgmt/v1alpha1/connection-service/connection.go
  backend/services/mgmt/v1alpha1/connection-service/service.go
  backend/services/mgmt/v1alpha1/integration_tests/connection-service_integration_test.go
  backend/sql/postgresql/models/models.go
  docs/docs/connections/mysql.md
  docs/docs/connections/postgres.md
  docs/docs/connections/sqlserver.md
  docs/openapi/mgmt/v1alpha1/connection.openapi.yaml
  docs/openapi/neosync.mgmt.v1alpha1.yaml
  docs/protos/mgmt/v1alpha1/connection.proto.mdx
  docs/protos/proto_docs.json
  frontend/apps/web/app/(mgmt)/[account]/connections/[id]/components/MssqlForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/connections/[id]/components/MysqlForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/connections/[id]/components/PostgresForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/connections/[id]/components/connection-component.tsx
  frontend/apps/web/app/(mgmt)/[account]/connections/util.ts
  frontend/apps/web/app/(mgmt)/[account]/new/connection/mssql/MssqlForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/connection/mysql/MysqlForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/connection/postgres/PostgresForm.tsx
  frontend/apps/web/components/guards/OSSOnlyGuard.tsx
  frontend/apps/web/yup-validations/connections.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/connection_pb.ts
  python/src/neosync/mgmt/v1alpha1/connection_pb2.py
  python/src/neosync/mgmt/v1alpha1/connection_pb2.pyi
Labels: enhancement

#3111 Fix generate jobs critical error check
  internal/benthos/benthos-builder/builders/generate-ai.go
  internal/benthos/benthos-builder/builders/generate.go
  worker/pkg/benthos/config.go
  worker/pkg/benthos/error/output_error.go
  worker/pkg/benthos/utils.go
Labels: bug

#3113 Fixes postgres identity column query
  backend/gen/go/db/dbschemas/postgresql/system.sql.go
  backend/pkg/dbschemas/sql/postgresql/queries/system.sql
Labels: bug

#3109 Updates math rand to v2
  worker/pkg/rng/rng.go
Labels: Improvement

#3112 NEOS-1700: adds 01-02 changelog
  docs/blog/2025-01-02-v5.md
Labels: Docs

#3120 NEOS-1698: updates address transformers to use corpii for better performance
  worker/pkg/benthos/transformers/data-sets/address_address1_gen.go
  worker/pkg/benthos/transformers/data-sets/address_address2_gen.go
  worker/pkg/benthos/transformers/data-sets/address_city_gen.go
  worker/pkg/benthos/transformers/data-sets/address_state_gen.go
  worker/pkg/benthos/transformers/data-sets/address_zipcode_gen.go
  worker/pkg/benthos/transformers/data-sets/addresses.go
  worker/pkg/benthos/transformers/data-sets/area_codes.go
  worker/pkg/benthos/transformers/data-sets/country_codes.go
  worker/pkg/benthos/transformers/data-sets/country_gen.go
  worker/pkg/benthos/transformers/data-sets/countrycode_gen.go
  worker/pkg/benthos/transformers/data-sets/datasets/addresses/address1.txt
  worker/pkg/benthos/transformers/data-sets/datasets/addresses/address2.txt
  worker/pkg/benthos/transformers/data-sets/datasets/addresses/city.txt
  worker/pkg/benthos/transformers/data-sets/datasets/addresses/state.txt
  worker/pkg/benthos/transformers/data-sets/datasets/addresses/zipcode.txt
  worker/pkg/benthos/transformers/data-sets/datasets/countries.txt
  worker/pkg/benthos/transformers/data-sets/datasets/country_codes.txt
  worker/pkg/benthos/transformers/data-sets/datasets/us_areacodes.txt
  worker/pkg/benthos/transformers/data-sets/datasets/us_state_codes.txt
  worker/pkg/benthos/transformers/data-sets/datasets/us_states.txt
  worker/pkg/benthos/transformers/data-sets/generators.go
  worker/pkg/benthos/transformers/data-sets/states.go
  worker/pkg/benthos/transformers/data-sets/usareacode_gen.go
  worker/pkg/benthos/transformers/data-sets/usstate_gen.go
  worker/pkg/benthos/transformers/data-sets/usstatecode_gen.go
  worker/pkg/benthos/transformers/generate_city.go
  worker/pkg/benthos/transformers/generate_city_test.go
  worker/pkg/benthos/transformers/generate_country.go
  worker/pkg/benthos/transformers/generate_country_test.go
  worker/pkg/benthos/transformers/generate_email_test.go
  worker/pkg/benthos/transformers/generate_full_address.go
  worker/pkg/benthos/transformers/generate_int64_phone_number.go
  worker/pkg/benthos/transformers/generate_state.go
  worker/pkg/benthos/transformers/generate_state_test.go
  worker/pkg/benthos/transformers/generate_street_address.go
  worker/pkg/benthos/transformers/generate_zipcode.go
  worker/pkg/benthos/transformers/generate_zipcode_test.go
  worker/pkg/benthos/transformers/transform_int64_phone_number.go
  worker/pkg/benthos/transformers/utils/integer_utils.go
  worker/pkg/benthos/transformers/utils/string_utils.go
  worker/scripts/addresses_datasets/.gitignore
  worker/scripts/addresses_datasets/addresses.json
  worker/scripts/addresses_datasets/generate_addresses.py
  worker/scripts/name_dataset/README.md
Labels: enhancement

#3123 NEOS-1703: add support for entity specific anonymization
  backend/gen/go/protos/mgmt/v1alpha1/transformer.pb.go
  backend/protos/mgmt/v1alpha1/transformer.proto
  docs/openapi/mgmt/v1alpha1/anonymization.openapi.yaml
  docs/openapi/mgmt/v1alpha1/job.openapi.yaml
  docs/openapi/mgmt/v1alpha1/transformer.openapi.yaml
  docs/openapi/neosync.mgmt.v1alpha1.yaml
  docs/protos/mgmt/v1alpha1/transformer.proto.mdx
  docs/protos/proto_docs.json
  frontend/packages/sdk/src/client/mgmt/v1alpha1/transformer_pb.ts
  internal/ee/transformers/functions/functions.go
  internal/ee/transformers/functions/functions_test.go
  python/src/neosync/mgmt/v1alpha1/transformer_pb2.py
  python/src/neosync/mgmt/v1alpha1/transformer_pb2.pyi
Labels: enhancement

#3126 Updates javascript transformer docs
  docs/docs/transformers/neosync-types.md
  docs/docs/transformers/sql-javascript-transformer.md
  docs/sidebars.ts
Labels: Docs

#3124 Adds on conflict update feature for Mysql
  backend/gen/go/protos/mgmt/v1alpha1/job.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/job.pb.json.go
  backend/protos/mgmt/v1alpha1/job.proto
  backend/sql/postgresql/models/models.go
  cli/internal/cmds/neosync/sync/sync_integration_test.go
  docs/openapi/mgmt/v1alpha1/job.openapi.yaml
  docs/protos/mgmt/v1alpha1/job.proto.mdx
  docs/protos/proto_docs.json
  frontend/apps/web/app/(mgmt)/[account]/jobs/util.ts
  frontend/apps/web/components/jobs/Form/DestinationOptionsForm.tsx
  frontend/apps/web/components/jobs/Form/MysqlDBDestinationOptionsForm.tsx
  frontend/apps/web/yup-validations/jobs.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/job_pb.ts
  internal/benthos/benthos-builder/builders/generate-ai.go
  internal/benthos/benthos-builder/builders/generate.go
  internal/benthos/benthos-builder/builders/sql-util.go
  internal/benthos/benthos-builder/builders/sql.go
  internal/testutil/testdata/mssql/alltypes/job-mappings.go
  internal/testutil/testdata/mysql/alltypes/create-tables.sql
  internal/testutil/testdata/mysql/alltypes/job-mappings.go
  internal/testutil/testdata/mysql/humanresources/create-tables.sql
  internal/testutil/testdata/mysql/humanresources/job-mappings.go
  python/src/neosync/mgmt/v1alpha1/job_pb2.py
  python/src/neosync/mgmt/v1alpha1/job_pb2.pyi
  tools/generators/test_jobmapping_generator/main.go
  worker/pkg/benthos/config.go
  worker/pkg/benthos/sql/output_sql_insert.go
  worker/pkg/integration-test/mysql_test.go
  worker/pkg/integration-test/types.go
  worker/pkg/integration-test/workflow-integration_test.go
  worker/pkg/query-builder/insert-query-builder.go
  worker/pkg/query-builder/query-builder.go
Labels: Feature

#3138 NEOS-1713: fixes run logs automatically turning on in k8s
  backend/internal/cmds/mgmt/serve/connect/cmd.go
Labels: bug

#3141 Adds Postgres on conflict update
  backend/gen/go/protos/mgmt/v1alpha1/job.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/job.pb.json.go
  backend/protos/mgmt/v1alpha1/job.proto
  backend/sql/postgresql/models/models.go
  cli/internal/cmds/neosync/sync/sync.go
  docs/openapi/mgmt/v1alpha1/job.openapi.yaml
  docs/openapi/neosync.mgmt.v1alpha1.yaml
  docs/protos/mgmt/v1alpha1/job.proto.mdx
  docs/protos/proto_docs.json
  frontend/apps/web/app/(mgmt)/[account]/jobs/util.ts
  frontend/apps/web/components/jobs/Form/DestinationOptionsForm.tsx
  frontend/apps/web/components/jobs/Form/PostgresDBDestinationOptionsForm.tsx
  frontend/apps/web/yup-validations/jobs.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/job_pb.ts
  internal/benthos/benthos-builder/builders/sql-util.go
  internal/benthos/benthos-builder/builders/sql.go
  python/src/neosync/mgmt/v1alpha1/job_pb2.py
  python/src/neosync/mgmt/v1alpha1/job_pb2.pyi
  worker/pkg/benthos/config.go
  worker/pkg/benthos/sql/output_sql_insert.go
  worker/pkg/query-builder/insert-query-builder.go
  worker/pkg/query-builder/query-builder.go
Labels: Feature

#3125 NEOS-1704: Adds Neosync Transformers to Anonymization API
  .mockery.yml
  backend/gen/go/protos/mgmt/v1alpha1/transformer.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/transformer.pb.json.go
  backend/protos/mgmt/v1alpha1/transformer.proto
  backend/services/mgmt/v1alpha1/anonymization-service/anonymization.go
  backend/services/mgmt/v1alpha1/integration_tests/anonymization-service_integration_test.go
  docs/openapi/mgmt/v1alpha1/anonymization.openapi.yaml
  docs/openapi/mgmt/v1alpha1/job.openapi.yaml
  docs/openapi/mgmt/v1alpha1/transformer.openapi.yaml
  docs/openapi/neosync.mgmt.v1alpha1.yaml
  docs/protos/mgmt/v1alpha1/transformer.proto.mdx
  docs/protos/proto_docs.json
  frontend/packages/sdk/src/client/mgmt/v1alpha1/transformer_pb.ts
  internal/ee/transformers/functions/functions.go
  internal/ee/transformers/functions/functions_test.go
  internal/ee/transformers/functions/mock_NeosyncOperatorApi.go
  internal/json-anonymizer/json-anonymizer.go
  internal/json-anonymizer/json-anonymizer_test.go
  internal/json-anonymizer/neosync-operator.go
  internal/json-anonymizer/neosync-operator_test.go
  internal/queue/queue.go
  internal/queue/queue_test.go
  python/src/neosync/mgmt/v1alpha1/transformer_pb2.py
  python/src/neosync/mgmt/v1alpha1/transformer_pb2.pyi
  tools/go.sum
  worker/pkg/benthos/transformers/transformer_initializer.go
  worker/pkg/benthos/transformers/transformer_initializer_test.go
Labels: enhancement

#3143 Adds table does not exist to critical errors list
  worker/pkg/benthos/utils.go
Labels: enhancement

#3144 Adds grafana pyroscope to worker and backend
  backend/internal/cmds/mgmt/serve/connect/cmd.go
  go.mod
  go.sum
  internal/pyroscope/logger/logger.go
  internal/pyroscope/pyroscope.go
  worker/internal/cmds/worker/serve/serve.go
Labels: Tech Debt

#3149 Updates Genai Job table to handle non-string columns
  frontend/apps/web/app/(mgmt)/[account]/jobs/util.ts
  frontend/apps/web/app/(mgmt)/[account]/new/job/aigenerate/single/schema/SampleTable/SampleTable.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/aigenerate/single/schema/SampleTable/SampleTableColumns.tsx
  worker/pkg/benthos/openai_generate/openai_generate.go
Labels: bug

#3150 NEOS-1719: fixes generate job surfacing unsupported transformers
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/DataGenConnectionCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/generate/single/schema/page.tsx
Labels: bug

#3151 NEOS-1718: fixes apply default transformers button incorrectly showing for some …
  frontend/apps/web/components/jobs/JobMappingTable/JobMappingTable.tsx
  frontend/apps/web/components/jobs/NosqlTable/NosqlTable.tsx
  frontend/apps/web/components/jobs/SchemaTable/SchemaTable.tsx
Labels: bug

#3153 1-16 changelog
  docs/blog/2025-01-16-anon-api-synthetic-data.md
Labels: documentation

#3140 add in gtag for neosync cloud conversion tracking
  frontend/apps/web/app/BaseLayout.tsx
  frontend/apps/web/app/api/config/config.ts
  frontend/apps/web/app/config/app-config.ts
  frontend/apps/web/app/layout.tsx
  frontend/apps/web/components/providers/googleTag-provider.tsx
  frontend/apps/web/components/providers/unify-provider.tsx
Labels: enhancement

#3156 Updates mysql and postgres docs to include notes about database differences
  docs/docs/connections/mysql.md
  docs/docs/connections/postgres.md
Labels: Docs

#3160 NEOS-1712: Adds ability to specify user defined transformers in anonymization api
  .mockery.yml
  backend/internal/cmds/mgmt/serve/connect/cmd.go
  backend/pkg/integration-test/mux.go
  backend/services/mgmt/v1alpha1/anonymization-service/anonymization.go
  backend/services/mgmt/v1alpha1/anonymization-service/service.go
  backend/services/mgmt/v1alpha1/integration_tests/anonymization-service_integration_test.go
  internal/json-anonymizer/json-anonymizer.go
  internal/json-anonymizer/json-anonymizer_test.go
  internal/json-anonymizer/neosync-operator.go
  internal/json-anonymizer/neosync-operator_test.go
  worker/pkg/benthos/transformers/mock_UserDefinedTransformerResolver.go
  worker/pkg/benthos/transformers/transformer_initializer.go
  worker/pkg/benthos/transformers/transformer_initializer_test.go
Labels: enhancement

#3155 Adds warnings to jobmapping validator
  backend/gen/go/protos/mgmt/v1alpha1/job.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/job.pb.json.go
  backend/internal/utils/utils.go
  backend/protos/mgmt/v1alpha1/job.proto
  backend/services/mgmt/v1alpha1/job-service/jobs.go
  docs/openapi/mgmt/v1alpha1/job.openapi.yaml
  docs/openapi/neosync.mgmt.v1alpha1.yaml
  docs/protos/mgmt/v1alpha1/job.proto.mdx
  docs/protos/proto_docs.json
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/DataGenConnectionCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/DataSyncConnectionCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/util.ts
  frontend/apps/web/app/(mgmt)/[account]/jobs/util.ts
  frontend/apps/web/app/(mgmt)/[account]/new/job/generate/single/schema/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/schema/page.tsx
  frontend/apps/web/components/jobs/SchemaTable/FormErrorsCard.tsx
  frontend/apps/web/components/jobs/SchemaTable/SchemaTable.tsx
  frontend/packages/sdk/src/client/mgmt/v1alpha1/job_pb.ts
  internal/benthos/benthos-builder/builders/sql-util.go
  internal/benthos/benthos-builder/builders/sql.go
  internal/job/job.go
  internal/job/jobmapping-validator.go
  internal/job/jobmapping-validator_test.go
  python/src/neosync/mgmt/v1alpha1/job_pb2.py
  python/src/neosync/mgmt/v1alpha1/job_pb2.pyi
Labels: enhancement

#3161 Fixes halt on new column addition being too strict
  internal/benthos/benthos-builder/builders/benthos-builder_test.go
  internal/benthos/benthos-builder/builders/sql-util.go
Labels: bug

#3164 Postgres - handle datatypes created in schemas not found in jobmappings
  backend/gen/go/db/dbschemas/postgresql/system.sql.go
  backend/pkg/dbschemas/sql/postgresql/queries/system.sql
  backend/pkg/sqlmanager/postgres/postgres-manager.go
Labels: bug

#3162 Postgres init schema - improved handling of creating extensions
  backend/gen/go/db/dbschemas/postgresql/querier.go
  backend/gen/go/db/dbschemas/postgresql/system.sql.go
  backend/pkg/dbschemas/sql/postgresql/queries/system.sql
  backend/pkg/sqlmanager/postgres/postgres-manager.go
  backend/pkg/sqlmanager/shared/types.go
  worker/pkg/workflows/datasync/activities/run-sql-init-table-stmts/init-statement-builder.go
Labels: bug

#3163 NEOS-1712: Adds support for JS in Anon Api
  .mockery.yml
  backend/services/mgmt/v1alpha1/integration_tests/anonymization-service_integration_test.go
  internal/benthos/benthos-builder/builders/processors.go
  internal/benthos/benthos-builder/builders/processors_test.go
  internal/benthos_slogger/logger.go
  internal/javascript/functions/benthos/functions.go
  internal/javascript/functions/benthos/functions_test.go
  internal/javascript/functions/functions.go
  internal/javascript/functions/neosync/functions.go
  internal/javascript/functions/neosync/functions_test.go
  internal/javascript/javascript.go
  internal/javascript/userland/userland.go
  internal/javascript/userland/userland_test.go
  internal/javascript/vm/console_logger.go
  internal/javascript/vm/vm.go
  internal/javascript/vm/vm_test.go
  internal/json-anonymizer/json-anonymizer.go
  internal/json-anonymizer/neosync-operator.go
  internal/json-anonymizer/neosync-operator_test.go
  tools/go.mod
  tools/go.sum
  worker/pkg/benthos/default_transform/processor.go
  worker/pkg/benthos/default_transform/processor_test.go
  worker/pkg/benthos/environment/environment.go
  worker/pkg/benthos/javascript/benthos_value_api.go
  worker/pkg/benthos/javascript/casts.go
  worker/pkg/benthos/javascript/functions.go
  worker/pkg/benthos/javascript/ifs/http.go
  worker/pkg/benthos/javascript/ifs/os.go
  worker/pkg/benthos/javascript/ifs/os_test.go
  worker/pkg/benthos/javascript/logger.go
  worker/pkg/benthos/javascript/processor.go
  worker/pkg/benthos/javascript/processor_test.go
  worker/pkg/benthos/javascript/vm.go
  worker/pkg/benthos/transformer_executor/anon_value_api.go
  worker/pkg/benthos/transformer_executor/anon_value_api_test.go
  worker/pkg/benthos/transformer_executor/executor.go
  worker/pkg/benthos/transformer_executor/executor_test.go
  worker/pkg/benthos/transformer_executor/mock_UserDefinedTransformerResolver.go
Labels: enhancement, Tech Debt

#3171 Updates schema initialization to log individual statement with corresponding error
  worker/pkg/workflows/datasync/activities/run-sql-init-table-stmts/init-statement-builder.go
Labels: enhancement

#3172 NEOS-1605: Fixes job run logs not loading, fixes inability to specify log level
  frontend/apps/web/app/api/accounts/[accountId]/runs/[id]/logs/route.ts
  frontend/apps/web/libs/hooks/useGetJobRunLogs.ts
Labels: bug

#3173 Adds GetRunLogs RPC, fixes loki-backend log sorting
  backend/gen/go/db/dbschemas/postgresql/mock_Querier.go
  backend/gen/go/protos/mgmt/v1alpha1/job.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/job.pb.json.go
  backend/gen/go/protos/mgmt/v1alpha1/mgmtv1alpha1connect/job.connect.go
  backend/gen/go/protos/mgmt/v1alpha1/mgmtv1alpha1connect/mock_JobServiceClient.go
  backend/gen/go/protos/mgmt/v1alpha1/mgmtv1alpha1connect/mock_JobServiceHandler.go
  backend/protos/mgmt/v1alpha1/job.proto
  backend/services/mgmt/v1alpha1/job-service/runs.go
  docs/openapi/mgmt/v1alpha1/job.openapi.yaml
  docs/openapi/neosync.mgmt.v1alpha1.yaml
  docs/protos/mgmt/v1alpha1/job.proto.mdx
  docs/protos/proto_docs.json
  frontend/apps/web/app/(mgmt)/[account]/runs/[id]/components/JobRunLogs.tsx
  frontend/apps/web/app/(mgmt)/[account]/runs/[id]/components/JobRunLogsTable/columns.tsx
  frontend/apps/web/app/(mgmt)/[account]/runs/[id]/page.tsx
  frontend/apps/web/app/api/accounts/[accountId]/runs/[id]/logs/route.ts
  frontend/apps/web/libs/hooks/useGetJobRunLogs.ts
  frontend/apps/web/shared/index.ts
  frontend/apps/web/shared/types.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/job_pb.ts
  python/src/neosync/mgmt/v1alpha1/job_pb2.py
  python/src/neosync/mgmt/v1alpha1/job_pb2.pyi
  python/src/neosync/mgmt/v1alpha1/job_pb2_grpc.py
Labels: Tech Debt

#3169 Setup continuous benchmarking
  .github/workflows/go.yml
  tools/generators/neosync_transformer_generator/main.go
  worker/pkg/benthos/transformers/benchmarks_test.go
  worker/pkg/benthos/transformers/generate_bool.go
  worker/pkg/benthos/transformers/generate_business_name.go
  worker/pkg/benthos/transformers/generate_card_number.go
  worker/pkg/benthos/transformers/generate_categorical.go
  worker/pkg/benthos/transformers/generate_city.go
  worker/pkg/benthos/transformers/generate_city_test.go
  worker/pkg/benthos/transformers/generate_country.go
  worker/pkg/benthos/transformers/generate_email.go
  worker/pkg/benthos/transformers/generate_email_test.go
  worker/pkg/benthos/transformers/generate_first_name.go
  worker/pkg/benthos/transformers/generate_float.go
  worker/pkg/benthos/transformers/generate_full_address.go
  worker/pkg/benthos/transformers/generate_full_name.go
  worker/pkg/benthos/transformers/generate_gender.go
  worker/pkg/benthos/transformers/generate_int64.go
  worker/pkg/benthos/transformers/generate_int64_phone_number.go
  worker/pkg/benthos/transformers/generate_international_phone_number.go
  worker/pkg/benthos/transformers/generate_ip_address.go
  worker/pkg/benthos/transformers/generate_last_name.go
  worker/pkg/benthos/transformers/generate_random_string.go
  worker/pkg/benthos/transformers/generate_sha256hash.go
  worker/pkg/benthos/transformers/generate_ssn.go
  worker/pkg/benthos/transformers/generate_state.go
  worker/pkg/benthos/transformers/generate_street_address.go
  worker/pkg/benthos/transformers/generate_string_phone_number.go
  worker/pkg/benthos/transformers/generate_unix_timestamp.go
  worker/pkg/benthos/transformers/generate_username.go
  worker/pkg/benthos/transformers/generate_utc_timestamp.go
  worker/pkg/benthos/transformers/generate_uuid.go
  worker/pkg/benthos/transformers/generate_zipcode.go
  worker/pkg/benthos/transformers/generator_utils.go
  worker/pkg/benthos/transformers/transform_character_scramble.go
  worker/pkg/benthos/transformers/transform_e164_phone_number.go
  worker/pkg/benthos/transformers/transform_email.go
  worker/pkg/benthos/transformers/transform_first_name.go
  worker/pkg/benthos/transformers/transform_float.go
  worker/pkg/benthos/transformers/transform_full_name.go
  worker/pkg/benthos/transformers/transform_int64.go
  worker/pkg/benthos/transformers/transform_int64_phone_number.go
  worker/pkg/benthos/transformers/transform_lastname.go
  worker/pkg/benthos/transformers/transform_string.go
  worker/pkg/benthos/transformers/transform_string_phone_number.go
  worker/pkg/benthos/transformers/transform_uuid.go
Labels: Devex

#3174 NEOS-1724: updates runs logs query to use close time if workflow has ended
  backend/services/mgmt/v1alpha1/job-service/runs.go
  internal/javascript/vm/vm_test.go
Labels: enhancement

#3177 Updates job run page to show schema initialization errors
  frontend/apps/web/app/(mgmt)/[account]/runs/[id]/components/JobRunActivityErrors.tsx
  frontend/apps/web/app/(mgmt)/[account]/runs/[id]/page.tsx
  frontend/apps/web/components/providers/query-provider.tsx
Labels: enhancement

#3176 Add benchmark count of 6 for better benchstat analysis
  .github/workflows/go.yml
Labels: Devex

#3178 NEOS-1624: add more tags to the logs page
  backend/gen/go/protos/mgmt/v1alpha1/job.pb.go
  backend/internal/loki/loki.go
  backend/internal/loki/loki_test.go
  backend/internal/loki/types.go
  backend/protos/mgmt/v1alpha1/job.proto
  backend/services/mgmt/v1alpha1/job-service/runs.go
  docs/openapi/mgmt/v1alpha1/job.openapi.yaml
  docs/openapi/neosync.mgmt.v1alpha1.yaml
  docs/protos/mgmt/v1alpha1/job.proto.mdx
  docs/protos/proto_docs.json
  frontend/apps/web/app/(mgmt)/[account]/runs/[id]/components/JobRunLogs.tsx
  frontend/apps/web/app/(mgmt)/[account]/runs/[id]/components/JobRunLogsTable/columns.tsx
  frontend/apps/web/app/(mgmt)/[account]/runs/[id]/components/JobRunLogsTable/data-table-column-header.tsx
  frontend/apps/web/app/(mgmt)/[account]/runs/[id]/components/JobRunLogsTable/data-table.tsx
  frontend/apps/web/components/FastTable/FastTable.tsx
  frontend/apps/web/components/FastTable/MemoizedRow.tsx
  frontend/packages/sdk/src/client/mgmt/v1alpha1/job_pb.ts
  python/src/neosync/mgmt/v1alpha1/job_pb2.py
  python/src/neosync/mgmt/v1alpha1/job_pb2.pyi
Labels: enhancement

#3181 Set retry to 1 on generate AI job. To avoid wasting tokens
  internal/benthos/benthos-builder/builders/generate-ai.go
Labels: Improvement

#3179 Updates job mapping validator to return error codes
  backend/gen/go/protos/mgmt/v1alpha1/job.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/job.pb.json.go
  backend/protos/mgmt/v1alpha1/job.proto
  backend/services/mgmt/v1alpha1/job-service/jobs.go
  docs/openapi/mgmt/v1alpha1/job.openapi.yaml
  docs/openapi/neosync.mgmt.v1alpha1.yaml
  docs/protos/mgmt/v1alpha1/job.proto.mdx
  docs/protos/proto_docs.json
  frontend/packages/sdk/src/client/mgmt/v1alpha1/job_pb.ts
  internal/job/jobmapping-validator.go
  internal/job/jobmapping-validator_test.go
  python/src/neosync/mgmt/v1alpha1/job_pb2.py
  python/src/neosync/mgmt/v1alpha1/job_pb2.pyi
Labels: enhancement

#3182 NEOS-1708: optimize sql disconnections and busy signals during sync
  .mockery.yml
  backend/pkg/sqlconnect/mock_SqlDbContainer.go
  backend/pkg/sqlconnect/sql-connector.go
  backend/pkg/sqldbtx/dbtx.go
  backend/pkg/sqldbtx/mock_DBTX.go
  backend/pkg/sqlretry/dbtx_retry.go
  backend/pkg/sqlretry/dbtx_retry_test.go
  backend/pkg/sqlretry/deadlock.go
  backend/pkg/sqlretry/deadlock_test.go
  internal/connection-manager/providers/sqlprovider/provider.go
  worker/pkg/benthos/config.go
  worker/pkg/benthos/sql/output_sql_insert.go
  worker/pkg/benthos/sql/output_sql_update.go
  worker/pkg/benthos/sql/retry.go
  worker/pkg/benthos/sql/retry_test.go
Labels: enhancement

#3184 Adds table missing alert to destination cards on Job page
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/destinations/components/DestinationConnectionCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/destinations/page.tsx
Labels: enhancement

#3185 NEOS-1727, NEOS-1676, NEOS-1728: Adds docs for hooks, rbac, and more
  docs/docs/deploy/environment-variables.md
  docs/docs/guides/ai-synthetic-data-generation.md
  docs/docs/guides/column-removal-strategies.md
  docs/docs/guides/initializing-schemas.md
  docs/docs/guides/job-hooks.md
  docs/docs/guides/new-column-addition-strategies.md
  docs/docs/guides/rbac.md
  docs/sidebars.ts
  docs/src/CustomComponents/IconHandler.tsx
  docs/src/css/overrides.css
  docs/static/img/hooks/job-hooks-overview.png
  docs/static/img/hooks/new-hook-form.png
  docs/static/img/rbac/invite-user.png
  docs/static/img/rbac/update-role.png
Labels: Docs

#3188 NEOS-1726: updates test regex to be more permissive
  worker/pkg/benthos/transformer_executor/executor_test.go
Labels: Tech Debt

#3196 NEOS-1731: Fixes init types to properly handle python type hints
  python/src/neosync/__init__.py
  python/src/neosync/__init__.pyi
Labels: bug

#3198 NEOS-1730: mysql index statements broken when using non column
  backend/gen/go/db/dbschemas/mysql/system.sql.go
  backend/pkg/dbschemas/sql/mysql/queries/system.sql
  backend/pkg/dbschemas/sql/mysql/schema/system.sql
  backend/pkg/sqlmanager/mysql/mysql-manager.go
  backend/pkg/sqlmanager/mysql/mysql-manager_integration_test.go
  backend/pkg/sqlmanager/mysql/testdata/setup.sql
Labels: bug

#3199 re-enables worker db logs, adds more err wraps to benthos insert
  backend/internal/neosyncdb/db.go
  backend/pkg/sqlconnect/sql-connector.go
  internal/pgx-slog/adapter.go
  internal/sshtunnel/connectors/postgrestunconnector/connector.go
  worker/pkg/benthos/sql/output_sql_insert.go
  worker/pkg/benthos/utils.go
  worker/pkg/query-builder/insert-query-builder.go
Labels: enhancement

#3201 Fixes Stripe Billing Anchor Edge Case
  backend/internal/cmds/mgmt/serve/connect/cmd.go
  backend/services/mgmt/v1alpha1/integration_tests/anonymization-service_integration_test.go
  backend/services/mgmt/v1alpha1/integration_tests/user-account-service_integration_test.go
  backend/services/mgmt/v1alpha1/user-account-service/billing.go
  backend/services/mgmt/v1alpha1/user-account-service/users.go
  go.mod
  go.sum
  internal/billing/mock_Interface.go
  internal/billing/stripe-billing.go
  internal/billing/stripe-billing_test.go
Labels: bug

#3202 Fixes PG Data Type Arrays on schema init, re-enables integration tests in CI
  .github/workflows/go.yml
  backend/gen/go/db/dbschemas/postgresql/system.sql.go
  backend/pkg/dbschemas/sql/postgresql/queries/system.sql
  backend/pkg/sqlmanager/mssql/mssql-manager_integration_test.go
  backend/pkg/sqlmanager/postgres/postgres-manager_integration_test.go
  backend/pkg/sqlmanager/postgres/testdata/setup.sql
  backend/pkg/sqlretry/dbtx_retry.go
  cli/internal/cmds/neosync/sync/config.go
  internal/connectrpc/interceptors/retry/interceptor.go
  internal/connectrpc/interceptors/retry/interceptor_test.go
  internal/sshtunnel/dialer_integration_test.go
  internal/testutil/testcontainers/sqlserver/sqlserver.go
  worker/pkg/integration-test/dynamodb_test.go
Labels: bug

#3206 Fixes latest job run from s3 not found, fixes data race in ssh dialer
  backend/internal/connectiondata/aws-s3.go
  internal/sshtunnel/dialer.go
Labels: bug

#3208 fixing circular dependency run order
  backend/pkg/table-dependency/circular-dependencies.go
  backend/pkg/table-dependency/circular-dependencies_test.go
  backend/pkg/table-dependency/table-dependency.go
  internal/benthos/benthos-builder/builders/processors_test.go
  worker/pkg/workflows/datasync/activities/sync/activity_test.go
Labels: bug
