Repository nucleuscloud/neosync, pull requests merged in 2025-03, with the labels that each got.

#3314 fixes postgres deadlock detection
  backend/pkg/sqlretry/dbtx_retry.go
  backend/pkg/sqlretry/dbtx_retry_test.go
  backend/pkg/sqlretry/deadlock.go
  backend/pkg/sqlretry/deadlock_test.go
  internal/neosyncdb/util.go
Labels: bug

#3316 Adds more handling for SQL Networking Errs, Updates SSH Dialer Backoff Strategy
  backend/pkg/sqlretry/dbtx_retry.go
  backend/pkg/sqlretry/dbtx_retry_test.go
  internal/backoffutil/backoff-util.go
  internal/integration-tests/sshtunnel/dialer_integration_test.go
  internal/sshtunnel/dialer.go
Labels: enhancement

#3303 NEOS-1755: add slack app integration for account hooks
  .cursor/rules/golang-sub-tests.mdc
  .cursor/rules/mockery.mdc
  .mockery.yml
  backend/gen/go/db/account-hooks.sql.go
  backend/gen/go/db/mock_Querier.go
  backend/gen/go/db/models.go
  backend/gen/go/db/querier.go
  backend/gen/go/protos/mgmt/v1alpha1/account_hook.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/account_hook.pb.json.go
  backend/gen/go/protos/mgmt/v1alpha1/mgmtv1alpha1connect/account_hook.connect.go
  backend/gen/go/protos/mgmt/v1alpha1/mgmtv1alpha1connect/mock_AccountHookServiceClient.go
  backend/internal/cmds/mgmt/serve/connect/cmd.go
  backend/internal/ee/hooks/accounts/service.go
  backend/pkg/integration-test/integration-test.go
  backend/pkg/integration-test/mux.go
  backend/protos/mgmt/v1alpha1/account_hook.proto
  backend/services/mgmt/v1alpha1/account-hooks-service/service.go
  backend/sql/postgresql/queries/account-hooks.sql
  backend/sql/postgresql/schema/20250224175040_slack-oauth.down.sql
  backend/sql/postgresql/schema/20250224175040_slack-oauth.up.sql
  docs/docs/deploy/environment-variables.md
  docs/openapi/mgmt/v1alpha1/account_hook.openapi.yaml
  docs/openapi/neosync.mgmt.v1alpha1.yaml
  docs/protos/mgmt/v1alpha1/account_hook.proto.mdx
  docs/protos/proto_docs.json
  frontend/apps/web/api-only/neosync-context.ts
  frontend/apps/web/app/(mgmt)/[account]/settings/hooks/components/AccountHookSlackForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/settings/hooks/components/EditHookButton.tsx
  frontend/apps/web/app/(mgmt)/[account]/settings/hooks/components/EditHookForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/settings/hooks/components/FormInputs.tsx
  frontend/apps/web/app/(mgmt)/[account]/settings/hooks/components/NewHookForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/settings/hooks/components/stores.ts
  frontend/apps/web/app/(mgmt)/[account]/settings/hooks/components/validation.ts
  frontend/apps/web/app/api/config/config.ts
  frontend/apps/web/app/api/slack/oauth/callback/route.ts
  frontend/apps/web/app/config/app-config.ts
  frontend/apps/web/app/hooks/slack/page.tsx
  frontend/apps/web/components/ui/toggle.tsx
  frontend/packages/sdk/src/client/mgmt/v1alpha1/account_hook_pb.ts
  go.mod
  go.sum
  internal/ee/slack/mock_Interface.go
  internal/ee/slack/slack.go
  internal/ee/slack/slack_test.go
  internal/encrypt/sym/encrypt.go
  internal/encrypt/sym/encrypt_test.go
  internal/encrypt/sym/mock_Interface.go
  internal/integration-tests/api/account-hooks-service_integration_test.go
  python/src/neosync/mgmt/v1alpha1/account_hook_pb2.py
  python/src/neosync/mgmt/v1alpha1/account_hook_pb2.pyi
  python/src/neosync/mgmt/v1alpha1/account_hook_pb2_grpc.py
  worker/pkg/workflows/ee/account_hooks/activities/execute/activity.go
  worker/pkg/workflows/ee/account_hooks/activities/execute/activity_test.go
Labels: enhancement

#3320 fixes job run events message on frontend not surfacing enough details
  backend/internal/dtomaps/job-runs.go
Labels: Blocked

#3323 update changelog
  docs/blog/2025-02-13-webhooks.md
Labels: Docs

#3324 Changelog227
  docs/blog/2025-02-27-connection-security.md
Labels: Docs

#3322 NEOS-1762: reworks account provider to handle selected account more effectively
  frontend/apps/web/app/(mgmt)/[account]/settings/members/components/MemberTable.tsx
  frontend/apps/web/app/invite/page.tsx
  frontend/apps/web/components/providers/account-provider.tsx
  frontend/apps/web/components/site-header/AccountStatusHandler.tsx
  frontend/apps/web/components/site-header/Upgrade.tsx
Labels: bug

#3325 sets slack failure message to red circle emoji
  backend/internal/ee/hooks/accounts/service.go
Labels: enhancement

#3326 Adds sendslackmessage to allowed worker procedures
  backend/internal/cmds/mgmt/serve/connect/cmd.go
Labels: bug

#3327 NEOS-1760: Adds logic that automatically joins a slack channel
  backend/internal/ee/hooks/accounts/service.go
  backend/internal/ee/hooks/accounts/service_test.go
  internal/integration-tests/api/account-hooks-service_integration_test.go
Labels: enhancement

#3328 changes account hooks to not halt on first failure
  worker/pkg/workflows/ee/account_hooks/workflow/workflow.go
  worker/pkg/workflows/ee/account_hooks/workflow/workflow_test.go
Labels: bug

#3329 adds docs on slack hooks
  docs/blog/2025-02-13-webhooks.md
  docs/docs/guides/account-hooks.md
Labels: Docs

#3331 Minimal style change to surface tables in listbox that overflow
  frontend/apps/web/components/DualListBox/columns.tsx
Labels: bug

#3330 reworks go cursor rules
  .cursor/rules/golang-sub-tests.mdc
  .cursor/rules/golang-tests.mdc
  .cursor/rules/mockery.mdc
Labels: ignore-for-release

#3333 NEOS-1765: update slack hooks to link to neosync resources
  backend/internal/cmds/mgmt/serve/connect/cmd.go
  backend/internal/ee/hooks/accounts/service.go
  compose.dev.yml
  compose.yml
  worker/pkg/workflows/ee/account_hooks/activities/execute/activity.go
Labels: enhancement

#3334 update date on changelog
  docs/blog/2025-02-27-connection-security.md
Labels: Docs

#3318 Postgres - adds support for exclusions, partitioned tables and fixes constraint query
  backend/gen/go/db/dbschemas/postgresql/querier.go
  backend/gen/go/db/dbschemas/postgresql/system.sql.go
  backend/pkg/dbschemas/sql/postgresql/queries/system.sql
  backend/pkg/sqlmanager/postgres/postgres-manager.go
  backend/pkg/sqlmanager/shared/types.go
  internal/integration-tests/sqlmanager/postgres/testdata/setup.sql
  internal/integration-tests/worker/workflow/postgres_test.go
  internal/testutil/testcontainers/postgres/postgres.go
  internal/testutil/testdata/postgres/complex/create-tables.sql
  internal/testutil/testdata/postgres/complex/inserts.sql
  internal/testutil/testdata/postgres/complex/job-mappings.go
Labels: bug, enhancement

#3335 moves backend/internal/connectiondata to internal/connectiondata
  .mockery.yml
  backend/internal/cmds/mgmt/serve/connect/cmd.go
  backend/pkg/integration-test/mux.go
  backend/services/mgmt/v1alpha1/connection-data-service/service.go
  backend/services/mgmt/v1alpha1/job-service/service.go
  internal/connectiondata/aws-s3.go
  internal/connectiondata/connectiondata.go
  internal/connectiondata/dynamodb.go
  internal/connectiondata/gcp.go
  internal/connectiondata/mongodb.go
  internal/connectiondata/sql.go
  internal/gcp/client.go
  internal/gcp/manager.go
  internal/gcp/mock_ClientInterface.go
  internal/gcp/mock_ManagerInterface.go
Labels: Tech Debt

#3340 Fixes postgres sequence reset
  backend/pkg/sqlmanager/postgres/postgres-manager.go
  worker/pkg/workflows/datasync/activities/run-sql-init-table-stmts/init-statement-builder.go
Labels: bug

#3339 Postgres support for partitioned tables
  backend/gen/go/db/dbschemas/postgresql/mock_Querier.go
  backend/gen/go/db/dbschemas/postgresql/querier.go
  backend/gen/go/db/dbschemas/postgresql/system.sql.go
  backend/pkg/dbschemas/sql/postgresql/queries/system.sql
  backend/pkg/sqlmanager/postgres/postgres-manager.go
  backend/pkg/sqlmanager/shared/types.go
  internal/benthos/benthos-builder/builders/sql.go
  internal/integration-tests/worker/workflow/postgres_test.go
  internal/testutil/testcontainers/postgres/postgres.go
  internal/testutil/testdata/postgres/complex/create-tables.sql
  internal/testutil/testdata/postgres/complex/inserts.sql
Labels: bug, enhancement

#3346 NEOS-1772: adds in account hook events to pii detect job workflow
  worker/internal/cmds/worker/serve/serve.go
  worker/pkg/workflows/datasync/workflow/workflow.go
  worker/pkg/workflows/ee/piidetect/workflows/job/workflow.go
  worker/pkg/workflows/ee/piidetect/workflows/job/workflow_test.go
  worker/pkg/workflows/ee/piidetect/workflows/register/register.go
  worker/pkg/workflows/shared/util.go
  worker/pkg/workflows/shared/util_test.go
Labels: enhancement

#3348 NEOS-1756: updates not found logic for schedules
  internal/temporal/clientmanager/manager.go
Labels: bug

#3350 NEOS-1775: fixes export mappings to use correct format
  frontend/apps/web/components/jobs/SchemaTable/useOnExportMappings.tsx
Labels: bug

#3351 Moves init schema to separate workflow + creates schema manager
  frontend/apps/web/app/(mgmt)/[account]/runs/[id]/components/JobRunActivityErrors.tsx
  internal/integration-tests/worker/workflow/datasync-workflow.go
  internal/schema-manager/mssql/mssql.go
  internal/schema-manager/mysql/mysql.go
  internal/schema-manager/not-supported/not-supported.go
  internal/schema-manager/postgres/postgres.go
  internal/schema-manager/schema-manager.go
  internal/schema-manager/shared/shared.go
  internal/schema-manager/shared/shared_test.go
  worker/internal/cmds/worker/serve/serve.go
  worker/pkg/workflows/datasync/activities/run-sql-init-table-stmts/init-statement-builder.go
  worker/pkg/workflows/datasync/activities/sync-activity-opts/activity.go
  worker/pkg/workflows/datasync/workflow/register/register.go
  worker/pkg/workflows/datasync/workflow/workflow.go
  worker/pkg/workflows/datasync/workflow/workflow_test.go
  worker/pkg/workflows/schemainit/activities/init-schema/activity.go
  worker/pkg/workflows/schemainit/activities/init-schema/init-schema.go
  worker/pkg/workflows/schemainit/activities/init-schema/init-schema_test.go
  worker/pkg/workflows/schemainit/workflow/register/register.go
  worker/pkg/workflows/schemainit/workflow/workflow.go
  worker/pkg/workflows/schemainit/workflow/workflow_test.go
Labels: Devex

#3353 NEOS-1769: expose pii detection in new job workflow as well as job
  .cursor/rules/frontend.mdc
  .mockery.yml
  backend/gen/go/db/jobs.sql.go
  backend/gen/go/db/mock_Querier.go
  backend/gen/go/db/querier.go
  backend/gen/go/protos/mgmt/v1alpha1/job.pb.go
  backend/internal/auth/jwt/mock_JwtValidator.go
  backend/protos/mgmt/v1alpha1/job.proto
  backend/services/mgmt/v1alpha1/job-service/jobs.go
  backend/sql/postgresql/queries/jobs.sql
  docs/openapi/mgmt/v1alpha1/job.openapi.yaml
  docs/openapi/neosync.mgmt.v1alpha1.yaml
  docs/protos/mgmt/v1alpha1/job.proto.mdx
  docs/protos/proto_docs.json
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/layout.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/PiiDetectConnectionCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/SourceConnectionCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/util.ts
  frontend/apps/web/app/(mgmt)/[account]/jobs/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/util.ts
  frontend/apps/web/app/(mgmt)/[account]/new/job/JobsProgressSteps.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/define/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/job-form-validations.ts
  frontend/apps/web/app/(mgmt)/[account]/new/job/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/piidetect/connect/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/piidetect/schema/FormInputs.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/piidetect/schema/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/piidetect/schema/stores.ts
  frontend/apps/web/app/api/config/config.ts
  frontend/apps/web/app/config/app-config.ts
  frontend/apps/web/components/DualListBox/DualListBox.tsx
  frontend/apps/web/components/DualListBox/columns.tsx
  frontend/apps/web/components/forms/FormHeader.tsx
  frontend/packages/sdk/src/client/mgmt/v1alpha1/job_pb.ts
  internal/connection-manager/mock_ConnectionProvider.go
  internal/ee/presidio/mock_AnalyzeInterface.go
  internal/ee/presidio/mock_AnonymizeInterface.go
  internal/mocks/github.com/jackc/pgx/v5/mock_Tx.go
  internal/neosyncdb/mock_DBTX.go
  internal/temporal/clientmanager/mock_Interface.go
  python/src/neosync/mgmt/v1alpha1/job_pb2.py
  python/src/neosync/mgmt/v1alpha1/job_pb2.pyi
  worker/pkg/workflows/ee/piidetect/workflows/table/activities/mock_OpenAiCompletionsClient.go
Labels: enhancement

#3360 Fix SQL update processor removing primary key from message
  internal/benthos/benthos-builder/builders/sql.go
  internal/integration-tests/worker/workflow/postgres_test.go
Labels: bug

#3361 Updates complex postgres test to test table values
  cli/internal/cmds/neosync/sync/sync_integration_test.go
  internal/integration-tests/worker/workflow/mssql_test.go
  internal/integration-tests/worker/workflow/mysql_test.go
  internal/integration-tests/worker/workflow/postgres_test.go
  internal/testutil/testdata/postgres/complex/job-mappings.go
  internal/testutil/testdata/verify.go
Labels: Devex

#3364 Adds more errors to sql retry handler
  backend/pkg/sqlretry/dbtx_retry.go
  internal/sshtunnel/dialer.go
Labels: enhancement

#3362 NEOS-1770: update job run page for pii detection jobs to show pii
  backend/gen/go/db/mock_Querier.go
  backend/gen/go/db/querier.go
  backend/gen/go/db/runcontexts.sql.go
  backend/gen/go/protos/mgmt/v1alpha1/job.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/job.pb.json.go
  backend/gen/go/protos/mgmt/v1alpha1/mgmtv1alpha1connect/job.connect.go
  backend/gen/go/protos/mgmt/v1alpha1/mgmtv1alpha1connect/mock_JobServiceClient.go
  backend/gen/go/protos/mgmt/v1alpha1/mgmtv1alpha1connect/mock_JobServiceHandler.go
  backend/internal/dtomaps/job-runs.go
  backend/pkg/integration-test/integration-test.go
  backend/protos/mgmt/v1alpha1/job.proto
  backend/services/mgmt/v1alpha1/job-service/runs.go
  backend/sql/postgresql/queries/runcontexts.sql
  docs/openapi/mgmt/v1alpha1/job.openapi.yaml
  docs/openapi/neosync.mgmt.v1alpha1.yaml
  docs/protos/mgmt/v1alpha1/job.proto.mdx
  docs/protos/proto_docs.json
  frontend/apps/web/app/(mgmt)/[account]/runs/[id]/components/JobRunLogs.tsx
  frontend/apps/web/app/(mgmt)/[account]/runs/[id]/components/JobRunPiiDetectionTable/CategoryCell.tsx
  frontend/apps/web/app/(mgmt)/[account]/runs/[id]/components/JobRunPiiDetectionTable/ConfidenceCell.tsx
  frontend/apps/web/app/(mgmt)/[account]/runs/[id]/components/JobRunPiiDetectionTable/JobRunPiiDetectionTable.tsx
  frontend/apps/web/app/(mgmt)/[account]/runs/[id]/components/JobRunPiiDetectionTable/ReporterTypeCell.tsx
  frontend/apps/web/app/(mgmt)/[account]/runs/[id]/components/JobRunPiiDetectionTable/columns.tsx
  frontend/apps/web/app/(mgmt)/[account]/runs/[id]/page.tsx
  frontend/apps/web/components/guards/PiiDetectionJobGuard.tsx
  frontend/apps/web/libs/utils.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/job_pb.ts
  internal/integration-tests/api/jobs-service_integration_test.go
  python/src/neosync/mgmt/v1alpha1/job_pb2.py
  python/src/neosync/mgmt/v1alpha1/job_pb2.pyi
  python/src/neosync/mgmt/v1alpha1/job_pb2_grpc.py
  worker/pkg/workflows/ee/piidetect/workflows/job/activities/activities.go
  worker/pkg/workflows/ee/piidetect/workflows/job/activities/activities_test.go
  worker/pkg/workflows/ee/piidetect/workflows/job/workflow_test.go
  worker/pkg/workflows/ee/piidetect/workflows/table/activities/activities.go
  worker/pkg/workflows/ee/piidetect/workflows/table/activities/activities_test.go
  worker/pkg/workflows/ee/piidetect/workflows/table/workflow.go
  worker/pkg/workflows/ee/piidetect/workflows/table/workflow_test.go
Labels: enhancement

#3365 NEOS-1767: optimize pii detection getalltables sql method
  backend/gen/go/db/dbschemas/mysql/mock_Querier.go
  backend/gen/go/db/dbschemas/mysql/querier.go
  backend/gen/go/db/dbschemas/mysql/system.sql.go
  backend/gen/go/db/dbschemas/postgresql/mock_Querier.go
  backend/gen/go/db/dbschemas/postgresql/querier.go
  backend/gen/go/db/dbschemas/postgresql/system.sql.go
  backend/pkg/dbschemas/sql/mysql/queries/system.sql
  backend/pkg/dbschemas/sql/mysql/schema/system.sql
  backend/pkg/dbschemas/sql/postgresql/queries/system.sql
  backend/pkg/mssql-querier/mock_Querier.go
  backend/pkg/mssql-querier/querier.go
  backend/pkg/mssql-querier/system.sql.go
  backend/pkg/sqlmanager/mock_SqlDatabase.go
  backend/pkg/sqlmanager/mssql/mssql-manager.go
  backend/pkg/sqlmanager/mysql/mysql-manager.go
  backend/pkg/sqlmanager/postgres/postgres-manager.go
  backend/pkg/sqlmanager/shared/types.go
  backend/pkg/sqlmanager/sql-manager.go
  internal/connectiondata/sql.go
  internal/integration-tests/sqlmanager/mssql/mssql-manager_integration_test.go
  internal/integration-tests/sqlmanager/mysql/mysql-manager_integration_test.go
  internal/integration-tests/sqlmanager/postgres/postgres-manager_integration_test.go
Labels: Tech Debt

#3367 NEOS-1779: add rpc for exposing schemas and tables to pii detection
  backend/gen/go/protos/mgmt/v1alpha1/connection_data.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/connection_data.pb.json.go
  backend/gen/go/protos/mgmt/v1alpha1/mgmtv1alpha1connect/connection_data.connect.go
  backend/protos/mgmt/v1alpha1/connection_data.proto
  backend/services/mgmt/v1alpha1/connection-data-service/connection-data.go
  docs/openapi/mgmt/v1alpha1/connection_data.openapi.yaml
  docs/openapi/neosync.mgmt.v1alpha1.yaml
  docs/protos/mgmt/v1alpha1/connection_data.proto.mdx
  docs/protos/proto_docs.json
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/PiiDetectConnectionCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/piidetect/schema/FormInputs.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/piidetect/schema/page.tsx
  frontend/packages/sdk/src/client/mgmt/v1alpha1/connection_data_pb.ts
  internal/connectiondata/aws-s3.go
  internal/connectiondata/connectiondata.go
  internal/connectiondata/dynamodb.go
  internal/connectiondata/gcp.go
  internal/connectiondata/mock_ConnectionDataService.go
  internal/connectiondata/mongodb.go
  internal/connectiondata/sql.go
  python/src/neosync/mgmt/v1alpha1/connection_data_pb2.py
  python/src/neosync/mgmt/v1alpha1/connection_data_pb2.pyi
  python/src/neosync/mgmt/v1alpha1/connection_data_pb2_grpc.py
Labels: enhancement

#3363 Updates Mysql init schema to add new columns
  backend/pkg/sqlmanager/mssql/mssql-manager.go
  backend/pkg/sqlmanager/mysql/mysql-manager.go
  backend/pkg/sqlmanager/postgres/postgres-manager.go
  backend/pkg/sqlmanager/shared/types.go
  internal/benthos/benthos-builder/builders/sql.go
  internal/integration-tests/sqlmanager/postgres/postgres-manager_integration_test.go
  internal/integration-tests/worker/workflow/mysql_test.go
  internal/integration-tests/worker/workflow/workflow-integration_test.go
  internal/schema-manager/mssql/mssql.go
  internal/schema-manager/mysql/mysql.go
  internal/schema-manager/not-supported/not-supported.go
  internal/schema-manager/postgres/postgres.go
  internal/schema-manager/schema-manager.go
  internal/schema-manager/shared/shared.go
  internal/testutil/testdata/gen_jobmappings_config.json
  internal/testutil/testdata/mysql/schema-init/alter-job-mappings.go
  internal/testutil/testdata/mysql/schema-init/alter-statements.sql
  internal/testutil/testdata/mysql/schema-init/create-tables.sql
  internal/testutil/testdata/mysql/schema-init/job-mappings.go
  worker/pkg/benthos/config.go
  worker/pkg/benthos/sql/output_sql_insert.go
  worker/pkg/query-builder/insert-query-builder.go
  worker/pkg/workflows/datasync/activities/sync-activity-opts/activity.go
  worker/pkg/workflows/datasync/workflow/workflow.go
  worker/pkg/workflows/schemainit/activities/reconcile-schema/activity.go
  worker/pkg/workflows/schemainit/activities/reconcile-schema/reconcile-schema.go
  worker/pkg/workflows/schemainit/workflow/register/register.go
  worker/pkg/workflows/schemainit/workflow/workflow.go
Labels: enhancement

#3368 NEOS-1780: add support for pii detection job cloning
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/components/JobCloneButton.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/util.ts
  frontend/apps/web/app/(mgmt)/[account]/new/job/piidetect/schema/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/piidetect/schema/stores.ts
Labels: enhancement

#3369 bumps go to 1.24
  backend/dev/build/Dockerfile.dev
  docker/Dockerfile.backend
  docker/Dockerfile.worker
  go.mod
  tools/go.mod
  worker/dev/build/Dockerfile.dev
Labels: Tech Debt

#3370 adds in logic to handle abandoned child workflows in job run event history
  backend/internal/dtomaps/job-runs.go
  backend/services/mgmt/v1alpha1/job-service/runs.go
  frontend/apps/web/app/(mgmt)/[account]/runs/[id]/components/JobRunActivityTable.tsx
  frontend/apps/web/app/(mgmt)/[account]/runs/[id]/components/JobRunActivityTable/columns.tsx
  frontend/apps/web/components/RunTImeline/RunTimeline.tsx
Labels: enhancement

#3379 NEOS-1782: Fixes confidence sorting fn in PII Detection Table
  frontend/apps/web/app/(mgmt)/[account]/runs/[id]/components/JobRunPiiDetectionTable/columns.tsx
Labels: bug

#3378 NEOS-1774 Update Mysql Init Schema to drop constraints and columns
  backend/pkg/sqlmanager/mock_SqlDatabase.go
  backend/pkg/sqlmanager/mssql/mssql-manager.go
  backend/pkg/sqlmanager/mysql/mysql-manager.go
  backend/pkg/sqlmanager/postgres/postgres-manager.go
  backend/pkg/sqlmanager/shared/fingerprint.go
  backend/pkg/sqlmanager/shared/fingerprint_test.go
  backend/pkg/sqlmanager/shared/types.go
  backend/pkg/sqlmanager/sql-manager.go
  internal/integration-tests/worker/workflow/mysql_test.go
  internal/schema-manager/mysql/mysql.go
  internal/schema-manager/shared/foreign-keys.go
  internal/schema-manager/shared/foreign-keys_test.go
  internal/schema-manager/shared/schema-diff.go
  internal/schema-manager/shared/schema-diff_test.go
  internal/schema-manager/shared/shared.go
  internal/testutil/testdata/mysql/schema-init/alter-statements.sql
  internal/testutil/testdata/mysql/schema-init/create-tables.sql
  internal/testutil/testdata/mysql/schema-init/job-mappings.go
Labels: enhancement

#3380 NEOS-1777: refactor workflow option labels to make sense for pii
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/components/ActivitySyncOptionsCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/define/components/WorkflowSettings.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/define/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/page.tsx
Labels: enhancement

#3384 Updates Mysql init schema to continue on error
  internal/schema-manager/mysql/mysql.go
Labels: enhancement

#3383 NEOS-1771: add support for incremental scans to pii detection
  backend/gen/go/protos/mgmt/v1alpha1/job.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/job.pb.json.go
  backend/protos/mgmt/v1alpha1/job.proto
  backend/services/mgmt/v1alpha1/job-service/runs.go
  docs/openapi/mgmt/v1alpha1/job.openapi.yaml
  docs/openapi/neosync.mgmt.v1alpha1.yaml
  docs/protos/mgmt/v1alpha1/job.proto.mdx
  docs/protos/proto_docs.json
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/PiiDetectConnectionCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/util.ts
  frontend/apps/web/app/(mgmt)/[account]/new/job/job-form-validations.ts
  frontend/apps/web/app/(mgmt)/[account]/new/job/piidetect/schema/FormInputs.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/piidetect/schema/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/piidetect/schema/stores.ts
  frontend/apps/web/app/(mgmt)/[account]/runs/[id]/page.tsx
  frontend/packages/sdk/src/client/mgmt/v1alpha1/job_pb.ts
  python/src/neosync/mgmt/v1alpha1/job_pb2.py
  python/src/neosync/mgmt/v1alpha1/job_pb2.pyi
  worker/internal/cmds/worker/serve/serve.go
  worker/pkg/workflows/ee/piidetect/workflows/job/activities/activities.go
  worker/pkg/workflows/ee/piidetect/workflows/job/activities/activities_test.go
  worker/pkg/workflows/ee/piidetect/workflows/job/workflow.go
  worker/pkg/workflows/ee/piidetect/workflows/job/workflow_test.go
  worker/pkg/workflows/ee/piidetect/workflows/register/register.go
  worker/pkg/workflows/ee/piidetect/workflows/table/activities/activities.go
  worker/pkg/workflows/ee/piidetect/workflows/table/workflow.go
Labels: enhancement

#3382 NEOS-1774: Adds dropping and updating triggers to Mysql Init Schema
  backend/pkg/sqlmanager/mysql/mysql-manager.go
  backend/pkg/sqlmanager/postgres/postgres-manager.go
  backend/pkg/sqlmanager/shared/fingerprint.go
  backend/pkg/sqlmanager/shared/types.go
  internal/integration-tests/worker/workflow/mysql_test.go
  internal/schema-manager/mysql/mysql.go
  internal/schema-manager/shared/schema-diff.go
  internal/schema-manager/shared/schema-diff_test.go
  internal/testutil/testdata/mysql/schema-init/alter-statements.sql
  internal/testutil/testdata/mysql/schema-init/create-tables.sql
  internal/testutil/testdata/mysql/schema-init/job-mappings.go
Labels: enhancement

#3385 NEOS-1778: updates pii detection images and icon
  frontend/apps/web/app/(mgmt)/[account]/new/job/page.tsx
Labels: enhancement

#3387 NEOS-1774: Updates Mysql Schema Init to handle dropping, recreating functions
  backend/gen/go/db/dbschemas/mysql/system.sql.go
  backend/pkg/dbschemas/sql/mysql/queries/system.sql
  backend/pkg/dbschemas/sql/mysql/schema/system.sql
  backend/pkg/sqlmanager/mssql/mssql-manager.go
  backend/pkg/sqlmanager/mysql/mysql-manager.go
  backend/pkg/sqlmanager/postgres/postgres-manager.go
  backend/pkg/sqlmanager/shared/fingerprint.go
  backend/pkg/sqlmanager/shared/fingerprint_test.go
  backend/pkg/sqlmanager/shared/types.go
  internal/integration-tests/worker/workflow/mysql_test.go
  internal/schema-manager/mysql/mysql.go
  internal/schema-manager/shared/schema-diff.go
  internal/schema-manager/shared/schema-diff_test.go
  internal/testutil/testdata/mysql/schema-init/alter-statements.sql
  internal/testutil/testdata/mysql/schema-init/create-tables.sql
Labels: enhancement

#3388 NEOS-1583: Adds ability to remove missing source columns from the mappings table
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/DataGenConnectionCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/DataSyncConnectionCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/generate/single/schema/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/new/job/schema/page.tsx
  frontend/apps/web/components/jobs/JobMappingTable/JobMappingTable.tsx
  frontend/apps/web/components/jobs/NosqlTable/NosqlTable.tsx
  frontend/apps/web/components/jobs/SchemaTable/SchemaTable.tsx
  frontend/apps/web/components/jobs/SchemaTable/SchemaTableToolBar.tsx
Labels: enhancement

#3386 NEOS-1783: Adds stable sort to pii report, adds ability to download report on fE
  backend/services/mgmt/v1alpha1/job-service/runs.go
  frontend/apps/web/app/(mgmt)/[account]/runs/[id]/components/JobRunPiiDetectionTable/JobRunPiiDetectionTable.tsx
  frontend/apps/web/package.json
  frontend/package-lock.json
Labels: enhancement

#3390 NEOS-1786: fixes memoization of constraints in job mapping schema table
  frontend/apps/web/components/jobs/SchemaTable/SchemaTable.tsx
Labels: bug

#3393 Fix jobmapping virtual foreign key validator + run configs run order validator
  internal/job/jobmapping-validator.go
  internal/job/jobmapping-validator_test.go
  internal/runconfigs/runconfigs.go
  internal/runconfigs/runconfigs_test.go
  worker/pkg/workflows/datasync/workflow/workflow.go
  worker/pkg/workflows/datasync/workflow/workflow_test.go
Labels: bug

#3397 NEOS-1774 Mysql init schema modify column comments
  backend/gen/go/db/dbschemas/mysql/system.sql.go
  backend/pkg/dbschemas/sql/mysql/queries/system.sql
  backend/pkg/dbschemas/sql/mysql/schema/system.sql
  backend/pkg/sqlmanager/mysql/mysql-manager.go
  backend/pkg/sqlmanager/shared/fingerprint.go
  backend/pkg/sqlmanager/shared/types.go
  internal/testutil/testdata/mysql/schema-init/alter-statements.sql
  internal/testutil/testdata/mysql/schema-init/create-tables.sql
Labels: enhancement

#3407 NEOS-1790: Updates Postgres schema drift to add new columns
  backend/gen/go/db/dbschemas/postgresql/system.sql.go
  backend/pkg/dbschemas/sql/postgresql/queries/system.sql
  backend/pkg/sqlmanager/postgres/postgres-manager.go
  backend/pkg/sqlmanager/shared/types.go
  internal/integration-tests/worker/workflow/datasync-workflow.go
  internal/integration-tests/worker/workflow/postgres_test.go
  internal/integration-tests/worker/workflow/workflow-integration_test.go
  internal/schema-manager/postgres/postgres.go
  internal/testutil/testdata/gen_jobmappings_config.json
  internal/testutil/testdata/postgres/schema-init/alter-job-mappings.go
  internal/testutil/testdata/postgres/schema-init/alter-statements.sql
  internal/testutil/testdata/postgres/schema-init/create-tables.sql
  internal/testutil/testdata/postgres/schema-init/job-mappings.go
  worker/internal/cmds/worker/serve/serve.go
  worker/pkg/workflows/datasync/activities/sync-activity-opts/activity.go
  worker/pkg/workflows/datasync/activities/sync-activity-opts/activity_test.go
  worker/pkg/workflows/datasync/workflow/register/register.go
  worker/pkg/workflows/datasync/workflow/workflow.go
Labels: enhancement

#3408 Fixes Postgres insert identity with OnConflict bug + fixes flaky postgres integration test
  internal/integration-tests/worker/workflow/workflow-integration_test.go
  internal/testutil/testdata/postgres/schema-init/alter-job-mappings.go
  worker/pkg/query-builder/insert-query-builder.go
Labels: bug

#3405 NEOS-1789: adds Scramble Identity Transformer
  .mockery.yml
  backend/gen/go/protos/mgmt/v1alpha1/transformer.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/transformer.pb.json.go
  backend/pkg/integration-test/integration-test.go
  backend/protos/mgmt/v1alpha1/transformer.proto
  backend/services/mgmt/v1alpha1/transformers-service/system_transformers.go
  backend/sql/postgresql/models/transformers.go
  docs/docs/transformers/system.md
  docs/openapi/mgmt/v1alpha1/anonymization.openapi.yaml
  docs/openapi/mgmt/v1alpha1/job.openapi.yaml
  docs/openapi/mgmt/v1alpha1/transformer.openapi.yaml
  docs/openapi/neosync.mgmt.v1alpha1.yaml
  docs/protos/mgmt/v1alpha1/transformer.proto.mdx
  docs/protos/proto_docs.json
  frontend/apps/web/yup-validations/transformer-validations.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/transformer_pb.ts
  internal/benthos/benthos-builder/benthos-builder.go
  internal/benthos/benthos-builder/builders/benthos-builder_test.go
  internal/benthos/benthos-builder/builders/processors.go
  internal/benthos/benthos-builder/builders/processors_test.go
  internal/benthos/benthos-builder/builders/sql.go
  internal/benthos/benthos-builder/generate-benthos.go
  internal/benthos/benthos-builder/internal/types.go
  internal/integration-tests/worker/workflow/datasync-workflow.go
  python/src/neosync/mgmt/v1alpha1/transformer_pb2.py
  python/src/neosync/mgmt/v1alpha1/transformer_pb2.pyi
  tools/generators/neosync_transformer_generator/main.go
  tools/go.mod
  tools/go.sum
  worker/internal/cmds/worker/serve/serve.go
  worker/pkg/benthos/environment/environment.go
  worker/pkg/benthos/transformer_executor/executor.go
  worker/pkg/benthos/transformers/gen_transform_identity_scramble.go
  worker/pkg/benthos/transformers/generate_business_name_test.go
  worker/pkg/benthos/transformers/generate_email_test.go
  worker/pkg/benthos/transformers/generate_first_name_test.go
  worker/pkg/benthos/transformers/generate_full_name_test.go
  worker/pkg/benthos/transformers/generate_last_name_test.go
  worker/pkg/benthos/transformers/generate_username_test.go
  worker/pkg/benthos/transformers/generator_utils.go
  worker/pkg/benthos/transformers/transform_email_test.go
  worker/pkg/benthos/transformers/transform_first_name_test.go
  worker/pkg/benthos/transformers/transform_full_name_test.go
  worker/pkg/benthos/transformers/transform_identity_scramble.go
  worker/pkg/benthos/transformers/transform_identity_scramble_test.go
  worker/pkg/benthos/transformers/transform_lastname_test.go
  worker/pkg/benthos/transformers/transform_uuid_test.go
  worker/pkg/benthos/transformers/utils/string_utils_test.go
  worker/pkg/rng/mock_Rand.go
  worker/pkg/rng/rng.go
  worker/pkg/workflows/datasync/workflow/workflow.go
  worker/pkg/workflows/tablesync/activities/sync/activity.go
  worker/pkg/workflows/tablesync/activities/sync/activity_test.go
  worker/pkg/workflows/tablesync/shared/identity-allocator.go
  worker/pkg/workflows/tablesync/shared/identity-allocator_test.go
  worker/pkg/workflows/tablesync/shared/mock_BlockAllocator.go
  worker/pkg/workflows/tablesync/workflow/register/register.go
  worker/pkg/workflows/tablesync/workflow/workflow.go
Labels: enhancement

#3415 Adds users todo, adds enforcer auto load policy for syncing
  backend/services/mgmt/v1alpha1/user-account-service/users.go
  internal/ee/rbac/enforcer/enforcer.go
Labels: bug

#3416 Clean up redis at the end of workflow
  internal/benthos/benthos-builder/builders/sql-util.go
  internal/benthos/benthos-builder/builders/sql.go
  worker/pkg/workflows/datasync/workflow/workflow.go
  worker/pkg/workflows/datasync/workflow/workflow_test.go
Labels: bug

#3417 NEOS-1791: Add Mysql init schema set and enum test
  internal/integration-tests/worker/workflow/mysql_test.go
  internal/integration-tests/worker/workflow/workflow-integration_test.go
  internal/testutil/testdata/mysql/schema-init/alter-job-mappings.go
  internal/testutil/testdata/mysql/schema-init/alter-statements.sql
  internal/testutil/testdata/mysql/schema-init/create-tables.sql
  internal/testutil/testdata/mysql/schema-init/job-mappings.go
Labels: Devex

#3419 NEOS-1558: Fixes multi-az SSH Tunnel, exposes check ssh tunnel on frontend
  backend/gen/go/protos/mgmt/v1alpha1/connection.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/connection.pb.json.go
  backend/gen/go/protos/mgmt/v1alpha1/mgmtv1alpha1connect/connection.connect.go
  backend/gen/go/protos/mgmt/v1alpha1/mgmtv1alpha1connect/mock_ConnectionServiceClient.go
  backend/pkg/sqlconnect/sql-connector.go
  backend/pkg/sqlconnect/sql-connector_test.go
  backend/protos/mgmt/v1alpha1/connection.proto
  backend/services/mgmt/v1alpha1/connection-service/connection.go
  docs/openapi/mgmt/v1alpha1/connection.openapi.yaml
  docs/openapi/neosync.mgmt.v1alpha1.yaml
  docs/protos/mgmt/v1alpha1/connection.proto.mdx
  docs/protos/proto_docs.json
  frontend/apps/web/app/(mgmt)/[account]/connections/util.ts
  frontend/apps/web/components/connections/forms/SharedFormInputs.tsx
  frontend/apps/web/components/connections/forms/mysql/MysqlForm.tsx
  frontend/apps/web/components/connections/forms/postgres/PostgresForm.tsx
  frontend/apps/web/components/connections/forms/sql-server/SqlServerForm.tsx
  frontend/packages/sdk/src/client/mgmt/v1alpha1/connection_pb.ts
  internal/sshtunnel/connectors/postgrestunconnector/connector.go
  internal/sshtunnel/dialer.go
  internal/sshtunnel/utils.go
  internal/sshtunnel/utils_test.go
  python/src/neosync/mgmt/v1alpha1/connection_pb2.py
  python/src/neosync/mgmt/v1alpha1/connection_pb2.pyi
  python/src/neosync/mgmt/v1alpha1/connection_pb2_grpc.py
Labels: bug, enhancement

#3421 NEOS-1795: personal->team conversion now properly sets up rbac on new personal account
  backend/services/mgmt/v1alpha1/user-account-service/users.go
Labels: bug

#3424 adds more logic for conflicts, updates to use our sql adapter
  go.mod
  go.sum
  internal/ee/rbac/enforcer/enforcer.go
  internal/ee/rbac/policy.go
Labels: bug

#3427 Fixes form inputs for error messages
  frontend/apps/web/components/connections/TestConnectionBadge.tsx
  frontend/apps/web/components/connections/forms/SharedFormInputs.tsx
Labels: bug

#3412 NEOS-1787: add auto map support to mysql
  backend/gen/go/db/dbschemas/mysql/system.sql.go
  backend/gen/go/protos/mgmt/v1alpha1/job.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/job.pb.json.go
  backend/pkg/dbschemas/sql/mysql/queries/system.sql
  backend/pkg/sqlmanager/mysql/mysql-manager.go
  backend/pkg/sqlmanager/shared/types.go
  backend/protos/mgmt/v1alpha1/job.proto
  backend/sql/postgresql/models/models.go
  docs/docs/guides/new-column-addition-strategies.md
  docs/openapi/mgmt/v1alpha1/job.openapi.yaml
  docs/openapi/neosync.mgmt.v1alpha1.yaml
  docs/protos/mgmt/v1alpha1/job.proto.mdx
  docs/protos/proto_docs.json
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/source/components/DataSyncConnectionCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/util.ts
  frontend/apps/web/app/(mgmt)/[account]/new/job/connect/page.tsx
  frontend/apps/web/components/jobs/Form/ColumnRemovalStrategyOptionsForm.tsx
  frontend/apps/web/components/jobs/Form/MysqlDBSourceOptionsForm.tsx
  frontend/apps/web/components/jobs/Form/NewColumnAdditionStrategyOptionsForm.tsx
  frontend/apps/web/components/jobs/Form/SourceOptionsForm.tsx
  frontend/apps/web/yup-validations/jobs.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/job_pb.ts
  internal/benthos/benthos-builder/builders/sql-util.go
  internal/benthos/benthos-builder/builders/sql-util_test.go
  internal/job/job.go
  python/src/neosync/mgmt/v1alpha1/job_pb2.py
  python/src/neosync/mgmt/v1alpha1/job_pb2.pyi
  worker/pkg/benthos/transformers/utils/integer_utils.go
  worker/pkg/benthos/transformers/utils/integer_utils_test.go
  worker/pkg/benthos/transformers/utils/string_utils.go
  worker/pkg/benthos/transformers/utils/string_utils_test.go
Labels: enhancement

#3409 NEOS-1790 Updates postgres init schema to drop constraints and columns
  backend/gen/go/db/dbschemas/postgresql/querier.go
  backend/gen/go/db/dbschemas/postgresql/system.sql.go
  backend/pkg/dbschemas/sql/postgresql/queries/system.sql
  backend/pkg/sqlmanager/mysql/mysql-manager.go
  backend/pkg/sqlmanager/postgres/postgres-manager.go
  backend/pkg/sqlmanager/shared/types.go
  internal/integration-tests/worker/workflow/postgres_test.go
  internal/schema-manager/mysql/mysql.go
  internal/schema-manager/postgres/postgres.go
  internal/testutil/testdata/postgres/schema-init/alter-statements.sql
  internal/testutil/testdata/postgres/schema-init/create-tables.sql
Labels: enhancement

#3429 adds more logging and wrapped errors to checking conn config, fixes golangci config
  .golangci.yaml
  backend/services/mgmt/v1alpha1/connection-service/connection.go
Labels: enhancement

#3431 NEOS-1799: Fix one column table on conflict update bug
  internal/integration-tests/worker/workflow/mysql_test.go
  internal/integration-tests/worker/workflow/postgres_test.go
  internal/testutil/testdata/mysql/schema-init/create-tables.sql
  internal/testutil/testdata/mysql/schema-init/job-mappings.go
  internal/testutil/testdata/postgres/schema-init/create-tables.sql
  internal/testutil/testdata/postgres/schema-init/job-mappings.go
  worker/pkg/query-builder/insert-query-builder.go
Labels: bug

#3432 NEOS-1800: fixes transformer sorts, adds tooltip for multi sorting
  frontend/apps/web/components/jobs/JobMappingTable/Columns.tsx
  frontend/apps/web/components/jobs/SchemaTable/SchemaColumnHeader.tsx
Labels: enhancement

#3434 updates makefile to pull prod images from latest
  Makefile
Labels: Devex

#3410 NEOS-1790 Postgres init schema handles dropping triggers and functions
  backend/pkg/sqlmanager/postgres/postgres-manager.go
  backend/pkg/sqlmanager/shared/types.go
  internal/integration-tests/worker/workflow/postgres_test.go
  internal/schema-manager/mysql/mysql.go
  internal/schema-manager/postgres/postgres.go
  internal/schema-manager/shared/foreign-keys.go
  internal/schema-manager/shared/schema-diff.go
  internal/testutil/testdata/postgres/schema-init/alter-statements.sql
  internal/testutil/testdata/postgres/schema-init/create-tables.sql
  internal/testutil/testdata/postgres/schema-init/job-mappings.go
Labels: enhancement
