Repository nucleuscloud/neosync, pull requests merged in 2025-02, with the labels that each got.

#3214 removes transform pii text from frontend
  frontend/apps/web/libs/hooks/useGetTransformersHandler.ts
Labels: bug

#3215 adds another error code to postgres retryable errors
  backend/pkg/sqlretry/dbtx_retry.go
Labels: enhancement

#3216 allows specifying hpa behavior for worker,api
  backend/charts/api/README.md
  backend/charts/api/templates/hpa.yaml
  backend/charts/api/values.yaml
  charts/neosync/README.md
  worker/charts/worker/README.md
  worker/charts/worker/templates/hpa.yaml
  worker/charts/worker/values.yaml
Labels: enhancement

#3217 fixes term graceperiod seconds, removes unused env var
  backend/charts/api/templates/_helpers.tpl
  backend/charts/api/templates/deployment.yaml
  docs/docs/deploy/environment-variables.md
  frontend/apps/web/charts/app/templates/_helpers.tpl
  frontend/apps/web/charts/app/templates/deployment.yaml
  worker/charts/worker/templates/_helpers.tpl
  worker/charts/worker/templates/deployment.yaml
Labels: enhancement

#3218 removes forceful stop channel in temporal activity
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/activity.go
  worker/pkg/workflows/datasync/activities/jobhooks-by-timing/activity.go
Labels: enhancement

#3219 Removes worker stop channel for sync activity
  worker/pkg/workflows/datasync/activities/sync/activity.go
  worker/pkg/workflows/datasync/activities/sync/activity_test.go
Labels: enhancement

#3221 Fix assignment to entry in nil map when providing attributes in mysql connection string
  backend/pkg/dbconnect-config/mysql.go
  backend/pkg/dbconnect-config/mysql_test.go
Labels: bug

#3170 Makes worker database value conversion to Go types strictly enforce error handling
  internal/database-record-mapper/dynamodb/mapper.go
  internal/database-record-mapper/dynamodb/mapper_test.go
  internal/database-record-mapper/mongodb/mapper.go
  internal/database-record-mapper/mongodb/mapper_test.go
  internal/database-record-mapper/mssql/mapper.go
  internal/database-record-mapper/mssql/mapper_test.go
  internal/database-record-mapper/mysql/mapper.go
  internal/database-record-mapper/mysql/mapper_test.go
  internal/database-record-mapper/postgres/mapper.go
  internal/database-record-mapper/postgres/mapper_test.go
  internal/neosync-types/bits.go
  worker/pkg/benthos/config.go
  worker/pkg/benthos/dynamodb/output.go
  worker/pkg/benthos/dynamodb/output_test.go
  worker/pkg/benthos/mongodb/common.go
  worker/pkg/benthos/mongodb/common_test.go
  worker/pkg/benthos/sql/processor_neosync_mssql.go
  worker/pkg/benthos/sql/processor_neosync_mssql_test.go
  worker/pkg/benthos/sql/processor_neosync_mysql.go
  worker/pkg/benthos/sql/processor_neosync_mysql_test.go
  worker/pkg/benthos/sql/processor_neosync_pgx.go
  worker/pkg/benthos/sql/processor_neosync_pgx_test.go
Labels: Devex

#3226 Fix logic to determine when table in cycle needs to insert and update
  backend/pkg/table-dependency/circular-dependencies.go
  backend/pkg/table-dependency/circular-dependencies_test.go
  backend/pkg/table-dependency/table-dependency.go
  backend/pkg/table-dependency/table-dependency_test.go
  internal/job/jobmapping-validator.go
Labels: bug

#3231 add in 130 changelog
  docs/blog/2025-01-30-upgrade-python-sdk.md
Labels: Docs

#3229 Fixes postgres uuid extension failing in test setup
  internal/integration-tests/worker/workflow/postgres_test.go
  internal/integration-tests/worker/workflow/workflow-integration_test.go
  internal/testutil/testdata/postgres/edgecases/create-tables.sql
Labels: bug

#3233 Update the Datastream endpoint GCS connection to retrieve the most recent run ID from storage instead of Temporal.
  .gitignore
  backend/internal/cmds/mgmt/serve/connect/cmd.go
  backend/internal/connectiondata/connectiondata.go
  backend/internal/connectiondata/gcp.go
  backend/internal/gcp/client.go
  backend/pkg/integration-test/mux.go
  internal/benthos/benthos-builder/builders/gcp-cloud-storage.go
Labels: Devex

#3244 adds fix that filters out duplicate serials
  backend/gen/go/db/dbschemas/postgresql/system.sql.go
  backend/pkg/dbschemas/sql/postgresql/queries/system.sql
Labels: bug

#3243 NEOS-1739: adds webhook workflow
  .mockery.yml
  backend/dev/build/Dockerfile.dev
  backend/gen/go/db/account-hooks.sql.go
  backend/gen/go/db/mock_Querier.go
  backend/gen/go/db/models.go
  backend/gen/go/db/querier.go
  backend/gen/go/protos/mgmt/v1alpha1/account_hook.pb.go
  backend/gen/go/protos/mgmt/v1alpha1/account_hook.pb.json.go
  backend/gen/go/protos/mgmt/v1alpha1/mgmtv1alpha1connect/account_hook.connect.go
  backend/gen/go/protos/mgmt/v1alpha1/mgmtv1alpha1connect/mock_AccountHookServiceClient.go
  backend/internal/cmds/mgmt/serve/connect/cmd.go
  backend/internal/dtomaps/account-hooks.go
  backend/internal/ee/hooks/accounts/service.go
  backend/pkg/integration-test/clients.go
  backend/pkg/integration-test/mux.go
  backend/protos/mgmt/v1alpha1/account_hook.proto
  backend/services/mgmt/v1alpha1/account-hooks-service/service.go
  backend/sql/postgresql/queries/account-hooks.sql
  backend/sql/postgresql/schema/20250207180739_add-account-hooks.down.sql
  backend/sql/postgresql/schema/20250207180739_add-account-hooks.up.sql
  compose.yml
  compose/temporal/.env
  compose/temporal/compose.yml
  docs/openapi/mgmt/v1alpha1/account_hook.openapi.yaml
  docs/openapi/neosync.mgmt.v1alpha1.yaml
  docs/protos/mgmt/v1alpha1/account_hook.proto.mdx
  docs/protos/proto-sidebars.js
  docs/protos/proto_docs.json
  frontend/packages/sdk/src/client/mgmt/v1alpha1/account_hook_pb.ts
  internal/integration-tests/api/account-hooks-service_integration_test.go
  internal/integration-tests/worker/workflow/process-account-hook-workflow-integration_test.go
  python/src/neosync/mgmt/v1alpha1/account_hook_pb2.py
  python/src/neosync/mgmt/v1alpha1/account_hook_pb2.pyi
  python/src/neosync/mgmt/v1alpha1/account_hook_pb2_grpc.py
  worker/dev/build/Dockerfile.dev
  worker/internal/cmds/worker/serve/serve.go
  worker/pkg/workflows/datasync/activities/sync/mock_BenthosStreamManagerClient.go
  worker/pkg/workflows/ee/LICENSE.md
  worker/pkg/workflows/ee/account_hooks/activities/execute/activity.go
  worker/pkg/workflows/ee/account_hooks/activities/execute/activity_test.go
  worker/pkg/workflows/ee/account_hooks/activities/hooks-by-event/activity.go
  worker/pkg/workflows/ee/account_hooks/activities/hooks-by-event/activity_test.go
  worker/pkg/workflows/ee/account_hooks/events/events.go
  worker/pkg/workflows/ee/account_hooks/workflow/register/register.go
  worker/pkg/workflows/ee/account_hooks/workflow/workflow.go
Labels: enhancement

#3248 tweaks pg index query, changes schema init ordering
  backend/gen/go/db/dbschemas/postgresql/system.sql.go
  backend/pkg/dbschemas/sql/postgresql/queries/system.sql
  backend/pkg/sqlmanager/mysql/mysql-manager.go
  backend/pkg/sqlmanager/postgres/postgres-manager.go
  internal/ee/mssql-manager/ee-mssql-manager.go
  worker/pkg/workflows/datasync/activities/run-sql-init-table-stmts/init-statement-builder_test.go
Labels: bug

#3250 Adds table sync max concurrency limit
  internal/temporal/clientmanager/manager.go
  worker/pkg/workflows/datasync/workflow/workflow.go
Labels: enhancement

#3249 Use Postgres Cursors in selects for better memory management
  backend/pkg/sqlmanager/postgres/postgres-manager.go
  backend/services/mgmt/v1alpha1/job-service/jobs.go
  worker/pkg/benthos/sql/input_sql_raw.go
Labels: enhancement

#3252 Adds environment variable for table sync max currency limit
  charts/neosync/README.md
  compose.dev.yml
  compose.yml
  worker/charts/worker/README.md
  worker/charts/worker/templates/_helpers.tpl
  worker/charts/worker/values.yaml
  worker/dev/helm/helmfile.yaml
  worker/pkg/workflows/datasync/workflow/workflow.go
Labels: Improvement

#3253 Lowers max in flight on new jobs
  frontend/apps/web/app/(mgmt)/[account]/jobs/util.ts
  frontend/apps/web/components/jobs/Form/DestinationOptionsForm.tsx
  internal/benthos/benthos-builder/builders/gcp-cloud-storage.go
  internal/benthos/benthos-builder/builders/sql-util.go
Labels: enhancement

#3254 Fixes worker environment variable: TABLESYNC_MAX_CONCURRENCY
  worker/charts/worker/templates/_helpers.tpl
Labels: bug

#3255 adds transaction error to critical errs
  worker/pkg/benthos/utils.go
Labels: bug

#3256 Fixes foreign key statement bugs in postgres manager
  backend/gen/go/db/dbschemas/postgresql/mock_Querier.go
  backend/gen/go/db/dbschemas/postgresql/querier.go
  backend/gen/go/db/dbschemas/postgresql/system.sql.go
  backend/gen/go/protos/mgmt/v1alpha1/connection_data.pb.go
  backend/internal/connectiondata/sql.go
  backend/pkg/dbschemas/sql/postgresql/queries/system.sql
  backend/pkg/sqlmanager/mock_SqlDatabase.go
  backend/pkg/sqlmanager/mysql/mysql-manager.go
  backend/pkg/sqlmanager/postgres/postgres-manager.go
  backend/pkg/sqlmanager/postgres/postgres-manager_test.go
  backend/pkg/sqlmanager/sql-manager.go
  backend/protos/mgmt/v1alpha1/connection_data.proto
  cli/internal/cmds/neosync/sync/sync.go
  docs/openapi/mgmt/v1alpha1/connection_data.openapi.yaml
  docs/openapi/neosync.mgmt.v1alpha1.yaml
  docs/protos/mgmt/v1alpha1/connection_data.proto.mdx
  docs/protos/proto_docs.json
  frontend/packages/sdk/src/client/mgmt/v1alpha1/connection_data_pb.ts
  internal/ee/mssql-manager/ee-mssql-manager.go
  internal/integration-tests/sqlmanager/mysql/mysql-manager_integration_test.go
  internal/integration-tests/sqlmanager/postgres/postgres-manager_integration_test.go
  internal/integration-tests/sqlmanager/postgres/testdata/create-schemas.sql
  internal/integration-tests/sqlmanager/postgres/testdata/setup.sql
  internal/integration-tests/worker/querybuilder/testdata/postgres/setup.sql
  internal/testutil/testdata/postgres/subsetting/create-tables.sql
  python/src/neosync/mgmt/v1alpha1/connection_data_pb2.py
  sqlc.yaml
Labels: bug

#3258 fixes delete schedule wrapping
  backend/services/mgmt/v1alpha1/job-service/jobs.go
Labels: bug

#3259 Add job destination validation in proto and sync
  backend/protos/mgmt/v1alpha1/job.proto
  internal/benthos/benthos-builder/benthos-builder.go
Labels: Improvement

#3262 Fix connection data service not supporting SQLServer
  backend/internal/connectiondata/connectiondata.go
  frontend/apps/web/app/(mgmt)/[account]/new/job/schema/page.tsx
Labels: bug

#3263 Adds Resumable Sync
  internal/benthos-stream/client.go
  internal/benthos/benthos-builder/builders/sql.go
  internal/continuation-token/continuation-token.go
  internal/integration-tests/worker/workflow/datasync-workflow.go
  worker/internal/cmds/worker/serve/serve.go
  worker/pkg/benthos/config.go
  worker/pkg/benthos/environment/environment.go
  worker/pkg/benthos/sql/input_sql_raw.go
  worker/pkg/benthos/sql/input_sql_raw_test.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/benthos-builder.go
  worker/pkg/workflows/datasync/activities/shared/shared.go
  worker/pkg/workflows/datasync/activities/sync/activity.go
  worker/pkg/workflows/datasync/activities/sync/activity_test.go
  worker/pkg/workflows/datasync/activities/sync/mock_BenthosStreamClient.go
  worker/pkg/workflows/datasync/activities/sync/mock_BenthosStreamManagerClient.go
  worker/pkg/workflows/datasync/workflow/workflow.go
  worker/pkg/workflows/tablesync/activities/sync/activity.go
  worker/pkg/workflows/tablesync/activities/sync/activity_test.go
  worker/pkg/workflows/tablesync/workflow/register/register.go
  worker/pkg/workflows/tablesync/workflow/workflow.go
Labels: enhancement

#3273 Fixes SQLServer new destination form
  frontend/apps/web/app/(mgmt)/[account]/new/job/[id]/destination/page.tsx
Labels: bug

#3272 NEOS-1753: Fixes SQLServer schema initialization for encrypted triggers
  backend/pkg/mssql-querier/system.sql.go
  backend/pkg/sqlmanager/mssql/mssql-manager.go
  backend/pkg/sqlmanager/sql-manager.go
  docs/docs/schema-init/overview.md
  docs/sidebars.ts
  internal/ee/mssql-manager/ee-mssql-manager.go
  internal/ee/mssql-manager/generate-sql.go
  internal/integration-tests/sqlmanager/mssql/mssql-manager_integration_test.go
  internal/integration-tests/sqlmanager/mssql/testdata/source-setup/009.sql
  internal/integration-tests/sqlmanager/mssql/testdata/source-setup/010.sql
Labels: bug

#3274 NEOS-1747, NEOS-1754: Updates to on conflict and other async sql mechs
  frontend/apps/web/components/jobs/Form/MssqlDBDestinationOptionsForm.tsx
  frontend/apps/web/components/jobs/Form/MysqlDBDestinationOptionsForm.tsx
  frontend/apps/web/components/jobs/Form/PostgresDBDestinationOptionsForm.tsx
  frontend/apps/web/yup-validations/transformer-validations.ts
  go.mod
  worker/pkg/benthos/sql/input_sql_raw.go
  worker/pkg/benthos/sql/output_sql_insert.go
  worker/pkg/benthos/sql/output_sql_update.go
Labels: bug

#3279 fixes loki query to include child workflows
  backend/services/mgmt/v1alpha1/job-service/runs.go
Labels: bug

#3281 Adds tests for resumable sync
  .mockery.yml
  backend/gen/go/db/dbschemas/postgresql/mock_Querier.go
  backend/pkg/mssql-querier/mock_Querier.go
  backend/pkg/table-dependency/table-dependency_test.go
  go.mod
  internal/benthos-stream/mock_BenthosStreamClient.go
  internal/benthos-stream/mock_BenthosStreamManagerClient.go
  internal/integration-tests/sqlmanager/mssql/mssql-manager_integration_test.go
  internal/integration-tests/sqlmanager/mssql/testdata/source-setup/004.sql
  internal/integration-tests/sqlmanager/postgres/postgres-manager_integration_test.go
  internal/integration-tests/sqlmanager/postgres/testdata/setup.sql
  internal/integration-tests/worker/workflow/postgres_test.go
  internal/integration-tests/worker/workflow/types.go
  internal/integration-tests/worker/workflow/workflow-integration_test.go
  worker/pkg/workflows/datasync/workflow/workflow.go
  worker/pkg/workflows/datasync/workflow/workflow_test.go
  worker/pkg/workflows/tablesync/activities/sync/activity_test.go
  worker/pkg/workflows/tablesync/workflow/workflow_test.go
Labels: Devex

#3284 Adds expiration limit to redis keys
  worker/pkg/benthos/redis/output_hash.go
Labels: Devex

#3282 Integration tests for resumable sync
  internal/benthos/benthos-builder/benthos-builder.go
  internal/benthos/benthos-builder/builders/sql.go
  internal/benthos/benthos-builder/shared/types.go
  internal/integration-tests/worker/querybuilder/query-builder_integration_test.go
  internal/integration-tests/worker/workflow/datasync-workflow.go
  internal/integration-tests/worker/workflow/mssql_test.go
  internal/integration-tests/worker/workflow/postgres_test.go
  worker/internal/cmds/worker/serve/serve.go
  worker/pkg/benthos/sql/input_sql_raw.go
  worker/pkg/query-builder2/querybuilder.go
  worker/pkg/query-builder2/subset.go
  worker/pkg/query-builder2/wrapper.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/activity.go
  worker/pkg/workflows/datasync/activities/gen-benthos-configs/benthos-builder.go
  worker/pkg/workflows/tablesync/workflow/register/register.go
  worker/pkg/workflows/tablesync/workflow/workflow.go
  worker/pkg/workflows/tablesync/workflow/workflow_test.go
Labels: Devex

#3269 NEOS-1743: Workflows now emit account hooks for Job Run Create Success Failure
  backend/services/mgmt/v1alpha1/job-service/jobs.go
  internal/ee/events/events.go
  internal/integration-tests/worker/workflow/datasync-workflow.go
  internal/integration-tests/worker/workflow/process-account-hook-workflow-integration_test.go
  worker/internal/cmds/worker/serve/serve.go
  worker/pkg/workflows/datasync/workflow/register/register.go
  worker/pkg/workflows/datasync/workflow/workflow.go
  worker/pkg/workflows/datasync/workflow/workflow_test.go
  worker/pkg/workflows/ee/account_hooks/activities/execute/activity.go
  worker/pkg/workflows/ee/account_hooks/activities/execute/activity_test.go
  worker/pkg/workflows/ee/account_hooks/workflow/workflow.go
  worker/pkg/workflows/ee/account_hooks/workflow/workflow_test.go
Labels: enhancement

#3288 Makes page size persist page refresh
  frontend/apps/web/app/(mgmt)/[account]/connections/components/ConnectionsTable/data-table.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/components/DataTable/data-table-pagination.tsx
  frontend/apps/web/app/(mgmt)/[account]/jobs/components/DataTable/data-table.tsx
  frontend/apps/web/app/(mgmt)/[account]/runs/[id]/components/JobRunActivityTable/data-table-pagination.tsx
  frontend/apps/web/app/(mgmt)/[account]/runs/[id]/components/JobRunActivityTable/data-table.tsx
  frontend/apps/web/app/(mgmt)/[account]/runs/components/JobRunsTable/data-table-pagination.tsx
  frontend/apps/web/app/(mgmt)/[account]/runs/components/JobRunsTable/data-table.tsx
  frontend/apps/web/app/(mgmt)/[account]/settings/api-keys/components/ApiKeysTable/data-table-pagination.tsx
  frontend/apps/web/app/(mgmt)/[account]/settings/api-keys/components/ApiKeysTable/data-table.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/components/SystemTransformersTable/data-table-pagination.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/components/SystemTransformersTable/data-table.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/components/UserDefinedTransformersTable/data-table-pagination.tsx
  frontend/apps/web/app/(mgmt)/[account]/transformers/components/UserDefinedTransformersTable/data-table.tsx
  frontend/apps/web/components/table/data-table-pagination.tsx
Labels: enhancement

#3291 NEOS-1744: Adds Account Hooks UI and Docs
  backend/gen/go/db/account-hooks.sql.go
  backend/gen/go/protos/mgmt/v1alpha1/account_hook.pb.go
  backend/protos/mgmt/v1alpha1/account_hook.proto
  backend/sql/postgresql/queries/account-hooks.sql
  docs/docs/guides/account-hooks.md
  docs/docs/guides/job-hooks.md
  docs/openapi/mgmt/v1alpha1/account_hook.openapi.yaml
  docs/openapi/neosync.mgmt.v1alpha1.yaml
  docs/sidebars.ts
  docs/src/CustomComponents/IconHandler.tsx
  docs/static/img/accounthooks/account-hooks-overview.png
  docs/static/img/accounthooks/new-hook-form.png
  docs/static/img/jobhooks/job-hooks-overview.png
  docs/static/img/jobhooks/new-hook-form.png
  frontend/apps/web/app/(mgmt)/[account]/jobs/[id]/hooks/components/HooksCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/settings/hooks/components/AccountHookWebhookForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/settings/hooks/components/EditHookButton.tsx
  frontend/apps/web/app/(mgmt)/[account]/settings/hooks/components/EditHookForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/settings/hooks/components/FormInputs.tsx
  frontend/apps/web/app/(mgmt)/[account]/settings/hooks/components/HookCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/settings/hooks/components/HooksCard.tsx
  frontend/apps/web/app/(mgmt)/[account]/settings/hooks/components/NewHookButton.tsx
  frontend/apps/web/app/(mgmt)/[account]/settings/hooks/components/NewHookForm.tsx
  frontend/apps/web/app/(mgmt)/[account]/settings/hooks/components/RemoveHookButton.tsx
  frontend/apps/web/app/(mgmt)/[account]/settings/hooks/components/stores.ts
  frontend/apps/web/app/(mgmt)/[account]/settings/hooks/components/validation.ts
  frontend/apps/web/app/(mgmt)/[account]/settings/hooks/page.tsx
  frontend/apps/web/app/(mgmt)/[account]/settings/layout.tsx
  frontend/apps/web/app/api/config/config.ts
  frontend/apps/web/app/config/app-config.ts
  frontend/packages/sdk/src/client/client.ts
  frontend/packages/sdk/src/client/index.ts
  frontend/packages/sdk/src/client/mgmt/v1alpha1/account_hook_pb.ts
  python/src/neosync/__init__.py
  python/src/neosync/__init__.pyi
  python/src/neosync/client.py
  python/src/neosync/mgmt/v1alpha1/account_hook_pb2.py
Labels: enhancement

#3294 Makes JS VM Logic more defensive against panics
  internal/javascript/functions/benthos/functions.go
  internal/javascript/functions/functions.go
  internal/javascript/functions/functions_test.go
  internal/javascript/functions/neosync/functions.go
  worker/pkg/benthos/javascript/benthos_value_api.go
  worker/pkg/benthos/javascript/benthos_value_api_test.go
  worker/pkg/benthos/javascript/processor.go
  worker/pkg/benthos/javascript/processor_test.go
Labels: bug

#3295 Removes root react-icons import from FE
  frontend/apps/web/app/(mgmt)/[account]/new/connection/dynamodb/page.tsx
  frontend/apps/web/components/connections/ConnectionIcon.tsx
  frontend/apps/web/next.config.mjs
  frontend/package-lock.json
Labels: Tech Debt

#3301 Fixes web worker warning in next15
  frontend/apps/web/components/jobs/SchemaTable/ImportJobMappingsButton.tsx
  frontend/apps/web/components/useJsonFileDownload.tsx
Labels: Tech Debt

#3305 Updates mysql and postgres processors to handle null strings in json columns
  internal/database-record-mapper/mysql/mapper.go
  internal/database-record-mapper/mysql/mapper_test.go
  internal/database-record-mapper/postgres/mapper.go
  internal/database-record-mapper/postgres/mapper_test.go
  worker/pkg/benthos/sql/processor_neosync_mysql.go
  worker/pkg/benthos/sql/processor_neosync_pgx.go
Labels: bug
